### ISSUE TITLE
Работа с IPV6 в linux

### ISSUE THREAD

**Issue by Vision20202** [3proxy/3proxy#1000]
Исходные данные. 
Интерфейс основного интернет подключения (кабель) с IP: 192.168.1.10
Модем, с работающим IPV4 и IPV6, с постоянным IP адресом - т.е. зафиксированный в настройках модема: 192.168.21.100

Дальше будет конфиг. Работает на Windows. С некоторыми проблемами, но в целом работает. И очень странно работает в Linux. Прокси работает ровно до того момента, как происходит смена внешнего IP адреса модема, т.е. переключение из режима 4G в 3 G и обратно. Если эту процедуру не делать, то в Линуксе будет работать. Только сделал - всё, прокси перестает работать. Причем потом может спонтанно, спустя много часов заработать, но опять же не надолго, видимо до временной потери интернета на модеме. 

`daemon 

#monitor /usr/local/3proxy/3proxy_21.1_ipv6.txt

auth none

nscache6 65535
nscache 65536
nserver 192.168.21.1

maxconn 5000

proxy -64 -n -p17500 -i192.168.1.10 -e192.168.21.100

flush`

Повторюсь еще раз. В Win работает, а Linux только до временной потери интернета на модеме. Дальше в логе появляются строки с ошибкой 13. Что с этим делать - голову уже сломал. Пробовал разные версии 3proxy, собирал из исходников - не помогает. 

Пробовал биндить по имени интерфейса - -De(eth9) - никак не помогает. 
Такое проверял:
nserver [2001:4860:4860::8844]
nserver [2001:4860:4860::8888]
тоже не помогает. 

P.S.
Еще одна проблема, возможно связана с IPV6, но не уверен. Если выполнить команду sudo /etc/init.d/3proxy stop и потом sudo /etc/init.d/3proxy start что по сути является перезапуском 3proxy, отваливаются модемы. Вот буквально, нельзя зайти в настройки модема, они как будто не видимы в системе. Причем отваливается обычно только часть модемов, рандомно. Приходится перезапускать все интерфейсы. Пока точно не понял связано ли это с активированным IPV6 на модеме, если кто-то будет готов помочь, то протестирую.

**Comment by z3APA3A** [comment]
Смотри настройки роутинга, после отваливания интерфейса у тебя трафик может пойти в другой интерфейс, настрой source routing или делай биндинг к интерфейсу. Биндинг к интерфейсу требует рутовых прав и не будет работать с setgid/setuid/chroot.
