### ISSUE TITLE
All sites work except instagram

### ISSUE THREAD

**Issue by edikosmos** [3proxy/3proxy#1001]
Hi all, does anyone know what this could be about? 
Absolutely all sites open except instagram.
Proxies were raised on linux, it can't be that 3 mobile proxies/ports banned instagram at once?

**Comment by edikosmos** [comment]
HTTP/1.0 502 Bad Gateway
Connection: close
Content-type: text/html; charset=utf-8

curl: (56) Received HTTP code 502 from proxy after CONNECT
ping gives this error

**Comment by ezbik** [comment]
3proxy log ?

**Comment by z3APA3A** [comment]
It's quite possible TLS/TCP/HTTP fingerprint or some combination was banned.
