### ISSUE TITLE
Filter smtp traffic using parent proxy

### ISSUE THREAD

**Issue by gentoosys** [3proxy/3proxy#1002]
Hi. Is it possible to configure 3proxy to block smtp ports (25,587,465), when using parent proxy?

Right now I am using DNAT scheme to forward traffic to external parent servers. I tried 3proxy, but cpu load was much higher. 
In my scheme, I tried ndpi netfilter module to filter smtp traffic (https://github.com/vel21ripn/nDPI/issues/187)
If that will never work, I will try 3proxy again, if it is possible to configure such way. Thanks

**Comment by ezbik** [comment]
Yes it's possible. Read documentation about acl.

**Comment by z3APA3A** [comment]
```
deny * * * 25,587,465
allow *
parent ....
```
