### ISSUE TITLE
UDP is not working for me

### ISSUE THREAD

**Issue by xploader** [3proxy/3proxy#1003]
Hello! I'm trying to make a proxy that will work with UDP but is not working for some reason. I would appreciate if anyone can give me some advice. Thanks

This is my config file

```
#!/bin/3proxy
#daemon

chroot /usr/local/3proxy proxy proxy
include /conf/3proxy.cfg

#! /usr/local/bin/3proxy

nserver 8.8.8.8

nscache 65536

timeouts 1 5 30 60 180 15 60

users root:CL:pass root2:Cl:pass2

#log /var/log/3proxy.log

#rotate 30

setgid 13

setuid 13

auth none

allow root2
allow root

socks -a -p3128 -i192.168.0.3  -Deenp0s8
flush

```

**Comment by z3APA3A** [comment]
`-Deenp0s8` does not work with setuid. `-e` may be required if socks client requires external IP.
If it does not help, enable logging and check logs
