### ISSUE TITLE
PR_END_OF_FILE_ERROR

### ISSUE THREAD

**Issue by Vision20202** [3proxy/3proxy#1009]
Сразу скажу, что это проблема не столько 3proxy, сколько конкретного мобильного оператора. У него есть явные проблемы при загрузке сайтов, которые подключены к cloudflare. Если взять модем с этим оператором и попробовать загрузить сайты за CF, то сначала очень-очень долго ничего не происходит и потом начинает грузится сайт. А вот если настроить прокси из модема, то вылетает ошибка PR_END_OF_FILE_ERROR.
В логе это выглядит так:

```
23-02-2024 19:56:47 | - | 192.168.1.211:1685 | 104.21.21.194:443 | 104.21.21.194:443 | 0 | 0 | domen.ru | CONNECT sanepidem.ru:443 HTTP/1.1 | 00000
23-02-2024 19:56:51 | - | 192.168.1.211:1686 | 104.21.74.254:443 | 104.21.74.254:443 | 0 | 0 | domen2.ru | CONNECT vseoglazah.ru:443 HTTP/1.1 | 00000
```
Ошибки как бы нет, но у меня ощущение, что это можно поправить если настроить тайм-аут, но вот есть ли такая опция в 3proxy? 
Хром чуть иначе выдает ошибку - ERR_TUNNEL_CONNECTION_FAILED.

**Comment by z3APA3A** [comment]
По этому логу соединение было закрыто без отправки данных.

Таймауты можно установить командой timeouts.

**Comment by Vision20202** [comment]
Т.е. тут таймауты выставлять больше смысла нет?
