### ISSUE TITLE
How to foce 3proxy to use system dns servers

### ISSUE THREAD

**Issue by Sirvaude** [3proxy/3proxy#1010]
I have in my /etc/resolv.conf

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

And 3proxy.cfg:

```
nscache 65536
nserver 8.8.8.8
nserver 8.8.4.4
```

When I run some nslookup test, it shows the system is actually using the google dns servers but every request coming through the proxy, is not.

It's taking the router dns or something, how can I force it to use the /etc/resolv.conf servers or custom nserver ones?

I don't really need to use the /etc/resolv.conf but nserver is not working.

Is there a way?

The same exact config is working just fine in my second server but this ISP is causing this somehow. I mean, the request is being resolved by other dns servers and I can't access the router to check them.

Is there a way I can fix this?

EDIT: It seems my ISP is hijacking the DNS requests, so is there an alternative to fix this?

**Comment by z3APA3A** [comment]
3proxy users system resolvers by default (if nserver is not configured). Use e.g. DoH to avoid hijacking.

**Comment by Sirvaude** [comment]
Thanks, fixed
