### ISSUE TITLE
How to use fakeresolve for parent proxy

### ISSUE THREAD

**Issue by meotimdihia** [3proxy/3proxy#1012]
I can't get it work. Getting this error: page.goto: net::ERR_TUNNEL_CONNECTION_FAILED

```
fakeresolve
allow * 127.0.0.1 * *
parent 1000 http p.webshare.io [user] [password]
proxy -p23001 -i127.0.0.1 -a
```

If I change `p.webshare.io` to their IP then it works but p.webshare.io has multiple IPs. Please help with this problem.

**Comment by z3APA3A** [comment]
fakeresolve blocks all name resolutions, so you have to specify parent by IP or specify "fakeresolve" after "parent"
