### ISSUE TITLE
3proxy и внешний динамический IP

### ISSUE THREAD

**Issue by Vision20202** [3proxy/3proxy#1015]
Есть ли варианты, как сделать доступным из вне локальной сети, прокси, если на самом компе динамический адрес? Может там через сервисы типа No-IP или подобные? Не могу сообразить как это может работать.

**Comment by z3APA3A** [comment]
Посмотрите какие сервисы динамической регистрации поддержвиаются в вашем машрутизаторе, если IP белый. Если IP не белый, то можно попробовать использовать ngrok или другой сервис проброса портов.
