### ISSUE TITLE
Не запускается сервис

### ISSUE THREAD

**Issue by zara6502** [3proxy/3proxy#1016]
Лог не создается, сервис не стартует, Win10 x64, запускал с правами админа, файл конфига лежит в папке с бинарником, если указать полный путь к конфигу ситуация не меняется.

PS C:\3proxy-0.9.3-x64\bin64> .\3proxy.exe --install 3proxy.cfg
Failed to create service: No error

**Конфиг:**
maxconn 100
nserver 10.1.2.1
nserver 10.2.2.2
nscache 65536
service
log C:\3proxy-0.9.3-x64\log\3proxy.log D
logformat "- +_L%t.%.  %N.%p %E %U %C:%c %R:%r %O %I %h %T"
rotate 30
auth iponly
external 192.168.43.85
internal 0.0.0.0
flush
auth none
dnspr

**Обрезал конфиг до:**
maxconn 100
service
log C:\3proxy-0.9.3-x64\log\3proxy.log D
logformat "- +_L%t.%.  %N.%p %E %U %C:%c %R:%r %O %I %h %T"
rotate 30
auth iponly
external 192.168.43.85
internal 0.0.0.0

Ситуация не изменилась.

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtor.asp#SERVICE

**Comment by z3APA3A** [comment]
Запускать надо через runas или cmd/powershell запускать от администратора (не просто из-под учетки администратора, а через меню по правой кнопки мыши), проверить что у системной записи есть доступ к папке или назначить сервису правильную учетку, проверить что служба еще не установлена, если установлена можно удалить через --remove
.\ не стоит использовать, это относительный путь - или указывать полный или просто по имени

**Comment by zara6502** [comment]
> Запускать надо через runas или cmd/powershell запускать от администратора (не просто из-под учетки администратора, а через меню по правой кнопки мыши c Shift+Control), проверить что у системной записи есть доступ к папке или назначить сервису правильную учетку, проверить что служба еще не установлена, если установлена можно удалить через --remove .\ не стоит использовать, это относительный путь - или указывать полный или просто по имени

Спасибо за оперативный ответ, это Powershell, что видно по тексту, сам PS перед этим запущен от имени админа, то есть условие запуска оболочки с правами админа выполняется.
.\ обязательна при работе с PS и не влияет на запуски других программ и сервисов, если у 3proxy это "фишка", то Ок.
Инструкция прочитана до начала установки и все условия выполнены, если какие-то иные условия и применял, то исключительно в попытке разобраться с невозможностью установки сервиса.
А самое удивительное что я так и не смог запустить сервис ни разу, но сегодня утром после включения ПК он появился в списке служб, а узнал я об этом пытаясь запустить другой прокси и когда тот заругался что 8080 уже занят, то закрались подозрения.

**Comment by zara6502** [comment]
Вроде работает, спасибо.

**Comment by z3APA3A** [comment]
Это значит что сервис уже был создан, но не был запущен, его надо было стартануть. При создании он скорей всего не стартанулся из-за неправильного на тот момент конфига. Если его в списке сервисов не показывали, то надо было оснастку переоткрыть
