### ISSUE TITLE
3proxy ничего не пишет в лог-файлы

### ISSUE THREAD

**Issue by it800** [3proxy/3proxy#1017]
На нескольких серверах (Alma Linux/Rocky Linux) столкнулся со странным дефектом: 3proxy формирует, но никак не наполняет лог-файлы. Настройки проверил досконально, права на каталоги и файлы - всё чётко. Но нет. Файл имеет нулевой размер, ротируется на новый в полночь (игнорируется rotate 30) и всё.

Настройки логирования:
log /var/log/3proxy/3proxy.log D
logformat "L%d-%m-%Y %H:%M:%S %z %N.%p %E %U %C:%c %R:%r %O %I %h %T"
rotate 30

![image](https://github.com/3proxy/3proxy/assets/146009019/e3f00a8d-c3af-4a35-92f3-ead3905152e2)

cat /etc/os-release 
NAME="AlmaLinux"
VERSION="9.3 (Shamrock Pampas Cat)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.3 (Shamrock Pampas Cat)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.3"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"

**Comment by z3APA3A** [comment]
Что в конфиге помимо log и что в /etc/3proxy.cfg?

**Comment by it800** [comment]
> Что в конфиге помимо log и что в /etc/3proxy.cfg?
Весь конфиг у меня в /etc/3proxy.cfg, вывод из него ниже, приватное заменил. 
На всякий случай: proxy:x:1000:1000::/home/proxy:/sbin/nologin

setgid 1000
setuid 1000

nserver 1.1.1.1
nserver 8.8.8.8

timeouts 1 5 30 60 180 1800 15 60
nscache 65536

daemon

users user:CL:password

auth strong
flush
proxy -n -a -p12080 -iIP -eIP
socks -n -a -p12081 -iIP -eIP
allow user

log /var/log/3proxy/3proxy.log D
logformat "L%d-%m-%Y %H:%M:%S %z %N.%p %E %U %C:%c %R:%r %O %I %h %T"
rotate 30

**Comment by z3APA3A** [comment]
В 3proxy порядок команд имеет значение, log действует на сервисы которые ниже него, поставьте log до proxy/socks
