### ISSUE TITLE
fakeresolve и nserver в одном конфиге

### ISSUE THREAD

**Issue by philinp** [3proxy/3proxy#1019]
нужен один socks с fakeresolve, а второй который может резолвить.
можно ли это сделать в одном конфиге?

этот конфиг не работает, так как оба socks резолвят через 8.8.8.8:

```
fakeresolve
auth iponly

allow * *
socks -p1001
flush

nserver 8.8.8.8
nscache 65535

allow * *
socks -p1002
flush

end

```

**Comment by z3APA3A** [comment]
Сделай два отдельных конфига, запусти два инстанса прокси
