### ISSUE TITLE
0.9.4 Ошибка в работе DNS proxy

### ISSUE THREAD

**Issue by JMKh3r** [3proxy/3proxy#1026]
Если на прокси-сервере настроено несколько ip-адресов и в конфигурации не указан ip-адрес, на котором слушать порт (слушать будет на 0.0.0.0), то на запрос разрешения DNS-имени от клиента 3proxy может отвечать с другого ip-адреса, чем на который пришел запрос.
При этом клиент отбросит такой сетевой пакет и сгенерит ошибку таймаута DNS-сервера.
Тест производился на следующей конфигурации: прокси Win Server 2008r2, клиент Win10

**Comment by z3APA3A** [comment]
Да, в стандартном сокетном API нет возможности получить IP адрес с которого пришел UDP пакет, а планов использовать RAW сокеты или системнозависимые API в 3proxy нет, поэтому в таких конфигурациях следует указывать internal.
