### ISSUE TITLE
Вопрос по авторизации

### ISSUE THREAD

**Issue by Vision20202** [3proxy/3proxy#1028]
Можно ли сделать так, что если запрос к прокси идёт из локальной сети, то авторизации нет, если из внешней - то нужен логин и пароль? Или же хотя бы или как вариант - прописать разрешенные IP - локальная сеть и конкретные IP из внешней сети?

**Comment by z3APA3A** [comment]
```
auth iponly strong
users user:CL:password
allow * 192.168.0.0/16
deny -
allow *
proxy
```
