### ISSUE TITLE
build docker from Dockerfile.full error

### ISSUE THREAD

**Issue by Cr4ckPwd** [3proxy/3proxy#1030]
I build docker from Dockerfile.full error, today
![image](https://github.com/3proxy/3proxy/assets/84202581/fdb9f3fb-8b34-43c7-a191-3a87a9ce11fa)

**Comment by z3APA3A** [comment]
Should be fixed with ab8db00b1fdd57b8728790da91c23f137ede105f

**Comment by Cr4ckPwd** [comment]
I figured out the issue. It was due to the latest version of the Docker image GCC being faulty. When I used an older version, it worked fine.
