### ISSUE TITLE
Блокировка/доступ по URL, не доменному имени.

### ISSUE THREAD

**Issue by bkmz12332** [3proxy/3proxy#1031]
Добрый день.
Подскажите пожалуйста, хочу разрешить доступ конкретному пользователю к url, например https://mysite.com/foo/bar, но похоже, что можно разрешить только доменное имя или ip адрес?

**Comment by z3APA3A** [comment]
В https все урлы идут внутри шифрованного TLS соединения. То что ты хочешь сделать реализуемо, но только с подменой сертификата, см плагины SSLPlugin и PCREPlugin
https://3proxy.ru/plugins/

**Comment by bkmz12332** [comment]
Понял, большое спасибо.
