### ISSUE TITLE
How to make IE in windows7/10  work with 3proxy

### ISSUE THREAD

**Issue by oldunclez** [3proxy/3proxy#1033]
My goal is to make IE in windows7/10 to use 3proxy( socks5) .
But there is a  problem :
IE will resolve dns name locally, but it is dns-hijacking  https://github.com/3proxy/3proxy/issues/1032

Is it possble to force 3proxy to resolve the dns name , event though , client-host has resolve it locally .

**Comment by z3APA3A** [comment]
See https://github.com/3proxy/3proxy/commit/013d4bc3339d8e3760855eae448972f3f34cba14 available in master branch

Alternatively, you can use SSLPlugin 
https://3proxy.ru/plugins/SSLPlugin/
https://github.com/3proxy/3proxy/blob/master/doc/html/plugins/SSLPlugin.html
