### ISSUE TITLE
Не запускается 3proxy с несколькими конфигурационными файлами

### ISSUE THREAD

**Issue by Vision20202** [3proxy/3proxy#1035]
Пытаюсь настроить 3proxy на Ubuntu 16.04. Сделал всё по инструкции: https://selectel.ru/blog/tutorials/how-to-install-and-configure-3proxy-proxy-servers-on-ubuntu/
И вот что имею в результате:

```
3proxy.service - 3proxy Proxy Server
   Loaded: loaded (/etc/systemd/system/3proxy.service; enabled; vendor preset: enabled)
   Active: active (exited) since Wed 2024-05-22 20:43:32 MSK; 2min 56s ago
  Process: 3526 ExecStart=/usr/bin/3proxy /etc/3proxy/3proxy.cfg (code=exited, status=0/SUCCESS)
 Main PID: 3526 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/3proxy.service
           ├─3529 /usr/bin/3proxy /etc/3proxy/3proxy.cfg
           ├─3530 sh -c /usr/bin/3proxy /etc/3proxy/3proxy_11.1.txt
           └─3531 /usr/bin/3proxy /etc/3proxy/3proxy_11.1.txt

May 22 20:43:32 Ubuntu systemd[1]: Started 3proxy Proxy Server.

```
 Стартует только два конфига: 3proxy.cfg и 3proxy_11.1.txt хотя вот содержимое 3proxy.cfg: 

```
setgid 129
setuid 121

daemon

monitor /etc/3proxy/3proxy.cfg

system "/usr/bin/3proxy /etc/3proxy/3proxy_11.1.txt"
system "/usr/bin/3proxy /etc/3proxy/3proxy_12.1.txt"
system "/usr/bin/3proxy /etc/3proxy/3proxy_13.1.txt"
```

Вот содержимое 3proxy_11.1.txt:

```
monitor /etc/3proxy/3proxy_11.1.txt

nscache 65536
nserver 192.168.11.1

maxconn 5000

proxy -n -a -p8281 -i192.168.1.70 -e192.168.11.100

flush
```
Файл 3proxy_12.1.txt аналогично сделан, только там адрес модема другой: 192.168.12.100 и nserver соответствующий. Но почему не стартует с конфигом 3proxy_12.1.txt  и 3proxy_13.1.txt

Куда копать, в чём может быть проблема?

**Comment by z3APA3A** [comment]
Зачем вызывать прокси с конфигом через system в другом конфиге?
Я не вижу в статье на которую вы ссылаетесь такогого. Что именно вы хотите сделать не понятно, но происходит следующее - на строке
system "/usr/bin/3proxy /etc/3proxy/3proxy_11.1.txt"
3proxy запускает другой процесс 3proxy и ждет его окончания

**Comment by Vision20202** [comment]
Я хочу запускать каждый прокси со своим конфигом, чтобы ДНС были разные. Как через один конфиг, загрузить остальные прокси, для каждого из которых есть свой конфиг? Точно такая возможность есть. Более того, на минте 
вот такое срабатывает:
system "/usr/bin/3proxy /etc/3proxy/3proxy_11.1.txt"
system "/usr/bin/3proxy /etc/3proxy/3proxy_12.1.txt"
system "/usr/bin/3proxy /etc/3proxy/3proxy_13.1.txt"
Как всё таки правильно прописать в 3proxy.cfg ссылки на другие конфиги?

**Comment by z3APA3A** [comment]
Если вы хотите запускать через systemd как в статье указано, то запускайте 3 инстанса сервиса
https://opensource.com/article/20/12/multiple-service-instances-systemctl

**Comment by Vision20202** [comment]
Разве 3proxy не позволяет из своего основного конфига, запустить любое количество прокси со своим конфигом?

**Comment by z3APA3A** [comment]
3proxy позволяет любую внешнюю команду выполнить, но проще это сделать через bash-скрипт, зачем для этого прокси использовать? Что будет происходить при попытке остановить/перезапустить такой сервис?

**Comment by Vision20202** [comment]
Мне тут сложно сказать, что будет. Но в Минте конструкция работает безупречно, а в Убунту - нет. Ну т.е. вы рекомендуете стартовать, к примеру, 20 прокси со своим конфигом отдельно? Т.е. прописываем 20 раз запуск 3proxy cо своим конфигом, по аналогии с тем, как я сейчас запускаю 3proxy.cfg?

**Comment by z3APA3A** [comment]
Я не знаю что именно вы хотите, но запуск через system ровно это и делает - запускает прокси со своим конфигом отдельно, только при запуске через system все это неуправляемо. При запуске через инстансы systemd каждым инстансом можно управлять.
