### ISSUE TITLE
Limiting the number of devices

### ISSUE THREAD

**Issue by egasvegas1109** [3proxy/3proxy#1037]
Is it possible to limit the number of simultaneous connections to a specific port by the client's IP? The word "connections" refers to the number of devices. For example, I want a maximum of two devices to be able to connect to the server on the port, then the third device should be reset.

**Comment by ezbik** [comment]
connlim <rate> <period> <userlist> <sourcelist> <targetlist> <targetportlist> <operationlist> <weekdayslist> <timeperiodslist>

**Comment by egasvegas1109** [comment]
> ```
> connlim <rate> <period> <userlist> <sourcelist> <targetlist> <targetportlist> <operationlist> <weekdayslist> <timeperiodslist>
> ```

Спасибо, то есть если я хочу, чтобы к моему серверу на порту 10000 подключалось максимум два устройства, то это должно выглядеть примерно так:?
`
proxy -p3128
proxy -s0 -p10000 -a

connlim 2'

**Comment by ezbik** [comment]
нет. ~~почитайте мануал , займет минут 30, зато полностью разберетесь.~~
Идея в том, что надо знать IP этих устройств, каждому из 2-х дать определенное кол-во коннекшенов и ограничить остальным. Если их IP не знаете, или они меняются - то обсуждение не имеет смысла. Воспользуйтесь iptables + module recent или module limit.

**Comment by egasvegas1109** [comment]
> Воспользуйтесь iptables + module recent или module limit.

Спасибо за совет, но я уже пробовал iptables и либо я чего-то не понимаю, либо он работает не так как надо для меня. Я использовал команду `sudo iptables -A INPUT -p 6 --syn --dport 10000 -m connlimit --connlimit-above 1 -j DROP`, но когда к серверу подключается **два устройства с разными IP**, то запрет на подключение для второго не срабатывает вообще никак.
![Безымянный](https://github.com/3proxy/3proxy/assets/50997210/3baf85b2-58ad-471f-9d14-b73acdc9ebd2)
