### ISSUE TITLE
Вопрос по блок листу 

### ISSUE THREAD

**Issue by NeroGeer** [3proxy/3proxy#1038]

**Comment by NeroGeer** [comment]
Есть ли возможность блокировки под сайта например как в данном случае yandex.ru\games . т.е не блокировать весь яндекс а тоолько ветку games ибо сейчас как я понимаю проверка идет только по строчке Url до доменного имени

**Comment by z3APA3A** [comment]
Можно блокировать через PCREPlugin, но в https:// все запросы идут внутри TLS с шифрованием, поэтому это возможно только если использовать еще и SSLPlugin с подменным сертификатом
