### ISSUE TITLE
About dnspr

### ISSUE THREAD

**Issue by imclint21** [3proxy/3proxy#1039]
Hi,

I try to create a DNS fowarder using `dnspr` but then use it by the proxy, is it possible?

So in my case proxy would use 127.0.0.1:5353.

```
nserver 127.0.0.1 
dnspr -l -p5353
proxy -a -t -p1001
```

**Comment by z3APA3A** [comment]
dnspr uses nserver and shares DNS cache with proxy, so there is no difference between resolving via dnspr and resolving via nserver except there is no local network traffic.

If for some reason you really want it, just use 2 separate proxy instances with separate config, one for proxy and one for dnspr.
