### ISSUE TITLE
Whitelist + DNS

### ISSUE THREAD

**Issue by imclint21** [3proxy/3proxy#1040]
Hi,

Let's assume we have a proxy and we use a DNS server located at `127.0.0.1`.

```
nserver 127.0.0.1
proxy -a -t -l -p1001
```

In this DNS server, let say we block a big list of domains, does there any possibility to allow it from the 3proxy configuration? something like `nsrecord` but that would specify the `nserver` to use for some domains.

Regards

**Comment by z3APA3A** [comment]
It depends on what "block" means. If DNS returns some IP, you can parent traffic for this IP to another proxy instance. If server does not reply or replies with error, you can set second nserver. In more sophisticated cases you may need something like dnsmasq.
