### ISSUE TITLE
Difficulty with Proxy Chaining in 3proxy

### ISSUE THREAD

**Issue by NaturalT314** [3proxy/3proxy#1041]
**Description:**
I am encountering issues with setting up proxy chaining in my 3proxy configuration. The chaining does not work as expected, and I need assistance to resolve this.

**Configuration Details:**
```ini
log logs

nscache 65536
nserver 8.8.8.8
nserver 8.8.4.4

users proxy:CL:proxy

proxy -p22222 -n -a

allow proxy
parent 1000 http 127.0.0.1 8000 proxy proxy

internal 0.0.0.0
external 0.0.0.0
```
I used this command to verify 

```bash
curl -v --proxy http://proxy:proxy@localhost:22222 http://eth0.me
```

And this is what the logs look like after this command
```
240604090928.824 22222 00000 proxy 127.0.0.1:58462 188.114.97.3:80 95 557 0 GET http://eth0.me/ HTTP/1.1
```

What I essentially need is to setup 2 proxies and redirect the traffic from one proxy to the other.

**Comment by z3APA3A** [comment]
This configuration misses "auth" command, "auth strong" is required for your config.

**Comment by NaturalT314** [comment]
Thanks for your response

I thought this was the problem, I just tried adding this and the problem is not solved
