### ISSUE TITLE
bandlimout - doesn't work unless TCP buffer is filled 

### ISSUE THREAD

**Issue by ezbik** [3proxy/3proxy#1042]
I encountered an issue that `bandlimout` starts shaping only after several MB since data flow start. The conf file is very simple.

```
auth none
proxy -a -n -4  -p8999
socks -n -4  -p5999
bandlimin   10000000 *
bandlimout  10000000 *
```

Test:

1. prepare a large file with urandom as `/root/file.txt`
2. `curl -X POST https://postman-echo.com/post --data-binary @/root/file.txt -x socks5h://127.0.0.1:5999 >/dev/null`

You will see that shaping happens after Curl has sent ~4..10MB of data.

**Workaround**

Lower sending&receiving OS buffers .

```
sysctl -w net.ipv4.tcp_wmem="4096 16384 819200"
sysctl -w net.ipv4.tcp_rmem="4096 16384 819200"
```

**Situation after applying the workaround**

Shaping happens immediately.

**Question**

Can the same behavior be implemented right in 3proxy?

**Comment by z3APA3A** [comment]
3proxy acts on application level and it shapes this traffic, but it happens _after_traffic is received from the socket. 3proxy can not shape the traffic before it arrives, so yes, if you want to prevent bursts you must configure network buffers / tcp windows.
