### ISSUE TITLE
Connection closed when using CURL -v -L method

### ISSUE THREAD

**Issue by slaiddominio** [3proxy/3proxy#1043]
I am applying the configuration given below, however when using the CURL -v -L method, I receive a closed connection return.

Apparently CURL is unable to authenticate to the Proxy server.

curl -x "http://146.192.15.175:22500" www.netflix.com -v -L

# 3proxy.cfg
daemon
nserver 8.8.8.8
nserver 8.8.4.4
nserver [2001:4860:4860::8888]
nserver [2001:4860:4860::8844]
nscache 65536
nscache6 65536
timeouts 1 5 30 60 180 1800 15 60
stacksize 6000
maxconn 121500
connlim 40500 1 * * * * * * *

#log /var/log/3proxy/3proxy.log 
#rotate 2

#flush
#internal 127.0.0.1
#allow * 127.0.0.1
#admin

flush
allow * 127.0.0.1 * *
tcppm 180 1.1.1.1 80

include /opt/3proxyipv6/config_1.cfg

# config_1.cfg
flush
auth iponly strong
include /opt/3proxyipv6/blockedPorts.cfg
include /opt/3proxyipv6/userAllow_1.cfg
include /opt/3proxyipv6/random_1.cfg
include /opt/3proxyipv6/ipAllow_1.cfg
deny *
include /opt/3proxyipv6/ipv6_1.cfg

# ipAllow_1.cfg
allow * 185.259.226.85

**Comment by z3APA3A** [comment]
Your config only allows connections from 127.0.0.1 to port 180. There is no proxy on 22500
