### ISSUE TITLE
If creating a TCP map with tcppm to a SOCKS5 proxy server, being them listening in different IPs, there is no UDP connectivity.

### ISSUE THREAD

**Issue by przemyslaw0** [3proxy/3proxy#1044]
When I create a TCP port mapping using tcppm to a SOCKS5 proxy server listening in another local IP in my host, there is no UDP connectivity al all:

```
$ socks -l -i192.168.1.5 -p1080
240606230122.678 1080 00465 - 192.168.1.5:48225 1.1.1.1:53 0 0 0 UDPMAP 1.1.1.1:53
240606230127.683 1080 00465 - 192.168.1.5:47427 1.1.1.1:53 0 0 0 UDPMAP 1.1.1.1:53
240606230132.685 1080 00465 - 192.168.1.5:34289 1.1.1.1:53 0 0 0 UDPMAP 1.1.1.1:53
240606230201.045 1080 00465 - 192.168.1.5:53383 2606:4700:4700::1111:53 0 0 0 UDPMAP 2606:4700:4700::1111:53
240606230206.049 1080 00465 - 192.168.1.5:59717 2606:4700:4700::1111:53 0 0 0 UDPMAP 2606:4700:4700::1111:53
240606230211.053 1080 00465 - 192.168.1.5:51793 2606:4700:4700::1111:53 0 0 0 UDPMAP 2606:4700:4700::1111:53

$ tcppm -l -i127.0.0.1 1080 192.168.1.5 1080
240606224908.807 1080 00000 - 127.0.0.1:1080 0.0.0.0:0 0 0 0 Accepting connections [935847/211969856]
240606230122.678 1080 00000 - 127.0.0.1:36227 192.168.1.5:1080 13 12 0 192.168.1.5
240606230127.683 1080 00000 - 127.0.0.1:52469 192.168.1.5:1080 13 12 0 192.168.1.5
240606230132.685 1080 00000 - 127.0.0.1:44385 192.168.1.5:1080 13 12 0 192.168.1.5
240606230201.045 1080 00000 - 127.0.0.1:35163 192.168.1.5:1080 25 12 0 192.168.1.5
240606230206.049 1080 00000 - 127.0.0.1:49793 192.168.1.5:1080 25 12 0 192.168.1.5
240606230211.053 1080 00000 - 127.0.0.1:35219 192.168.1.5:1080 25 12 0 192.168.1.5
```

Is there a way to correct this behavior?

**Comment by z3APA3A** [comment]
Socks uses UDP between client and proxy for UDP map, tcppm only passes control connection.

**Comment by z3APA3A** [comment]
UDPPM for SOCKSv5 works this way:
1. client establishes command connection via TCP and sens UDPPM command
2. proxy opens dynamic UDP port on external interface
3. proxy opens dynamic UDP port on internal interface
4. proxy report internal UDP port to client
5. client sends UDP packets prefixed with destination ip:port to proxy's internal UDP port, proxy removes prefix and relays packet via external UDP port
6. proxy receives UDP packets on external UDP port, prefixes this packet with source IP:port and relays this packet to client via internal UDP port

so, it's impossible to place tcppm/udppm between client and proxy. It could be possible to place another SOCKSv5 proxy and configure another proxy as a parent. Unfortunetely, 3proxy does not currentl support parent SOCKS for UDP traffic.
