### ISSUE TITLE
Command: 'plugin' failed with code 1, line 7

### ISSUE THREAD

**Issue by Afam007** [3proxy/3proxy#1046]
I keep getting this error when I try using SSLPlugin on Ubuntu 22.04

```
> Jun 20 09:55:17 ip-172-31-31-110 systemd[1]: Started 3proxy tiny proxy server.
> Jun 20 09:55:17 ip-172-31-31-110 3proxy[1253]: Command: 'plugin' failed with code 1, l>Jun 20 09:55:17 ip-172-31-31-110 3proxy[1253]: Command: 'include' failed with code 7, >Jun 20 09:55:17 ip-172-31-31-110 systemd[1]: 3proxy.service: Deactivated successfully.
```

This is my config file 

```
nscache 65536
nserver 8.8.8.8
nserver 8.8.4.4

config /conf/3proxy.cfg
monitor /conf/3proxy.cfg

log /logs/3proxy-%y%m%d.log D
rotate 60
counter /count/3proxy.3cf

users $/conf/passwd

include /conf/counters
include /conf/bandlimiters

auth strong
deny * * 127.0.0.1
allow *

plugin /libexec/SSLPlugin.ld.so ssl_plugin
ssl_server_cert /cert/fullchain.pem
ssl_server_key /cert/privkey.pem
ssl_serv
proxy -p33128
ssl_noserv
proxy -n
socks
flush
allow admin

admin -p8080

```
The required file is in the correct directory
I didn't edit anything else , I don't know what's wrong

**Comment by z3APA3A** [comment]
By default, 3proxy chroot's to /usr/local/3proxy and uses 2 config files: pre-chroot and post-chroot, pre-chroot config does "chroot" and includes post-chroot config. This config file is post-chroot. Either place .so file within this dir and use relative path, or place "plugin" command into pre-chroot config file. Or remove chroot.

**Comment by Afam007** [comment]
I added the plugin with full path to the pre-chroot file , it works now , thanks 🙏
