### ISSUE TITLE
3proxy close tcp

### ISSUE THREAD

**Issue by hunterhe23** [3proxy/3proxy#1047]
usually client or server closes tcp.
but sometimes 3proxy may close tcp activity.
when will that happen?

**Comment by z3APA3A** [comment]
check the logs, after connection successfully established, 3proxy can close connection on:
- either connection side closes connection
- network error
- inactivity timeout (CONNECTION_LONG, 1800 seconds by default)

**Comment by hunterhe23** [comment]
i have a problem.
after a success http proxy request,  neither client nor server closes the connection, 3proxy first close tcp to server. 
then client sends another http request in the same tcp to 3proxy in 1s.
3proxy reset tcp to client, so the request fails.
why and how to resolv?
thanks.

**Comment by hunterhe23** [comment]
please see attachment tcpdump. (x.x.72.26 is client, x.x.46.147 is 3proxy, x.x.23.70 is server.)
![3proxy](https://github.com/3proxy/3proxy/assets/14845810/af07835c-797f-422f-9a5a-1f21bb93e636)

**Comment by z3APA3A** [comment]
Probably server sent 
Connection: close 
header. Under this condition connection is closed. I have no idea why RST (26) is sent, it should not happen, because normal FIN sequence is initiated, as seen in previous packet (25). Packets 25 and 26 have same ACK, so it can not be result of some packet delayed in network stack. It looks like a bug in TCP stack implementation. Try to switch off TCP offload in network card.

**Comment by z3APA3A** [comment]
Also, I have no idea why client sent another request after connection: close, if this is a case.

**Comment by hunterhe23** [comment]
i have two 3proxy, both version 0.9.4.
same http request to vdata.amap.com, one works nomally, the other is abnormal.
sever sent Connection: keep-alive to 3proxy.
one 3proxy sent Connection: close to client, and it worked nomally.
the other 3proxy removed field Connection, and client sent another http request which failed, cause 3proxy closed tcp to server.
when did 3proxy change Connection: keep-alive to Connection: close?
when did 3proxy remove field Connection?
is that related to linux system?

**Comment by z3APA3A** [comment]
what do you have in logs?

**Comment by hunterhe23** [comment]
no errors in system or 3proxy logs.
3proxy didn't log another request reset by itself.
tcpdump shows the problem.
server always sent connection:keepalive.
3proxyA sent connection:close.
3proxyB removed connection.
![server to 3proxy(allways connection keep-alive)](https://github.com/3proxy/3proxy/assets/14845810/6cb57ff2-7ada-4c55-bf69-946ebd564108)
![3proxyA to client (connection-close)](https://github.com/3proxy/3proxy/assets/14845810/e4c5c9c5-c96b-4cec-942f-7de07f01e666)
![3proxyB to client (no connection info)](https://github.com/3proxy/3proxy/assets/14845810/fa9312ef-e3e1-4127-b277-99738fd009a5)

**Comment by hunterhe23** [comment]
would you please take a look at this issue again?

**Comment by z3APA3A** [comment]
If you see no request in the logs while the logs are enabled, it means request was not processed by the proxy. Check tcpdumps both between client and proxy and between proxy and destination and look if you have any request (may be different one) from the same tcp client port in the proxy logs. If there are no requests from the same port, it means this requests were never seen by 3proxy, may be you have something else on the same port. If there are requests from the same port, but no specific request, send full tcpdumps and logs to 3proxy@3proxy.ru. Also, you may try to use current master version, it has some bugfixes.

**Comment by hunterhe23** [comment]
sorry, mail to 3proxy@3proxy.ru failed, shows Connect to remote host error.
Any other email?

**Comment by hunterhe23** [comment]
have sent to 3proxy@3proxy.ru from gmail.
