### ISSUE TITLE
failed to read: /etc/3proxy/private.key

### ISSUE THREAD

**Issue by Afam007** [3proxy/3proxy#1048]
I use a private key from certbot  . The file permissions are good , but I keep getting this

```
172-31-45-247 systemd[1]: Stopped 3proxy tiny proxy server.
Jun 20 14:54:51 ip-172-31-45-247 systemd[1]: Started 3proxy tiny proxy server.
Jun 20 14:54:51 ip-172-31-45-247 3proxy[2390]: failed to read: /etc/3proxy/private.key
Jun 20 14:54:51 ip-172-31-45-247 3proxy[2390]: failed to read: /etc/3proxy/private.key
Jun 20 14:54:51 ip-172-31-45-247 3proxy[2390]: failed to read: /etc/3proxy/private.key
```
I have changed permissions , but it's not working ,I also tried moving the file , doesn't work too

**Comment by z3APA3A** [comment]
Check
- 3proxy account (one set with setgid/setuid or chroot) has permission to access the files
- if chroot is used (default Linux configuration) key must be either placed within chroot dir and relative path must be used, or plugin must be started/configured before chroot (in pre-chroot config file).
