### ISSUE TITLE
Можно ли на уровне filter_header_cli (FILTER ACTION API) изменять parent proxy?

### ISSUE THREAD

**Issue by n-e-x-u-s-i-v** [3proxy/3proxy#1051]
У меня есть плагин, который из БД подтягивает прокси с паролями типа SOCKS5, и мне бы бы хотелось на уровне FILTER ACTION особенно filter_header_cli изменять перенаправление на parent данного запроса от клиента, скажите пожалуйста возможно ли это ? Или придется писать свою реализацию общения сокета таким образом. 
В идеале хотелось бы видеть следующее:
SOCKS 3proxy socks5://127.0.0.1 :8765   (без парольная) ---> API filter_header_cli change parent proxy (Обновление remsock соединения с parent proxy)

Заранее спасибо!

**Comment by z3APA3A** [comment]
А зачем filter_header_cli? Он в SOCKS вообще не используется, т.к. там нет заголовков.
По каким параметрам будет выбираться родительский прокси?

**Comment by n-e-x-u-s-i-v** [comment]
Чтобы было наглядно, вот мой curl
 curl  -x socks5://127.0.0.1:8765 'https://ya.ru' -v -H 'user-agent:L:2'
 
 
 
```
static FILTER_ACTION
sql_proxy_filter_header_cli(
        void *fc,
        struct clientparam *param,
        unsigned char **buf_p,
        int *bufsize_p,
        int offset,
        int *length_p
) {
в buf_p (тут как раз у меня запрос на ya.ru  и заголовок user-agent)

 const char *error;
    char *cidr;
    struct chain *chains;
    int erroffset;
    int offsetcount = 0;
    const char *result;
    debug_print("--- sql_proxy_filter_header_cli ---");
    char pattern[] = "user-agent:.*L:(\\d+)";
    int offsets[OFFSETCOUNT];
    pcre *re = pcre_compile(pattern, PCRE_CASELESS, &error, &erroffset, NULL);
    if (re == NULL) {
        debug_print("PCRE compilation failed at offset %d: %s/n", erroffset, error);
        return REJECT;
    }
    offsets[1] = 0;
    offsetcount = pcre_exec(re, NULL,  (char *)*buf_p, *length_p, offsets[1], offsets[1], offsets, OFFSETCOUNT);
    if(offsetcount >= 0) {
        if(pcre_get_substring((char *)*buf_p, offsets, offsetcount, 1, &result) >= 0){
        // выполнить перенаправление на parent
        
        // тяну с БД прокси по id из user-agent
        chains = get_chain_by_proxy(&proxy, param->srv->acl->chains);
        // используем логику работы chain...
  chains = get_chain_by_proxy(&proxy, param->srv->acl->chains);
    if (!chains) {
        chains = malloc(sizeof(struct chain));
        if (!chains) {
            debug_print("--- chains malloc failed ---");
            return REJECT;
        }
        memset(chains, 0, sizeof(struct chain));
        chains->weight = 1000;
        chains->type = R_SOCKS5;
        cidr = strchr(proxy.url, '/');
        if (cidr) *cidr = 0;
        if (!pl->getip46(46, (unsigned char *) proxy.url, (struct sockaddr *) &chains->addr)) return (5);
        chains->exthost = (unsigned char *) strdup(proxy.url);
        *SAPORT(&chains->addr) = htons((unsigned short) atoi((char *) proxy.port));
        chains->extuser = (unsigned char *) strdup(proxy.user);
        chains->extpass = (unsigned char *) strdup(proxy.pass);
        if (!param->srv->acl->chains) {
            param->srv->acl->chains = chains;
        } else {
            struct chain *tmpchain;
            for (tmpchain = param->srv->acl->chains; tmpchain->next; tmpchain = tmpchain->next);
            tmpchain->next = chains;
        }
    }
// но к сожалению перенаправление на remsock уже не проходит...
        }
```

**Comment by z3APA3A** [comment]
Для того чтобы прокси увидел заголовки внутри https надо использовать SSLPlugin и перенаправление в локальный HTTP прокси. 
HTTP запрос и заголовки в таком случае парсятся уже внутри HTTP proxy. В такой конфигурации у тебя уже не получится что-либо сделать с соединением, потому что в этот момент уже установлено соединение с родительским сервером и произведен TLS хендшейк

**Comment by n-e-x-u-s-i-v** [comment]
Я использую SSLPlugin для того чтобы расшифровать трафик, это не проблема, тут все хорошо.
 
Владимир,а  что посоветуете, чтобы на уровне чтение заголовков сделать переадресацию на тот parent который был определен в user-agent исходя из моей ситуации?

**Comment by z3APA3A** [comment]
Можно делать разные паренты по разным портам прокси, на клиенте родительский прокси выбирать за счет выбора порта - это можно сделать штатно.

allow *
parent 1000 socks5+ socks.1 ...
proxy -p10001

flush
allow *
parent 1000 socks5+ socks.2 ...
proxy -p10002


flush
allow *
parent 1000 socks5+ socks.3 ...
proxy -p10003
...

Если все-таки хочется передавать с клиента, то самый просто способ - передавать не через HTTP заголовок, а через логин к SOCKS прокси
