### ISSUE TITLE
Прокси выдают ошибку коннекта

### ISSUE THREAD

**Issue by mongusss** [3proxy/3proxy#1052]
У меня стояла задача сделать фильтрацию трафика на основе 3proxy
вот мой конфиг

daemon
maxconn 20000
nserver 8.8.8.8
nserver 8.8.4.4
nserver 1.1.1.1
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
setgid 65***
setuid 65***
stacksize 8000
monitor /etc/3proxy/3proxy.cfg
auth iponly
flush
allow * 65.109.***.***  *instagram.com
#MIX
connlim 100 parent 1000 http тут прокси
proxy -n -p15001 -a
flush

Сам vps довольно мощный. Но при попытке подключения хотя бы в 30-40 потоков, начинает выдавать ответы что прокси не валидный. Соответственно обращение идет к ip vps через порт 15001

что можно дописать в конфиге чтобы решить эту проблему?

**Comment by z3APA3A** [comment]
Так у тебя connlim 100

**Comment by mongusss** [comment]
Спасибо Понял
