### ISSUE TITLE
Changing userpass and proxy configuration without stopping the software

### ISSUE THREAD

**Issue by DevilLord41** [3proxy/3proxy#1055]
so `/etc/init.d/3proxy reload` can works but if there active connection in socks it wont be cut off the connection. How do we change the config file without and cut off the active connection if the auth are not valid anymore and keep active for connection that the auth still valid?

**Comment by z3APA3A** [comment]
SIGUSR1 causes 3proxy to reload configuration without reboot. Default init.d script does so
https://github.com/3proxy/3proxy/blob/master/scripts/init.d/3proxy.sh

**Comment by z3APA3A** [comment]
Sorry, I misread the question.  See `force` command:
```

force
noforce
If force is specified for service, configuration reload will require all current sessions of this service to be re-authenticated. If ACL is changed or user account is removed, old connections which do not match current are closed. noforce allows to keep previously authenticated connections.
```

**Comment by DevilLord41** [comment]
I have my configuration as:

force
auth strong cache
allow xxx
maxconn 200
socks -pxxxx -ixxxxx -exxx
flush

But the socks that been invalid still active.

**Comment by z3APA3A** [comment]
describe full testing scenario with your actions step-by-step.
