### ISSUE TITLE
Помогите пж побороть проблему 7 - неверный пароль (crypt)

### ISSUE THREAD

**Issue by SkyLine66rus** [3proxy/3proxy#1056]
Уже всю голову сломал, какой нужен пароль длина символы и т.д нужны, чтобы победить ошибку 7 - неверный пароль (crypt)
curl: (7) Failed to connect to *IP* port *PORT*: Connection refused
Делал все строчные буквы и пароль, с верхним регистром делал, по итогу при проверке работы
Даже решил уже использовать символ % в пароле. Результат без изменений
curl -I -x socks5://*логин*:*пароль*@*IP*:*PORT* https://google.ru | grep HTTP
Результат один и тот же
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to *IP* port *PORT*: Connection refused

Содержимое файла 3proxy.cfg
#!/bin/3proxy
#daemon
pidfile /var/run/3proxy/3proxy.pid
chroot /usr/local/3proxy proxy proxy
include /conf/3proxy.cfg
nscache 65536
nserver *IP*
config /conf/3proxy.cfg
monitor /conf/3proxy.cfg
log /logs/3proxy-%y%m%d.log D
rotate 60
counter /count/3proxy.3cf
users $/conf/passwd  # в этом файле сохраняются proxy-аккаунты
include /conf/counters
include /conf/bandlimiters
auth strong
deny * * 127.0.0.1
allow * * * 80 HTTP
allow * * * 443 HTTPS
socks -n -p*PORT* -a
flush
allow
maxconn 384
EOF

Буду признателен за помощь.

**Comment by z3APA3A** [comment]
Что и в каком формате в conf/passwd ?

**Comment by z3APA3A** [comment]
```
allow * * * 80 HTTP
allow * * * 443 HTTPS

```
это не будет работать для SOCKS, если ты хочешь фильтровать по методам HTTP, то надо сделать локальное перенаправление в HTTP прокси, SOCKS использует методы CONNECT/BIND/UDPASSOC.

**Comment by SkyLine66rus** [comment]
> Что и в каком формате в conf/passwd ?

testuser:CR:$1$2118012$2sRuZJfbinSbOMl2wl9wr1
В таком формате пишется все логины и пароли.


> ```
> allow * * * 80 HTTP
> allow * * * 443 HTTPS
> ```
> 
> это не будет работать для SOCKS, если ты хочешь фильтровать по методам HTTP, то надо сделать локальное перенаправление в HTTP прокси, SOCKS использует методы CONNECT/BIND/UDPASSOC.

Может быть так будет проще понять что я хочу добиться.
Чтобы через прокси весь трафик из браузера шёл через прокси. Чем проще тем лучше как говорится.
Вполне возможно у меня весь файл конфигурации кривой ?
---------------
Кучу ресурсов просмотрел везде разное пишут про файл конфигурации. Уже не знаю какой правильный и корректный.
Напишите корректный файл конфига.

**Comment by z3APA3A** [comment]
Пароль который приходит от curl не соответствует криптованному паролю $1$2118012$2sRuZJfbinSbOMl2wl9wr1, чем ты криптил пароли?

**Comment by SkyLine66rus** [comment]
> Пароль который приходит от curl не соответствует криптованному паролю $1$2118012$2sRuZJfbinSbOMl2wl9wr1, чем ты криптил пароли?

Ничем не шифровал
Прописывал через скрипт
bash /etc/3proxy/conf/add3proxyuser.sh <логин> <пароль> 
Соответственно после этого писал лог и пасс который прописывал через скрипт.

**Comment by z3APA3A** [comment]
Проверь через nycrypt (есть в бинарниках 3proxy)
`mycrypt 2118012 testpass` 
(вместо testpass - пароль с которым идешь в curl, если не получается 2sRuZJfbinSbOMl2wl9wr1 - значит пароль не тот

или попробуй задать пароли в открытом тексте
user:CL:password

**Comment by SkyLine66rus** [comment]
> Проверь через nycrypt (есть в бинарниках 3proxy) `mycrypt 2118012 testpass` (вместо testpass - пароль с которым идешь в curl, если не получается 2sRuZJfbinSbOMl2wl9wr1 - значит пароль не тот
> 
> или попробуй задать пароли в открытом тексте user:CL:password

Выяснил что проблема была не с авторизацией. А в том что прокси не хотела слушать порт который был ей задан в конфиге
Нашел нормальную статью по установке. Ровный конфиг. Всё работает
