### ISSUE TITLE
connlimit dont work in version .94 any alternative ? 

### ISSUE THREAD

**Issue by jacoballen55** [3proxy/3proxy#1058]
connection stops when we use connlimit randomly, I found if we remove this parameter it works well,
any alternative where we can set number of threads allowed or connlimit to work?

**Comment by z3APA3A** [comment]
Use current master, it has e.g. this patch https://github.com/3proxy/3proxy/commit/6532163f01c9fd09ccda9cda70f6a2ea6ba56cb7
