### ISSUE TITLE
How to restrict access to sock and proxy services when there is traffic redirection to parent socks5?

### ISSUE THREAD

**Issue by IlyaIndigo** [3proxy/3proxy#1061]
With a simple configuration without redirection there are no problems with access configuration.
```
auth iponly

allow * 127.0.0.1,1.2.3.4 *
deny *

socks -p1080
proxy -a -p3128
```
With simple redirection where you need to make services local only too.
```
internal 127.0.0.1
auth iponly

allow *
parent 1000 socks5 2.2.2.2 1080 user password

socks -p1080
proxy -a -p3128
```
How can I now define a similar access list as in the first example for socks and proxy so that they don't affect parent?

**P.S. I figured out how to do it!**
Just replace **deny** with **parent**.
```
auth iponly

allow * 127.0.0.1,1.2.3.4 *
parent 1000 socks5 2.2.2.2 1080 user password

socks -p1080
proxy -a -p3128
```
Only a strange effect that confused me and I thought for a long time that it doesn't work.
The value **127.0.0.1** in the `allow` directive somehow has the same effect as **127.0.0.0/8**.

And the application crashes if you write **deny** between `allow` and `parent` directives.

**Comment by z3APA3A** [comment]
> The value 127.0.0.1 in the allow directive somehow has the same effect as 127.0.0.0/8.

probably your testing scenario was wrong, e.g. you change internal address of the proxy instead of source address for connection, you can try to add logging to see source address.

**Comment by IlyaIndigo** [comment]
```
logformat "L%C - %U [%d/%o/%Y:%H:%M:%S %z] ""%T"" %E %I %O %N/%R:%r"
log /var/log/3proxy/3proxy.log D
rotate 30
archiver xz xz -9e %F

auth iponly
allow * 127.0.0.1 *
parent 1000 socks5 SERVER PORT USER PASSWORD
socks -p1080
```
```
curl -x socks5://127.0.0.1:1080 https://2ip.io
curl -x socks5://127.58.98.187:1080 https://2ip.io
```
```
127.0.0.1 - - [23/Aug/2024:00:00:10 +0300] "CONNECT 195.201.201.33:443" 00000 5946 840 SOCK5/SERVER:PORT
127.0.0.1 - - [23/Aug/2024:00:00:13 +0300] "CONNECT 195.201.201.33:443" 00000 5946 840 SOCK5/SERVER:PORT
```
That is, any local address is still converted to 127.0.0.1 for the proxy.
I don't see a problem with this, but I'm curious to know why this happens.

**Comment by z3APA3A** [comment]
You do not set source address for curl, request to 127.58.98.187 is made from default interface address, that is 127.0.0.1. Source address is 127.0.0.1, destination address in 127.58.98.187. You can log destination address with `%i`
