### ISSUE TITLE
Using 3proxy to build proxy service

### ISSUE THREAD

**Issue by ak3zaidan** [3proxy/3proxy#1065]
Hello I am quite new to this area and I'm wondering If someone can guide me on building a proxy service. I currently spend hundreds renting out proxies in the form:

IP Address;Port Number; Login ID;Password

I use these proxies to re route my traffic so I don't get rate limited for Shopify API calls, and also to make unique selenium sessions. I want to be able to generate thousands of unique proxies. I also want to create residential, live, resis proxies in different regions.

I did some research and my current plan is to rent out VPS servers in different regions, downloading Squid/3Proxy software on each server. I also thought of docker containerization. Can anyone point me in the right direction. the image below is an example of what I purchase, and what I aim to build. This is a educational project but will also help me save money.

<img width="1239" alt="Screenshot 2024-08-25 at 1 47 37 PM" src="https://github.com/user-attachments/assets/ab1bddbb-b520-4f34-8027-50d26a883dc8">

**Comment by jelyqs** [comment]
@ak3zaidan 

Ib me
