### ISSUE TITLE
Why Does 3proxy Randomly Select Parent Proxies?

### ISSUE THREAD

**Issue by thanh743** [3proxy/3proxy#1066]
I'm experiencing an issue where 3proxy seems to randomly select between parent proxies, even though I want it to use a specific one for each port. When I connect through port 40000, it occasionally switches between different parent proxies each time I refresh (F5).
Here's my configuration:
allow * * *example1.com*
parent 1000 socks5 147.185.238.169 50087
socks -p40000

allow * * *example2.com*
parent 1000 socks5 147.185.238.169 50085
socks -p40001

Despite this setup, the connections appear to randomly choose between the two parent proxies. How can I configure 3proxy to ensure each port consistently uses its designated parent proxy? Any advice or solutions would be greatly appreciated!

**Comment by TruthFire** [comment]
Add flush between allow comands.
```
allow * * example1.com
parent 1000 socks5 147.185.238.169 50087
socks -p40000
flush

allow * * example2.com
parent 1000 socks5 147.185.238.169 50085
socks -p40001
```
