### ISSUE TITLE
Плагин SSL не работает

### ISSUE THREAD

**Issue by oracleh2** [3proxy/3proxy#1069]
С горем пополам скомпиллировал плагин ССЛ, который не компиллировался по умолчанию. При его использовании получаю ошибку

```
Sep 04 12:49:23 vps151223 systemd[1]: Stopped 3proxy.service - 3proxy tiny proxy server.
Sep 04 12:49:23 vps151223 systemd[1]: Started 3proxy.service - 3proxy tiny proxy server.
Sep 04 12:49:23 vps151223 3proxy[23992]: /bin/3proxy: symbol lookup error: /libexec/SSLPlugin.ld.so: undefined symbol: OPENSSL_init_ssl
Sep 04 12:49:23 vps151223 systemd[1]: 3proxy.service: Main process exited, code=exited, status=127/n/a
Sep 04 12:49:23 vps151223 systemd[1]: 3proxy.service: Failed with result 'exit-code'.
```

Гугл рассказал,  что этот метод используется в openssl 1.1.0 точно, поэтому поставил вместо 3 версии 1.1.1, но ошибка не ушла и дальше уже у меня не хватает компетенции понять что не так и что мне делать. Подскажите как правильно его скомпиллировать и подключить, пожалуйста.

**Comment by usename-Poezd** [comment]
+ 1

**Comment by usename-Poezd** [comment]
У меня такая ошибка, запускал через docker 
`/bin/3proxy: symbol lookup error: /usr/local/3proxy/libexec/SSLPlugin.ld.so: undefined symbol: COMP_get_type`

**Comment by z3APA3A** [comment]
OPENSSL_init_ssl есть во всех версиях начиная с 1.1.0, скорей всего у тебя не установлены хидеры/библиотеки OpenSSL, поэтому были проблемы и с компиляцией. В debian/ubuntu это пакет libssl-dev. В других линуксах может быть что-то другое. Установи библиотеки/хидеры и пересобери все с нуля.

**Comment by IlyaIndigo** [comment]
Так вот для чего в Федоре требуется openssl-devel, понятно!

**Comment by Str1ker17** [comment]
> Также, SSLPlugin нет врелизе 3proxy-0.9.5 для Linux

как человек, который собирал универсальный модуль с поддержкой OpenSSL, скажу - запаришься тащить, сборки под разные дистры и версии OpenSSL могут быть трындец как несовместимы

> /usr/local/bin/3proxy: symbol lookup error: /usr/local/3proxy/libexec/SSLPlugin.ld.so: undefined symbol: COMP_get_type

скомпилили с одним OpenSSL, а запустить пытаетесь под другим, а это ай-яй-яй!

как варик, можно слинковаться статически, на чистом дереве исходников запустите сборку так:

```
make -f Makefile.Linux -e LIBS="-l:libcrypto.a -l:libssl.a -ldl" -e PLUGINS="SSLPlugin"
```

SSLPlugin.ld.so будет весить под 6 мб, но шансы на то, что запустится везде, увеличатся (размер можно попытаться уменьшить через CFLAGS="-ffunction-sections -fdata-sections" LDFLAGS="-Wl,--gc-sections" но это следующий уровень)
