### ISSUE TITLE
a problem about dual stack ipv4&v6

### ISSUE THREAD

**Issue by hunterhe23** [3proxy/3proxy#1071]
3proxy config（ to support both v4 and v6）：
internal [::]
allow * 10.1.2.3 www.baidu.com
log format "%N %E %C %p %n"

when curl -x 10.2.2.2:3128 www.baidu.com at client 10.1.2.3, get error '403 Access Deny'.

3proxy log：
PROXY 00003 ::ffff:10.1.2.3 3128 www.baidu.com

why client ipv4 changed to ::ffff:10.1.2.3?

**Comment by z3APA3A** [comment]
`::` listens IPv6 sockets, `::ffff:10.1.2.3` is hybrid notation for IPv6 mapped IPv4 addresses, see https://en.wikipedia.org/wiki/IPv6_address

allow rule requires IPv6 address in your case, you can use e.g. `::ffff:10.1.2.3` or `::ffff:0a01:0203`
