### ISSUE TITLE
Принудительное включение ipv4

### ISSUE THREAD

**Issue by komel22** [3proxy/3proxy#1074]
Я настроил себе IPv6 прокси. Каждые на своих портах и логино и паролем. использую префикс -64, но на некоторых сайтах плохо работает IPv6 и я хотел бы для них принудительно включать IPv4. Допустим сайт example.com работает прекрасно на IPv6 но вот конкретно страница этого сайта например example.com/test_page/IPv4 не работает и я хотел бы для этой страницы принудительно включать IPv4. Есть ли такая возможность?

**Comment by z3APA3A** [comment]
Отключить IPv6 для конкретного сайта можно попробовать добавив в кеш (nscache6) нулевой (`::`) nsrecord6 или прописав`allow` + `parent` с типом tcp, изменить разрешение имени для отдельной страницы не получится.
