### ISSUE TITLE
3proxy does not match urls that has - and as a result cant block it 

### ISSUE THREAD

**Issue by cyrexer** [3proxy/3proxy#1078]
I want to report a problem ,
The bug is I can block a domains normally in 3proxy conf file .
But any domain has character like (–) I cant ……..
So as an example :
I cant block the domain https://ip-api.com/ or https://ip-scan.com/
Bec the domain itself contain the –
But I can easily block google.com. or yahoo.com or FB.com
 
I guess maybe we need to use escape character ? or its just a bug ?
im using 
tiny proxy server Flatron-0.9.3 ()
 
Let me know and have a nice day !
 
Thanks

**Comment by cyrexer** [comment]
Any one can help ?

**Comment by cyrexer** [comment]
Guys ?!

**Comment by cyrexer** [comment]
Hello TEAM , any one can help ?

**Comment by z3APA3A** [comment]
Use master version, it should be fixed already.
