### ISSUE TITLE
Не работает опция parent c socks5

### ISSUE THREAD

**Issue by Victor3264** [3proxy/3proxy#1080]
Здравствуйте!
3proxy игнорирует опцию parent и конектится напрямую! В логах никакой информации о parent нет!!!
Версия 3proxy-0.9.4 (210702132242) для Windows. Запускаю в Windows 10 Pro
```
timeouts 1 5 30 60 180 1800 15 60
log "C:\ProgramData\3proxy\logs\3proxy-%y%m%d.log" D
auth none
allow *
parent 500 socks5 1.2.3.4 57425 socksuser sockspass
maxconn 25600
socks -p8080

```

**Comment by starter48** [comment]
вместо **auth none** поставь **auth iponly**

**Comment by z3APA3A** [comment]
см FAQ, при auth none отключаются любые ACL и перенаправления, ровно для этого она и нужна
