### ISSUE TITLE
some URLS not being blocked by 3proxy 

### ISSUE THREAD

**Issue by cyrexer** [3proxy/3proxy#1082]
any domain has character like (–) I cant  block it in 3proxy ……..
So as an example :
I cant block the domain https://ip-api.com/ or https://ip-scan.com/
Bec the domain itself contain the –
But I can easily block google.com. or yahoo.com or FB.com

I guess maybe we need to use escape character ? or its just a bug ?
im using
tiny proxy server 3proxy -0.9.3 ()

Any one to help here ?

**Comment by Zeropak** [comment]
Hi, not sure but blocked

You can close the site by IP. For example, Google IP 142.250.178.132

**Comment by cyrexer** [comment]
Hello , Thanks for your reply ,
im sure it does not work , Can you try to block 
https://ip-api.com/ or https://ip-scan.com/
on your side ?

i guess there might be an escape character or a bug here .

Please help !
