### ISSUE TITLE
Bind a username for certain port 

### ISSUE THREAD

**Issue by cyrexer** [3proxy/3proxy#1085]
Hello Folks , 
i have multiple ports listening with different outgoing .

Does 3proxy support binding a specific username for specific listening port/ outgoing address ?

**Comment by cyrexer** [comment]
Hello Support , Can you help ?

**Comment by z3APA3A** [comment]
Userlist is common for all services in proxy config, you have few alternatives:
- Use ACL to limit access to specific service
- Use multiple configs
