### ISSUE TITLE
Ошибка с odbc

### ISSUE THREAD

**Issue by srvh** [3proxy/3proxy#1086]
Debian 12
3proxy установлен с Github, ветка Master
При компиляции добавил -lodbc, удалил -DNOODBC

unixODBC установлен.
cat /etc/odbcinst.ini 
```
[MySQL ODBC 9.1 Unicode Driver]
DRIVER=/usr/lib/x86_64-linux-gnu/odbc/libmyodbc9w.so
UsageCount=1

[MySQL ODBC 9.1 ANSI Driver]
DRIVER=/usr/lib/x86_64-linux-gnu/odbc/libmyodbc9a.so
UsageCount=1
```

cat /etc/odbc.ini

```
[proxy]
Description = MySQL ODBC Driver
Driver = MySQL ODBC 9.1 Unicode Driver
Server = localhost
Database = mydb
User = odbc
Password = FWj32e87
```

Команда isql -v proxy корректно заходит в оболочку SQL запросов.

Добавлено логирование так в файле /etc/3proxy/conf/3proxy.cfg

log &proxy
logformat "-\'+_GINSERT INTO logs VALUES (%t, '%c', '%U', %I)"

При старте 3proxy получаю такие ошибки:
&proxy: Permission denied
Command: 'log' failed with code 1, line 8

Если удалить из конфига эти 2 строки (log и logformat), то 3proxy запускается без ошибок.
В чем может быть причина ?

**Comment by z3APA3A** [comment]
Убедись, что у эккаунта с которым работает прокси есть доступ к файлам ODBC. Так же, если нужно использовать ODBC совместно с chroot вынеси логирование до chroot или откажись от chroot или унаси все компоненты ODBC в chroot.
