### ISSUE TITLE
https SNI через transparent

### ISSUE THREAD

**Issue by githubniko** [3proxy/3proxy#1090]
Здравствуйте!
Хочу решить проблему блокировки ютуба через подключение к ipv6 сети на VPS.

Варианты:
1) proxy -64 -e3a4c:f540:0:3::a -e207.26.55.121: Работает только для ютуба. Инстаграм и другое режется DPI по пути к прокси-серверу.
2) vpn + iptables(80,443) + transparent + proxy -64  : Работает только по ipv4, т.к. transparent не поддерживает SNI?
Тут (https://github.com/3proxy/3proxy/issues/149#issuecomment-292139971) было сказано о планах работы с SNI. Решил уточнить добавлен ли этот функционал?

**Comment by z3APA3A** [comment]
transparent надо использовать не с proxy а с tcppr, proxy ожидает http запрос на входе

если нужен прокси по SNI то можно использовать tlspr в текущем мастере, описание тут
https://github.com/3proxy/3proxy/commit/013d4bc3339d8e3760855eae448972f3f34cba14
