### ISSUE TITLE
Использование объёмных хост-листов для вышестоящих прокси ?

### ISSUE THREAD

**Issue by Baltazar500** [3proxy/3proxy#1091]
Привет.

Как выяснилось, большой хост-лист 3proxy просто не обрабатывает (перевёл хост-лист антизапрета на 148К хостов в приемлемый для 3proxy вид), попросту игноря его. С небольшим набором хостов в файле проблем нет - всё работает как и задумано. 

Можете реализовать поддержку массивных хост-листов ? 

Ну и до кучи обработку хостов с делителем в виде новой строки, а не только запятой ?

**Comment by z3APA3A** [comment]
нет ограничения на количество хостов, есть ограничениена размер строки, разбей на несколько строк.

Но работать со списками в 148К я бы не рекомендовал, потому что поиск в них линеен, лучше задавать этот список через nsrecord, задав достаточный nscache, потому что для dns кеша используется хеш-таблица

**Comment by Baltazar500** [comment]
>нет ограничения на количество хостов, есть ограничениена размер строки, разбей на несколько строк.

На сколько символов ограничение ? Хосты перестали вычитываться примерно после 20500 символа. Перевод объёмного хост-листа с делением по новой строке в хост-лист разделённый запятыми и нарезанный кусками по 20500 символов будет той ещё задачкой

>лучше задавать этот список через nsrecord, задав достаточный nscache, потому что для dns кеша используется хеш-таблица

Я в конфигах 3proxy не дока, но разве записи nsrecord не делается с соотнесением ip и хоста ? У меня только список хостов, который нужно провести через вышесиоящий прокси. Или я чего-то не понимаю ?

**Comment by z3APA3A** [comment]
Задай для этих хостов IP адрес например 127.0.0.7, перенаправь трафик для 127.0.0.7 на родительский прокси (прокси должен быть http, socks5+ или connect+ чтобы на него ходить по имени), только nscache сделай достаточно большим

**Comment by Baltazar500** [comment]
@z3APA3A, получилось. Решение конечно ... нестандартное, как мне кажется, но работает. Сам бы до такого не додумался. Для тех, кто вдруг заглянет в тред, вот примерный конфиг :

```
internal 127.0.0.1
external 0.0.0.0
nscache 200000
nserver 127.0.0.1
log
logformat " %Y.%m.%d %H:%M:%S %N %p %C:%c %R:%r %O %I %h %T "
deny * * 127.0.0.1
include c:\PORTAB~1\3PROXY~1\blacklist.txt
allow * * 127.0.0.20
parent 1000 http 127.0.0.1 11228
allow *
proxy -p8080
socks -p8090
flush
```
blacklist.txt :
```
nsrecord adguard.com 127.0.0.20
nsrecord kinozal.tv 127.0.0.20
nsrecord rutracker.org 127.0.0.20
nsrecord static.rutracker.cc 127.0.0.20
```

p.s. nserver корректный - у меня юзается dnscrypt
