### ISSUE TITLE
не могу запустить 3proxy на одном хосте с parent socks5

### ISSUE THREAD

**Issue by keybo111** [3proxy/3proxy#1092]
конфиг такой:
auth iponly
log
allow *
parent 1000 socks5+ 127.0.0.1 1095
proxy -p3128 -a

пишет 502 ошибку и что не может подключиться к parent

**Comment by githubniko** [comment]
Столкнулся недавно с этой же ошибкой. Мне помогло следующее:
1) Замените строку parent на следующую **parent 1000 socks5+ 0.0.0.0 0**. Как я понял, такое написание отправляет данные на все локальные порты 3proxy.
2) Перед proxy -p3128 -a продублировать allow *

**Comment by keybo111** [comment]
> Столкнулся недавно с этой же ошибкой. Мне помогло следующее:
> 
> 1. Замените строку parent на следующую **parent 1000 socks5+ 0.0.0.0 0**. Как я понял, такое написание отправляет данные на все локальные порты 3proxy.
> 2. Перед proxy -p3128 -a продублировать allow *

Большое спасибо! Думаю порт можно и явно указать
