### ISSUE TITLE
How can I make it generate multiple WAN addresses?

### ISSUE THREAD

**Issue by hd00842** [3proxy/3proxy#1094]
I want it to be able to create a Wan address range for example from 10.0.0.1 to 10.0.0.10 to route it and create multiple proxies, how should I do that?

**Comment by z3APA3A** [comment]
proxy -p1001 -e10.0.0.1
proxy -p1002 -e10.0.0.2
...
proxy -p1010 -e10.0.0.10

**Comment by hd00842** [comment]
> proxy -p1001 -e10.0.0.1 proxy -p1002 -e10.0.0.2 ... proxy -p1010 -e10.0.0.10

Where can I fill in these parameters? Can you give me more detailed instructions?
