### ISSUE TITLE
transparent plugin

### ISSUE THREAD

**Issue by augin** [3proxy/3proxy#1097]
Здравствуйте. Работает ли плагин для прозрачного проксирования на FreeBSD? Вижу его для linux, но в пакете FreeBSD библиотека отсутствует. Очень хотелось бы настроить на OPNsense

**Comment by augin** [comment]
нашел ветку обсуждения, что у кого-то работает. Похоже надо собирать пакет самому.

**Comment by z3APA3A** [comment]
В Makefile.FreeBSD TransparentPlugin есть, чтобы он появился в стандартных пакетах просьбу лучше адресовать ментейнеру порта 3proxy в FreeBSD.
