### ISSUE TITLE
3proxy make htop very slow even there is no traffic 

### ISSUE THREAD

**Issue by cyrexer** [3proxy/3proxy#1099]
Hello @z3APA3A  .
i want to report that if i run like 10 or 20 3proxy sessions .
htop is slow and take like 20 seconds before it start to visualize the records .
it happen although 3proxy has no logs or real traffic .
im pretty sure if you find something that could solve this issue , U Gonna make 3proxy more powerful .

Do you think why does it slowing down htop ?
i tried almost all htop versions and all slow BTW with 3proxy .

Thanks

**Comment by z3APA3A** [comment]
This article explains 3proxy resource usage fort threads, descriptors, etc: https://3proxy.ru/highload.asp
As for htop, you better ask htop developers. You may want to use CPU affinity (man `taskset`) or set priority (man `nice`) to reserve resources for htop.
