### ISSUE TITLE
Прозрачный прокси для TLS трафика. Не работает Телеграм

### ISSUE THREAD

**Issue by githubniko** [3proxy/3proxy#1101]
Рабочий конфиг пересылки TLS трафика:
Весь трафик идет через ipv4, кроме сайтов, которые внесены в /conf/dpi.cfg, эти идут по ipv6

> plugin /libexec/TransparentPlugin.ld.so transparent_plugin
> auth iponly
> allow *
> proxy -64 -n -u -a -p4446 -i127.0.0.1 -e2a0c:d542:0:3::a -e217.39.35.181
> proxy -4 -n -u -a -p4445 -i127.0.0.1 -e217.39.35.181
> flush
> 
> allow * * $/conf/dpi.cfg
> parent 1000 connect+ 127.0.0.1 4446
> 
> allow *
> parent 1000 connect+ 127.0.0.1 4445
> 
> allow *
> tlspr -i10.0.0.1 -p8888 -c1
>
> Перенаправление трафика на 3proxy
> iptables -t nat -A PREROUTING -s 10.0.0.0/24 -p tcp -m multiport --dport 80,443 --jump DNAT --to 10.0.0.1:8888

Всё работает за исключением трафика из Телеги, который ходит без SNI по порту 80,443.

Лог: 

> 241123183600.104 8888 00303 - 10.0.0.2:50723 149.154.175.53:80 0 0 0 NONEv0.0 149.154.175.53 -
> 241123183600.113 8888 00303 - 10.0.0.2:50724 149.154.175.59:80 0 0 0 NONEv0.0 149.154.175.59 -
> 241123183600.114 8888 00303 - 10.0.0.2:50725 149.154.175.53:80 0 0 0 NONEv0.0 149.154.175.53 -

Предполагаю, что данный трафик надо перенаправлять в tcppm, но как ?

**Comment by githubniko** [comment]
Solved https://github.com/3proxy/3proxy/pull/1102

**Comment by z3APA3A** [comment]
-c1 означает требовать наличия TLS client hello. Убери его (allow non-TLS traffic) и все заработает.
