### ISSUE TITLE
Extracting Traffic Data from 3proxy Counter Logs Using PHP

### ISSUE THREAD

**Issue by TrustDesign** [3proxy/3proxy#1104]
Hello,
I have a 3proxy server where I enabled traffic counters for configurations. In the .cfg file, I use the following lines to activate the counter:

# Count traffic
counter "<logfile/>"
countin 1 M 200000 * * *
countout 1 M 200000 * * *

On the server, there is a config directory containing multiple .cfg files. Each configuration has its own folder named after the configuration, and within that folder, the corresponding counter .log file is stored.

I need to parse the counter log files using PHP to extract incoming and outgoing traffic. Despite testing multiple approaches, the results seem inaccurate due to issues with hex parsing.

Example Scenario
For a specific configuration, I installed the proxy in a browser and ran a speed test on [Fast.com](https://fast.com/). The test results showed:

    450 MB download
    300 MB upload

Here’s the hexdump of the corresponding log file:
```
hexdump -C /config/test1/test1.log | head
00000000  33 43 46 00 00 00 00 00  8c e5 44 67 00 00 00 00  |3CF.......Dg....|
00000010  fa d4 ca 11 00 00 00 00  3c a2 43 67 00 00 00 00  |........<.Cg....|
00000020  b2 e2 44 67 00 00 00 00                           |..Dg....|
00000028
```

Using my PHP script, the extracted traffic is as follows:
    Incoming: 284.68 MB (somewhat accurate)
    Outgoing: 1.61 GB (incorrect and identical across all configurations)

How should I correctly parse incoming and outgoing traffic from 3proxy counter logs using PHP?

Here is my current script:

[3proxy-traffic-counter.txt](https://github.com/user-attachments/files/17909026/3proxy-traffic-counter.txt)

Thanks!

**Comment by z3APA3A** [comment]
Each counter must have unique number, it specifies position (offset) in counter file to save the value. You save both counters into same place because you use a same number for 2 different counters.

**Comment by TrustDesign** [comment]
> @z3APA3A can you provide the file format, I am interesting in parsing counter files too.

What file format do you need?

**Comment by z3APA3A** [comment]
what exactly do you have in config and in logs? You counter file is updated on 
```
 % date -r 1732637220
вторник, 26 ноября 2024 г. 19:07:00 (MSK)
```
while counters are not changed after
```
 % date -r 1732636244
вторник, 26 ноября 2024 г. 18:50:44 (MSK)
```
it means counters are not set for traffic, if any.
