### ISSUE TITLE
3proxy + parent proxy + creds forwarding 

### ISSUE THREAD

**Issue by storm66-ag** [3proxy/3proxy#1107]
Hello guys! 

could you explain how I could to forward the all incoming requests http/socks to the parent proxy but with same creds ? 
is this something like a transparent proxy ? 
I use a radius auth. All works well, but now I have  a task to forward requests to the parent proxy with same creds like user used for primary proxy. Something like  Auth PASSTHRU  for parent proxy....

thanks!

**Comment by z3APA3A** [comment]
Use `*` to forward incoming authentication 

`parent 1000 <type> <host> <port> * *
`

**Comment by storm66-ag** [comment]
Очень похоже что :

parent 1000 http 1.2.3.4 65000 user1 * - не работает
parent 1000 http 1.2.3.4 65000 * password1 - работает
parent 1000 http 1.2.3.4 65000 * * - работает
