### ISSUE TITLE
Crash (divided by zero) in version 0.9.3

### ISSUE THREAD

**Issue by Shawn-Tong** [3proxy/3proxy#603]
I got the 'divided by zero' again after upgrade to version 0.9.3 from 0.9.1

Here is the error log from `/var/log/messages`

```
Feb 22 00:10:34 gate2 systemd: Started SYSV: 3proxy.
Feb 22 11:28:03 gate2 kernel: 3proxy[25986]: segfault at 6033956b ip 00007f9b67363bfd sp 00007ffe7562ad60 error 4 in libc-2.17.so[7f9b672e1000+1c3000]
Feb 22 11:32:02 gate2 kernel: traps: 3proxy[24963] trap divide error ip:407907 sp:7fa9232f6bf0 error:0 in 3proxy[400000+2a000]
```

Here is the result of the addr2line
```
addr2line -e 3proxy 407907
3proxy/src/auth.c:578 (discriminator 1)
```

Here is line 578 of auth.c
```
param->bandlims[i]->nexttime = msec + nsleeptime + ((nbytesin > 512)? ((nbytesin+32)/64)*(((64*8*1000000)/param->bandlims[i]->rate)) : ((nbytesin+1) * (8*1000000))/param->bandlims[i]->rate);
```

You fixed it in this issue: https://github.com/z3APA3A/3proxy/issues/546 (0.9.1)
But it happened again in version 0.9.3

PS: Today I got a new crashing message from the console.
```
*** Error in `/bin/3proxy': corrupted double-linked list (not small): 0x0000000000faf420 ***
```

**Comment by z3APA3A** [comment]
Check the latest version (with https://github.com/z3APA3A/3proxy/commit/681182b1e59142cc60d12c6112c057dc46414a17)

**Comment by Shawn-Tong** [comment]
I tested the latest version for a week and confirm it has been fixed.

PS: Some users said they got more proxy errors than before.
`ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)`

On the server end, I saw they are getting more `00155` errors than before.

BTW, your website https://3proxy.ru is down now. Would you consider moving the documents to Github?

```
500 - Internal server error.
There is a problem with the resource you are looking for, and it cannot be displayed.
```
