### ISSUE TITLE
feature suggestion: support for http byte range

### ISSUE THREAD

**Issue by mailinglists35** [3proxy/3proxy#640]
windows update is using http range feature, if available. it helps reduce amount of data downloaded. it's not required. it would be nice to have http range support in 3proxy.

i'm using it (thank you!) to redirect windows update traffic to it because i am also using outgoing firewall and since some time, the native windows firewall cannot allow windows update if you block everything for outgoing. but it works to connect to a proxy on localhost

https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization

thanks

**Comment by z3APA3A** [comment]
Can you descrbe the issue you experience with Range support? Range should work OK with proxy.
