### ISSUE TITLE
Feature request: logging in JSON format

### ISSUE THREAD

**Issue by tarampampam** [3proxy/3proxy#641]
Hi @z3APA3A! Thx for your project!

Could you please implement logging using `JSON` format? This will be very useful for running `3proxy` using docker and building metrics using log records. Right now for parsing log entries, I'll need to use 3rd party tools.

Config like (not tested):

```
logformat '{"date":"%d-%m-%Y %H:%M:%S", "u":"%U", "c":"%C:%c", "r":"%R:%r", "o":"%O", "i":"%I", "t":"%T"}'
```

Looks very unreliable and can be broken if the values will be contains something like `"` or `\n\r`.

**Comment by tarampampam** [comment]
Tested config:

```
logformat "-\""+_G{""time_unix"":%t, ""proxy"":{""type:"":""%N"", ""port"":%p}, ""error"":{""code"":""%E""}, ""auth"":{""user"":""%U""}, ""client"":{""ip"":""%C"", ""port"":%c}, ""server"":{""ip"":""%R"", ""port"":%r}, ""bytes"":{""sent"":%O, ""received"":%I}, ""request"":{""hostname"":""%n""}, ""message"":""%T""}"
```

**Comment by z3APA3A** [comment]
Yes, -+ filter is intended to be used here. In addition to listed characters, it eliminates special characters like CR/LF.
