### ISSUE TITLE
is there anyway to read counter file without web admin?

### ISSUE THREAD

**Issue by bashar-ait** [3proxy/3proxy#646]
Hey, 

I want to read the values in the counter without accessing the webadmin everytime.

Thanks

**Comment by z3APA3A** [comment]
You can peridoically get text repots with counters content, see "counter" command, reporttype/reportname arguments. reporname may contain same format specificators with "logformat" for date/time. If for some reason you still want to parse counters file, it has quite simple structure with 1*file header + n*records, where position of record matcher counter's number
```

struct counter_header {
	unsigned char sig[4];
	time_t updated;
};

struct counter_record {
	uint64_t traf64;
	time_t cleared;
	time_t updated;
};

```
