### ISSUE TITLE
Multiple instances issue

### ISSUE THREAD

**Issue by Al-Bsharat** [3proxy/3proxy#647]
Hello,
I'm trying to achieve rotating proxies on each port. To do that, I created a config profile with 5K proxies started from PORT 30000 and ending with 34999 and ran it on multiple 3proxy instances. Each instance has the same port, but with new external IP (-e), so I will get random IP for each request to that port.

my config file on each profile:

> daemon
> nserver 127.0.0.1
> nserver 208.67.222.222
> nserver 208.67.220.220
> nscache 65536
> setgid 65534
> setuid 65534
> timeouts 1 5 30 60 180 1800 15 60
> maxconn 120000
> #auth iponly
> #allow * 149.202.78.187
> proxy -6 -n -a -s0 -p30000 -i127.0.0.1 -e2b0d:5a11:216e:b742:5065:2cb7:f6a3:90b2
> proxy -6 -n -a -s0 -p30001 -i127.0.0.1 -e2b0d:5a11:4acb:b74f:539b:28ec:ea4b:9d37
> proxy -6 -n -a -s0 -p30002 -i127.0.0.1 -e2b0d:5a11:8ea4:2e7:7d25:b95:a7c5:d077
> proxy -6 -n -a -s0 -p30003 -i127.0.0.1 -e2b0d:5a11:9d44:4b6b:176e:34de:7b39:77df
> proxy -6 -n -a -s0 -p30004 -i127.0.0.1 -e2b0d:5a11:9f06:be68:8d90:7e07:a21b:290c
> proxy -6 -n -a -s0 -p30005 -i127.0.0.1 -e2b0d:5a11:b34c:8433:262e:fbc9:a49f:28e8
> proxy -6 -n -a -s0 -p30006 -i127.0.0.1 -e2b0d:5a11:3986:f206:c0ef:a5db:bdc0:27cc
> proxy -6 -n -a -s0 -p30007 -i127.0.0.1 -e2b0d:5a11:ec04:a6d0:9b19:37b6:e71e:7a47
> .
> .
> .
> proxy -6 -n -a -s0 -p34999 -i127.0.0.1 -e2b0d:5a11:6193:c5a7:7afb:8a73:88e2:dfc2

I tried to run 3proxy with multiple instances using.
`/root/3proxy/bin/3proxy [[PROFILE_PATH]]/3proxy.cfg`

[[PROFILE_PATH]] = The new profile path that has the configuration above.

But when I run 13 profiles, 3proxy will not work again, and the proxies will not respond. I get an instant fail message.

There is a better way to achieve what I want in a better way? (I want to have 1M IPs on my pool)
Note: I used 5K ports on the single profile to make 3proxy faster when running these ports. When I have many ports, it will be slow.

All the best

**Comment by z3APA3A** [comment]
What do you have in logs?

Start with the checking you have sufficientresources and limits https://3proxy.ru/highload.asp

**Comment by DULI2x** [comment]
> 

have you done it can you help me :D

**Comment by z3APA3A** [comment]
You can use random external address with `parent` of `extip` type

allow *
parent 1000 extip network/cidr 0
proxy -pPORT
