### ISSUE TITLE
Doesn't work with Tor

### ISSUE THREAD

**Issue by walidsa3d** [3proxy/3proxy#648]
3proxy doesn't use Tor as parent. Here's my config:
#nscache 65536
nserver 8.8.8.8
nserver 8.8.4.4

#config /conf/3proxy.cfg
#monitor /conf/3proxy.cfg

log /logs/3proxy-%y%m%d.log D
rotate 60
counter /count/3proxy.3cf

users $/conf/passwd

include /conf/counters
include /conf/bandlimiters
#fakeresolve
auth none
allow *
parent 1000 socks5+ 127.0.0.1 9050
proxy -a -n -p3111
socks
flush
#allow admin

#admin -p8080

**Comment by phantomcraft** [comment]
You should enable _fakeresolve_ and **auth** as _iponly_

```
#nscache 65536
nserver 8.8.8.8
nserver 8.8.4.4

#config /conf/3proxy.cfg
#monitor /conf/3proxy.cfg

log /logs/3proxy-%y%m%d.log D
rotate 60
counter /count/3proxy.3cf

users $/conf/passwd

include /conf/counters
include /conf/bandlimiters
fakeresolve
auth iponly
allow *
parent 1000 socks5+ 127.0.0.1 9050
proxy -a -n -p3111
socks
flush
#allow admin

#admin -p8080
```
