### ISSUE TITLE
3proxy with 1 port connection.

### ISSUE THREAD

**Issue by Al-Bsharat** [3proxy/3proxy#651]
Hello,
I noticed that when using 1 port with a windows server, it will stop after about 1 or 2 minutes (about 14-17K requests).
I used tcppm to redirect all connections to random 3proxy ports.

But the issue happens only when I use 1-4 ports.
When I use more ports, it will work fine.

Any solution for that?
I think 3proxy does not close the connection after receiving it or something like that. However, I'm not totally sure.

--------Update1-------
Yes, when I debug the problem, I see that windows keeping the TCP connection opened a lot of time. That's cuz the problem.
How to make 3proxy close it?
I tried 
`proxy -6 -n -a -s0 -ocTCP_NODELAY,TCP_QUICKACK -osTCP_NODELAY,TCP_QUICKACK -p$port -i$PUBLIC_IP -e$i`
But the issue still exist.
--------Update1-------

--------Update2------
I also tried TCP_QUICKACK, and it does not solve the issue I have.

`proxy -6 -n -a -s0 -ocTCP_NODELAY,TCP_QUICKACK -osTCP_NODELAY,TCP_QUICKACK -olTCP_NODELAY,TCP_QUICKACK -p$port -i$PUBLIC_IP -e$i`
--------Update2------

All the best

**Comment by z3APA3A** [comment]
What do you see in netstat?

**Comment by Al-Bsharat** [comment]
I got many TIME_WAIT in the windows machine where I'm using the proxies.
Screenshot: https://gyazo.com/2916d9bd861c1f5567f601e5f723af02

**Comment by z3APA3A** [comment]
TIME_WAIT means connection was successfully closed by both sides. If you see really high number (multiple thousands) of TIME_WAIT connections you are probably lack of ephemeral ports. You may want to decrease time_wait time and increase ephemeral port range, read something like this:
https://support.huawei.com/enterprise/en/doc/EDOC1100044388/6de15abb/how-do-i-reduce-the-time-for-canceling-tcp-connections-in-time_wait-state-on-windows for windows configuration and https://3proxy.ru/highload.asp for ephemeral ports tuning.

**Comment by Al-Bsharat** [comment]
I know a guy who has only 1 proxy port, and his proxies do not stop. There is anything to do without touch the windows machine? (Some Linux configuration to keep these ports opened and re-use them or something like that.)

**Comment by z3APA3A** [comment]
Read the article by the link above.
