### ISSUE TITLE
Act as simple HTTP 1.0/1.1 proxy that permit limited http client software connect https servers 

### ISSUE THREAD

**Issue by Dodutils** [3proxy/3proxy#652]
Hello,

Is there a way to make 3proxy act as a generic http to https proxy, for example let say I have some wget-like tool that cannot work with https servers at all, but it can pass http request thru some HTTP1.0/1.1 proxy, could 3proxy have some rewrite rule that transform any incoming HTTP 1.0/1.1 proxied request into HTTPS ?

Thank you for any answer.

**Comment by z3APA3A** [comment]
No, in current version 3proxy does not support proxying from http to https. If you have limited number of destination servers, you can use tools like stunnel.

**Comment by Antonius-S** [comment]
@Dodutils try [Node_TLS-Tunnel](https://github.com/Antonius-S/Node_TLS-Tunnel). It also could be used as parent proxy with 3proxy (to enable all 3p features like logs, URL/traffic control etc)
