### ISSUE TITLE
3proxy deny targetlist not work

### ISSUE THREAD

**Issue by widon1104** [3proxy/3proxy#654]
I read in man:
Since 0.6,	targetlist may also contain  host  names,  in-
       stead of	addresses. It's	possible to use	wildmask in the	begginning and
       in the the end of hostname, e.g.	*badsite.com or	 *badcontent*.	 Host-
       name  is	 only checked if hostname presents in request.

**I use 3proxy 0.8.13**
[root@localhost ~]# 3proxy -v
Usage: 3proxy [conffile]
 if conffile is missing, configuration is expected from stdin
3proxy tiny proxy server 3proxy-0.8.13 (190801174904)

the 3proxy conf file is:

nserver 223.5.5.5
nserver 180.76.76.76
nserver 114.114.114.114
nscache 65536
#timeouts 1 5 30 60 180 1800 15 60
log /mnt/log/log D
logformat "L{'时间':%Y-%m-%d %H:%M:%S ,'服务端ip':%N-%p,'请求ip':%Q:%q,'客户端ip': %C:%c,'目标ip':%R:%r,'发送到服务字节':%O,'接收字节':%I,'hops before target':%h,'service specific text': %T 'err':%E}"
#users :CL:
rotate 30
external 114.104.135.117
internal 0.0.0.0
auth iponly
allow * 171.212.112.124,171.212.115.92,8.210.133.108,171.223.227.235 *
`deny * * *baidu.com*`
proxy -a -p10110

➜  ~ curl -x 114.104.135.117:10110 -XGET www.baidu.com
![image](https://user-images.githubusercontent.com/12093211/123392567-c67d9e80-d5cf-11eb-8542-8dddbbc9234f.png)

I use tcpdump find www.baidu.com is in request.
![image](https://user-images.githubusercontent.com/12093211/123392645-e0b77c80-d5cf-11eb-9e19-95b630236fe0.png)

**Comment by z3APA3A** [comment]
What do you see in log files?

**Comment by btangbs** [comment]
In this case, using `*baidu.com` instead of `*baidu.com*` should work.

I found that if the hostname contains - (hyphen), it won't work. 

For example: 
`deny * * optimizationguide-pa.googleapis.com`

**Comment by z3APA3A** [comment]
It is fixed in both master and 0.9.14
https://github.com/3proxy/3proxy/commit/681182b1e59142cc60d12c6112c057dc46414a17
