### ISSUE TITLE
Turn on TSL 1,

### ISSUE THREAD

**Issue by billybons2006** [3proxy/3proxy#655]
Настраиваю прозрачный прокси:
```
setgid 112
setuid 106

auth none
log
#log /var/log/3proxy/3proxy.log D
#logformat "- +_G%t.%. %D %C TCP_MISS/200 %I %1-1T %2-2T %U DIRECT/%R application/unknown"
rotate 30
proxy

nserver 8.8.8.8
nserver 8.8.4.4
nscache 65536

plugin /etc/3proxy/plugins/TransparentPlugin.ld.so transparent_plugin
transparent
tcppm -iLOCAL_IP 31281 127.0.0.1 11111

plugin /etc/3proxy/plugins/SSLPlugin.ld.so ssl_plugin
ssl_certcache /etc/3proxy/plugins/ssl/
ssl_mitm

proxy -p31280
```

В директории ssl_certcache файлы 3proxy.key  3proxy.pem  server.key есть.

С помощью iptables заворачиваю трафик:
iptables -A PREROUTING -t nat -i enp0s3 -p tcp --dport 80 -j REDIRECT --to-port 31280
iptables -A PREROUTING -t nat -i enp0s3 -p tcp --dport 443 -j REDIRECT --to-port 31281

http ресурсы - ок, а при попытке https получаю в браузере:

```
Не удается отобразить эту страницу
Включите TLS 1.0, TLS 1.1 и TLS 1.2 в дополнительных параметрах и повторите попытку...
```

И в логах вижу:
210625132209.825 31281 00000 - ::ffff:192.168.2.177:49345 127.0.0.1:11111 0 0 0 127.0.0.1

Коннект есть, все вроде бы правильно. Может, какая-то хитрость с сертификатами в ssl_certcache?

**Comment by z3APA3A** [comment]
Так оно пока работать не будет в большинстве случаев, т.к. сломается SNI, сейчас схема генерации сертификата такая, что позволяет работать через прокси старым клиентам без поддержки SNI, но она не совместима с транспарентным редиректом и будет нормально работать только если прокси прописан в клиенте как прокси. Чтобы она работала с транспарентными редиректами надо допиливать.

**Comment by z3APA3A** [comment]
Недосмотрел, в текущей конфигурации по идее SSLPlugin вообще не задействован. Если убрать SSLPlugin какой будет результат?

**Comment by billybons2006** [comment]
> Недосмотрел, в текущей конфигурации по идее SSLPlugin вообще не задействован. Если убрать SSLPlugin какой будет результат?
Если прямо не указывать прокси в настройках браузера, то просто не открываются сайты https. Если указать прокси явно - сайты открываются, лог все видит.

**Comment by billybons2006** [comment]
> Так оно пока работать не будет в большинстве случаев, т.к. сломается SNI, сейчас схема генерации сертификата такая, что позволяет работать через прокси старым клиентам без поддержки SNI, но она не совместима с транспарентным редиректом и будет нормально работать только если прокси прописан в клиенте как прокси. Чтобы она работала с транспарентными редиректами надо допиливать.


Под допиливанием имеется в виду ожидание новых версий или допиливание моего конфига?

**Comment by z3APA3A** [comment]
Вот с таким конфигом (процесс надо полностью остановить и запустить заново) какой будет результат?
```

auth none
log
#log /var/log/3proxy/3proxy.log D
#logformat "- +_G%t.%. %D %C TCP_MISS/200 %I %1-1T %2-2T %U DIRECT/%R application/unknown"
rotate 30
proxy

nserver 8.8.8.8
nserver 8.8.4.4
nscache 65536

plugin /etc/3proxy/plugins/TransparentPlugin.ld.so transparent_plugin
transparent
tcppm -iLOCAL_IP 31281 127.0.0.1 11111
notransparent
proxy -p31280

```
и какая версия прокси используется?

**Comment by billybons2006** [comment]
> Вот с таким конфигом (процесс надо полностью остановить и запустить заново) какой будет результат?



3proxy-0.9.3, Debian 10

**Прокси прописан на клиенте явно:** все ок.
**Прокси не прописан  на клиенте:**
1) https:
`Не удается отобразить эту страницу
Включите TLS 1.0, TLS 1.1 и TLS 1.2 в дополнительных параметрах и повторите попытку...`
log:
210625145356.628 31281 00094 - ::ffff:192.168.2.177:49576 127.0.0.1:11111 0 0 0 127.0.0.1
210625145356.629 31281 00094 - ::ffff:192.168.2.177:49577 127.0.0.1:11111 0 0 0 127.0.0.1

2) http (например, изображение): все ок

**Comment by billybons2006** [comment]
Т.е. как и было, по сути.

**Comment by z3APA3A** [comment]
А как собирался? Пока похоже что transparent не работает
Попробуйте в logformat добавить %Q:%q
https://3proxy.ru/doc/howtor.html#LOGFORMAT

**Comment by z3APA3A** [comment]
и auth none уберите

**Comment by billybons2006** [comment]
Сборка:
`MAKEFILE = Makefile.Linux
LIBS = -lcrypto -lssl -ldl
PLUGINS = SSLPlugin StringsPlugin TrafficPlugin PCREPlugin TransparentPlugin
`

С добавкой к логу:
`- +_G1624636011.143  **87.250.250.90:443**   5934 192.168.2.177 TCP_MISS/200 4960 CONNECT an.yandex.ru:443 - DIRECT/87.250.250.90 application/unknown
- +_G1624636016.514  **78.140.185.169:80**   101 192.168.2.177 TCP_MISS/200 382 GET http://bozza.ru/ - DIRECT/78.140.185.169 application/unknown
- +_G1624636016.521  **127.0.0.1:11111**   0 ::ffff:192.168.2.177 TCP_MISS/200 0 127.0.0.1  - DIRECT/127.0.0.1 application/unknown
- +_G1624636016.536  **127.0.0.1:11111**   0 ::ffff:192.168.2.177 TCP_MISS/200 0 127.0.0.1  - DIRECT/127.0.0.1 application/unknown
- +_G1624636016.539  **127.0.0.1:11111**   1 ::ffff:192.168.2.177 TCP_MISS/200 0 127.0.0.1  - DIRECT/127.0.0.1 application/unknown`

где "127.0.0.1:11111" - там выключил явно прописанный прокси.

**Comment by z3APA3A** [comment]
::ffff:192.168.2.177:49577

здесь происходит что-то странное и запрос клиента приходит с IPv6 а не IPv4. А добавьте еще %i

**Comment by z3APA3A** [comment]
-iLOCAL_IP в tcppm это IPv4 или IPv6 адрес?

**Comment by billybons2006** [comment]
Пример из лога:
- +_G1624869731.680  127.0.0.1:11111:::ffff:192.168.2.170   0 ::ffff:192.168.2.177 TCP_MISS/200 0 127.0.0.1  - DIRECT/127.0.0.1 application/unknown

Я тоже не могу понять, что за намек на ipv6 эти ffff... На клиенте (Win 7) прописан только ipv4 (ipv6 галка снята вообще на инрефейсе, правда, этот клиент - виртуалка virtualbox), на проксе ipv6 запрещен в принципе.
ЗЫ: проверил также на Win10 (обычный комп) - такой же лог...

**Comment by z3APA3A** [comment]
-iLOCAL_IP - что конкретно в LOCAL_IP?

**Comment by z3APA3A** [comment]
В общем причина такая - по какой-то причине клиентский коннект через перенаправление приходит с IPv6 сокетом несмотря на IPv4 адрес и то, что слушающий сокет IPv4 (если там конечно действительно указан -i с IPv4 адресом). Похоже на системный баг, можно попробовать другое ядро. В принципе, 3proxy может с таким жить, но по типу сокета определяется тип адреса назначения и 3proxy ищет памминг транспарентного соединения в IPv6 таблице. Если баг не уйдет с обновлением ядра, можно попробовать добавить выбор версии IP по параметрам службы. В принципе, можешь попробовать tcppm запускать с -4, есть небольшой шанс что это поможет.

**Comment by billybons2006** [comment]
> В общем причина такая...

Большое спасибо за поддержку! Но время поджимало - поступил иначе - скомпилил Squid 4. Он пашет как надо.
