### ISSUE TITLE
Question: Is there any way to pass argument to 3proxy.exe in the command line?

### ISSUE THREAD

**Issue by Sia200** [3proxy/3proxy#656]
Hey everybody

I am developing a certain project which uses the 3proxy executable (for Windows).
I have a specific problem with the fact that the **argument 3proxy receives** is the configuration file.

Is there any way to pass the parameter to 3proxy from the command line?

something like
`3proxy.exe socks -u -l0.0.0.0 -p5050`

Thanks

**Comment by Sia200** [comment]
Well, I have compiled the code using TDM-GCC on windows and I saw in the output directory a standalone binary of `socks.exe` which gets the parameters from the command line which is great.
Is there official binaries (releases) of the socks.exe binary?

And if someone has another solution please let me know :)
Thanks

**Comment by z3APA3A** [comment]
Alternatively, you can generate temporary config file for every proxy.

Standalone executables are not provided currently within 3proxy distributions due to lot of false positives from antiviral software.
