### ISSUE TITLE
Проблема с авторизацией.

### ISSUE THREAD

**Issue by nahimov** [3proxy/3proxy#659]
Здравствуйте! Помогите разобраться с проблемой. 
Имеется на двух vps под управлением centos 7 прокси, на одном запрашивается авторизация, на втором нет, версия 3proxy 0.8.12

`nscache 65536
nserver 8.8.8.8
nserver 8.8.4.4
logformat "L%d-%m-%Y %H:%M:%S %z %N.%p %E %U %C:%c %R:%r %O %I %h %T"
log /var/log/3proxy/3proxy.log
rotate 12
archiver gz /usr/bin/gzip %F

daemon

auth strong
admin -p8080
users Admin:CL:******
users MrVasya:CL:*****

allow MrVasya,admin,ded

proxy -p3128 -n -a
socks -p1080

proxy -6 -n -a -p3129 -e2a01:6540:5568:22c::1

socks -6 -p1081 -i88.77.22.66 -e2a01:6540:5568:22c::1
`
Получается всегда открыт анонимный доступ на одном vps, при этом на втором всё отлично работает и требует авторизацию.

**Comment by z3APA3A** [comment]
А что в логах?

**Comment by nahimov** [comment]
В логах соединение удалось либо от пользователя которого создал, либо прочерк если в соединение прокси ничего не указано.

02-07-2021 15:40:11 +0300 PROXY.3128 00000 MrVasya 255.255.255.239:8777 216.58.215.110:443 3597 2949 0 CONNECT play.google.com:443 HTTP/1.1
02-07-2021 15:40:56 +0300 PROXY.3128 00000 MrVasya 255.255.255.239:32263 216.58.215.99:443 3309 2024 0 CONNECT www.google.ru:443 HTTP/1.1
02-07-2021 15:40:59 +0300 SOCK5.1080 00004 - 5.188.210.13:54195 5.188.210.13:80 0 0 0 CONNECT 5.188.210.13:80
02-07-2021 15:41:45 +0300 SOCK4.1080 00004 - 5.188.210.13:36702 5.188.210.13:80 0 0 0 CONNECT 5.188.210.13:80
02-07-2021 15:44:04 +0300 PROXY.3128 00004 - 5.188.210.13:45300 0.0.0.0:0 0 0 0 GET http://5.188.210.13/echo.php HTTP/1.1
02-07-2021 15:46:33 +0300 PROXY.3128 00005 - 5.188.62.248:33110 0.0.0.0:0 0 0 0 CONNECT api.ipify.org:443 HTTP/1.1
02-07-2021 15:47:10 +0300 SOCK5.1080 00004 - 5.188.210.13:54423 5.188.210.13:80 0 0 0 CONNECT 5.188.210.13:80
02-07-2021 15:47:23 +0300 SOCK4.1080 00004 - 5.188.210.13:38672 5.188.210.13:80 0 0 0 CONNECT 5.188.210.13:80
02-07-2021 15:48:49 +0300 PROXY.3128 00000 MrVasya 255.255.255.239:1047 52.114.74.45:443 54907 12340 0 CONNECT browser.events.data.msn.com:443 HTTP/1.1

**Comment by z3APA3A** [comment]
По этому логу видно что ни одного запроса без авторизации не прошло. Почему ты считаешь что кто-то может подключиться без авторизации через прокси?

**Comment by nahimov** [comment]
Вот этот неизвестный товарищ разве не попал куда хотел ? 02-07-2021 15:47:10 +0300 SOCK5.1080 00004 - 5.188.210.13:54423 5.188.210.13:80 0 0 0 CONNECT 5.188.210.13:80

Также я убирал в настройках браузера свою учётку и он спокойно открывал сайты, даже если неправильный пароль для учётки своей ставил всё равно. А второй прокси когда переключал сразу запрос авторизации выдавал если ему что-то не нравилось....

**Comment by z3APA3A** [comment]
Нет, не попал, видно что код 00004 (запрос авторизации) и нулевой трафик. Если ты можешь куда-то попасть, то либо с авторизацией, либо не через этот прокси

**Comment by nahimov** [comment]
5.188.210.13 - это какой-то сервер со скриптом который подключаясь узнаёт какой айпи у него через этот порт высвечивается.

**Comment by nahimov** [comment]
Видимо что-то где-то закешировалось, попробовал с другой машины, там всё нормально, форма авторизации выскочила. Спасибо за помощь!
