### ISSUE TITLE
nbname не работает

### ISSUE THREAD

**Issue by DimaXYZ** [3proxy/3proxy#662]
Windows. 
При задании в конфиге команды auth nbname сервер не стартует с ошибкой` 'auth' failed with code 1` что делать? iponly работает, но мне необходим доступ давать по имени компьютеров, поскольку ip по dhcp и иногда могут меняться. Сейчас доступ дается так:

auth iponly
allow * ip_пользователя * *

Может конфиг не правильно пишу. Пробую 
auth nbname
allow * имя_компьютера * *

**Comment by z3APA3A** [comment]
nbname не поддерживается в текущих версиях 3proxy т.к. не работает в актуальных версиях Windows, и он работал с именами пользователей, а не именами компьютеров. Скорей всего, тебе нужен не nbname а dnsname.
