### ISSUE TITLE
502 Bad Gateway Host Not Found or connection failed

### ISSUE THREAD

**Issue by thanhvodad** [3proxy/3proxy#666]
I just set up the Proxy, but when I run it, I get the problem "502 Bad Gateway Host Not Found or connection failed"
Is there any way to fix this situation :( Please help me
IPV4=>IPV6

---3proxy.cfg---
auth strong
allow WW9wD
proxy -6 -n -a -p10001 -i193.70.89.207 -e2001:41d0:404:300:09d4:6d24:eb26:dd6d
flush

---Logs ---
1627468975.529 PROXY.10001 00013 WW9wD 27.74.75.67:57045 2a00:1450:400f:801::2004:443 0 0 0 CONNECT_www.google.com:443_HTTP/1.1
1627468976.078 PROXY.10001 00013 WW9wD 27.74.75.67:57046 2a00:1450:400f:801::2004:443 0 0 0 CONNECT_www.google.com:443_HTTP/1.1
1627468978.118 PROXY.10001 00013 WW9wD 27.74.75.67:57047 2606:4700::6812:79c:80 0 0 0 GET_http://icanhazip.com/_HTTP/1.1
1627468980.406 PROXY.10001 00013 WW9wD 27.74.75.67:57049 2606:4700:3031::ac43:b3c1:443 0 0 0 CONNECT_youtube.xprivate.cc:443_HTTP/1.1
1627468980.787 PROXY.10001 00013 WW9wD 27.74.75.67:57051 2a00:1450:4001:808::200e:443 0 0 0 CONNECT_consent.youtube.com:443_HTTP/1.1
1627468981.292 PROXY.10001 00013 WW9wD 27.74.75.67:57055 2a00:1450:4001:80f::2005:443 0 0 0 CONNECT_gmail.com:443_HTTP/1.1

**Comment by z3APA3A** [comment]
00013 means connect() failed, see https://3proxy.ru/howtoe.asp#ERRORS
Check manually you can connect to IPv6 addresses from proxy host from address 2001:41d0:404:300:09d4:6d24:eb26:dd6d, e.g. 
nc -s 2001:41d0:404:300:09d4:6d24:eb26:dd6d 2a00:1450:4001:80f::2005 443

**Comment by thanhvodad** [comment]
> 00013 means connect() failed, see https://3proxy.ru/howtoe.asp#ERRORS
> Check manually you can connect to IPv6 addresses from proxy host from address 2001:41d0:404:300:09d4:6d24:eb26:dd6d, e.g.
> nc -s 2001:41d0:404:300:09d4:6d24:eb26:dd6d 2a00:1450:4001:80f::2005 443

[root@vps-2f4d8945 ~]# nc -s 2001:41d0:404:300:09d4:6d24:eb26:dd6d 2a00:1450:4001:80f::2005 443
Ncat: Connection timed out.

What are these errors usually?

**Comment by z3APA3A** [comment]
Probably, you have routing issues, and traffic to/from 2001:41d0:404:300:09d4:6d24:eb26:dd6d is not routed in the way you expect.

**Comment by thanhvodad** [comment]
> Probably, you have routing issues, and traffic to/from 2001:41d0:404:300:09d4:6d24:eb26:dd6d is not routed in the way you expect.

Is there an article to fix this problem, I am using Centos8
