### ISSUE TITLE
Not all logs cleared after compress

### ISSUE THREAD

**Issue by vfiuchcikicshuusrch** [3proxy/3proxy#667]
![3p](https://user-images.githubusercontent.com/46344039/127739404-212336d2-8d2c-41f1-80e8-58647dc21c71.png)

```
log /etc/3proxy/logs/%Y-%m-%d D
archiver gz /bin/gzip %F 2>/dev/null
rotate 21
```
Strange problem...
Log already gzipped but orig file still in folder.

This is bug?

**Comment by z3APA3A** [comment]
gzip (not 3proxy) removes original file. Probably, gzip failed for some reason to create an archive and/or remove an original file, check disk/memory/ulimits/file permissions

**Comment by z3APA3A** [comment]
Log was rotated on Jul 19 00:00 while gz file was crated Jul 18 16:03, same on Jul 31. Have you experimented with logging or created gzips with something else?
