### ISSUE TITLE
fakeresolve и flush

### ISSUE THREAD

**Issue by r4sas** [3proxy/3proxy#668]
Вопрос аналогичный #653, но с изюминкой.
Можно ли реализовать сброс параметра для разных проксей в одном конфиге посредством flush?

О чем речь:
Имеется сервер на котором предустановлены Tor, I2P, [Yggdrasil](https://github.com/yggdrasil-network/yggdrasil-go).
Понимая что fakeresolve нужен для резолвинга на стороне вышестоящего прокси, прописываю его в блоке для прокси, направляющего траффик по нужным сетям:

```
flush
auth iponly
fakeresolve

# yggdrasil network
allow * * 200::/7
allow * * *.ygg
parent 1000 socks5+ 127.0.0.1 1085

# i2p sites
allow * * *.i2p
parent 1000 http 127.0.0.1 4444

# onion sites
allow * * *.onion
parent 1000 socks5+ 127.0.0.1 9050

# forward clearnet to tor
allow *
parent 1000 socks5+ 127.0.0.1 9050

socks -olSO_REUSEADDR,SO_REUSEPORT -ocTCP_TIMESTAMPS,TCP_NODELAY -osTCP_NODELAY -46 -p1080
```

Только вот загвозка: следующему прокси (который будет у нас чисто для Yggdrasil на порту 1085) не требуется fakeresolve.
```
# Yggdrasil network handler
flush
auth iponly
allow *
socks -olSO_REUSEADDR,SO_REUSEPORT -ocTCP_TIMESTAMPS,TCP_NODELAY -osTCP_NODELAY -6 -p1085
```
Но вот flush не сбрасывает параметр fakeresolve, поэтому локальный резолвинг для *.ygg не проходит, и все домены возвращают `::2`.
Приходится запускать из-за этого две копии 3proxy.

Есть ли вариант решения проблемы в пределах одной копии программы?

**Comment by z3APA3A** [comment]
Настройки DNS и DNS-кеш являются общими для всех сервисов, поэтому запускать две копии это правильное решение. В общем-то, нет причине этого НЕ делать, более мелкий конфиг обычно является более эффективным.
