### ISSUE TITLE
Can not configure external Ip

### ISSUE THREAD

**Issue by 123bistami** [3proxy/3proxy#669]
Hello,
I want to use multiple ip addresses trough one instance public ip address.
On the config file i set my public instance ip as internal and as external ip i set a non existing ip connection not possible. I can only connect if i set the specified port. And than connect with my public instance ip and port. Did i understand 3proxy correctly i will have multiple outgoing addresses with one instance ip, i try to specify multiple ports with same internal ip and different external ip nothing works.

Pls help my config file

`# Specify valid name servers. You can locate them on your VPS in /et$
#
nserver 8.8.8.8
nserver 8.8.4.4
nserver 1.1.1.1
nserver 1.0.0.1
#Leave default cache size for DNS requests:
#
nscache 65536
#Leave default timeout as well:
#
timeouts 1 5 30 60 180 1800 15 60
#If your server has several IP-addresses, you need to provide an ext$
#Alternatively, you may ignore this line
#external YOURSERVERIP
#If you ignore this line, proxy will listen all the server's IP-addr$
#internal YOURSERVERIP
#Create users proxyuser1 and proxyuser2 and specify a password
#
users $/etc/3proxy/.proxyauth
#Specify daemon as a start mode
#
auth none 

## NOT WORKING ##
proxy -n -p9999 -a -i123.123.123.101 -e124.124.124.101
## not working ##
internal 123.123.123.101 
external 125.125.125.125
proxy -n -p9999
## not working ##

daemon
#Logs path and log format. Creation date will be added to a log name
#log /dev/null
#
log /var/log/3proxy/3proxy.log
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
#Compress logs using gzip
#
archiver gz /usr/bin/gzip %F `

**Comment by z3APA3A** [comment]
daemon and log must be at the beginning of file. Set correct logging and check the log file.

**Comment by 123bistami** [comment]
Thanks for responding,

my 3proxy.log content is

![B4C18BE9-1D85-4255-AEB4-5FEC1094E731](https://user-images.githubusercontent.com/28767886/130249210-aa2bf27c-8dba-4ad8-82c8-db19ff3abcfa.jpeg)

`

nserver 8.8.8.8
nserver 8.8.4.4
nserver 1.1.1.1
nserver 1.0.0.1
#Leave default cache size for DNS requests:
#
nscache 65536
#Leave default timeout as well:
#
timeouts 1 5 30 60 180 1800 15 60
#If your server has several IP-addresses, you need to provide an external one
#Alternatively, you may ignore this line
#external YOURSERVERIP
#If you ignore this line, proxy will listen all the server's IP-addresses
#internal YOURSERVERIP
#Create users proxyuser1 and proxyuser2 and specify a password
#
users $/etc/3proxy/.proxyauth
#Specify daemon as a start mode
#
daemon
#Logs path and log format. Creation date will be added to a log name
#log /dev/null
#
log /var/log/3proxy/3proxy.log
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
#Compress logs using gzip
#
archiver gz /usr/bin/gzip %F
#store the logs for 30 days
rotate 1

#added authentication caching to make life easier
authcache user 60

# Start new ACLs
#enable strong authorization. To disable authentication, simply change to 'auth none'
#auth strong cache
auth none

proxy -n -p3128 -a -i152.xx.xxx.166 -e152.70.165.155
#restrict access for ports via http(s)-proxy and deny access to local interfaces
deny * * 127.0.0.0/8,192.168.1.1
allow * * * 80-88,8080-8088 HTTP
allow * * * 443,8443 HTTPS
# allow SOCKS connection to all ports
# allow * * * 1-65535 CONNECT
#allow * * * 1-65535 HTTPS

#HTTP Proxy
# Use default ACLs, don't need to flush
proxy -n -p9999 -a

#SOCKS
flush
auth strong cache
socks -p8088

#internal 0.0.0.0
#external 155.45.160.120
#proxy -a -p8080 -i 0.0.0.0 -e 152.175.50.167

#Enable admin web-ui on specified port, only allow connection from loopback interface (127.0/8) & intranet's admin user (10/8)
flush
auth iponly strong cache
allow * * 127.0.0.0/8
allow admin * 10.0.0.0/8
admin -p2525

`

**Comment by 123bistami** [comment]
Thanks for responding,

my 3proxy.log content is

![5F7F99D4-31AC-4858-B997-2E209C9853F1](https://user-images.githubusercontent.com/28767886/130249952-74eca5b2-cbec-4e74-b9a9-32b30870c1d8.jpeg)


nserver 8.8.8.8
nserver 8.8.4.4
nserver 1.1.1.1
nserver 1.0.0.1
#Leave default cache size for DNS requests:
#
nscache 65536
#Leave default timeout as well:
#
timeouts 1 5 30 60 180 1800 15 60
#If your server has several IP-addresses, you need to provide an external one
#Alternatively, you may ignore this line
#external YOURSERVERIP
#If you ignore this line, proxy will listen all the server's IP-addresses
#internal YOURSERVERIP
#Create users proxyuser1 and proxyuser2 and specify a password
#
users $/etc/3proxy/.proxyauth
#Specify daemon as a start mode
#
daemon
#Logs path and log format. Creation date will be added to a log name
#log /dev/null
#
log /var/log/3proxy/3proxy.log
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
#Compress logs using gzip
#
archiver gz /usr/bin/gzip %F
#store the logs for 30 days
rotate 1

#added authentication caching to make life easier
authcache user 60

# Start new ACLs
#enable strong authorization. To disable authentication, simply change to 'auth none'
#auth strong cache
auth none

proxy -n -p3128 -a -i152.xx.xxx.166 -e152.70.165.155
#restrict access for ports via http(s)-proxy and deny access to local interfaces
deny * * 127.0.0.0/8,192.168.1.1
allow * * * 80-88,8080-8088 HTTP
allow * * * 443,8443 HTTPS
# allow SOCKS connection to all ports
# allow * * * 1-65535 CONNECT
#allow * * * 1-65535 HTTPS

#HTTP Proxy
# Use default ACLs, don't need to flush
proxy -n -p9999 -a

#SOCKS
flush
auth strong cache
socks -p8088

#internal 0.0.0.0
#external 155.45.160.120
#proxy -a -p8080 -i 0.0.0.0 -e 152.175.50.167

#Enable admin web-ui on specified port, only allow connection from loopback interface (127.0/8) & intranet's admin user (10/8)
flush
auth iponly strong cache
allow * * 127.0.0.0/8
allow admin * 10.0.0.0/8
admin -p2525

**Comment by z3APA3A** [comment]
Your internal address is invalid, check it with ifconfig.
