### ISSUE TITLE
3proxy as relay through NAT/PAT?

### ISSUE THREAD

**Issue by Born-to-be-Brad** [3proxy/3proxy#672]
When traveling abroad we occasionally experience difficulties with US web sites being paranoid about Asian IP addresses.  Some are not reachable at all.  Some appear to work but reject known working login credentials.  Rather than depend entirely on VPNs, I'm considering setting up a 3proxy proxy service as an HTTP/HTTPS/SOCKS5 relay in my US home.

The lightweight Win10 client that 3proxy would be running on would be behind a consumer router (Asus RT-AC86U with OEM firmware) with PAT rules directing traffic from outside into the Win10 box.  Traffic would just go right back out the same network interface and out through the router.

Do-able?  What would the interface lines look like in the .cfg file?  Anything unusual needed in the lines for proxy and socks?

Or am I over-thinking this and should just RDP/VNC into the box from wherever I am?

I did some searching here and with Google but didn't really find anyone attempting this sort of scenario.

Thanks for any guidance.  Big kudos to 3APA3A, Vladimir et al!

**Comment by z3APA3A** [comment]
Yes, it's quite common proxy usage scenario. For this case you need to map router port to proxy port, internal and external addresses both point to the same interface IP.

P.S. actually, you can install 3proxy onto the router itself, 3proxy binaries for arm/linux are available, but it may be quite tricky.
