### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by lollita** [3proxy/3proxy#675]
Window Defender reveal a virus in 3Proxy: "Wacatac.a!ml".

**Comment by z3APA3A** [comment]
You can report it to antivirus developers as false positive. 3proxy code is often reused by malware developers and it leads to false detection of 3proxy itself. It happens too often, so I gave up with it, 3proxy site has a warning on false detections.

**Comment by steveepreston** [comment]
Windows Defender Alert:
```
Trojan:Win32/Kepavll!rfn

Alert level: Severe
Status: Active
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.
```
