### ISSUE TITLE
Не работают запреты на протоколе SOCKS

### ISSUE THREAD

**Issue by antodemontoolsy** [3proxy/3proxy#677]
На протоколе http все нормально, запреты работают
############95.84.154.72:54098:test:test
auth strong
users test:CL:test
deny test* $"C:\3proxy\bin64\platezki.list"
allow test
proxy-n -a -p54098 -i192.168.88.1 -e192.168.80.100
flush
Меняю только протокол на порту, перестают работать, так и должно быть? или..? как быть
############95.84.154.72:54099:2ujwom:2ujwom
auth strong
users test:CL:test
deny test* $"C:\3proxy\bin64\platezki.list"
allow test
socks -n -a -p54099 -i192.168.88.1 -e192.168.80.100
flush

**Comment by z3APA3A** [comment]
Что должно работать и что в логах?

**Comment by antodemontoolsy** [comment]
Запреты не работают на протоколе socks. На протоколе http работают. У меня есть лист запретов platezki.list с сайтами куда нельзя заходить

**Comment by antodemontoolsy** [comment]
https://dropmefiles.com/Besgh
Вот логи
я не ориентируюсь в них, не знаю что Вам от туда прислать.

**Comment by antodemontoolsy** [comment]
> 
> 
> Запреты не работают на протоколе socks. На протоколе http работают. У меня есть лист запретов platezki.list с сайтами куда нельзя заходить

Есть допустим порт, 54099. Если у него протокол http - лист запретов platezki.list работает, и я не могу перейти по сайтам которые указаны в листе. Когда я меняю протокол - socks, лист запретов перестает работать

**Comment by antodemontoolsy** [comment]
> 
> 
> Что должно работать и что в логах?

если будете смотреть логи то там порты 54098 и 54099, я менял socks http и увидел что не работает лист на соксе

**Comment by z3APA3A** [comment]
Что именно у тебя в platezki.list и в логах (достаточно 1-2 строчек которые исллюстрируют поведение отличное от ожидаемое)

**Comment by antodemontoolsy** [comment]
*www.qiwi.com*,*www.sberbank.ru*,*kassa.yandex.ru*,*walletone*,*rbk.money*,*paypal.com*,*paypal*,*wallet.rapida.ru*,*perfect-money*,*paypal*,*z-payment*,*skrill.com*,*epayments.com*,*192.168.1.1*,*192.168.2.1*,*192.168.3.1*,*192.168.4.1*,*192.168.5.1*,*192.168.6.1*

**Comment by antodemontoolsy** [comment]
Что в логах не вижу вообще ни того ни другого.

**Comment by z3APA3A** [comment]
Скорей всего клиент запрашивает ресурс по адресу, а не по имени. Ты можешь запретить запрашивать ресурсы по IP адресу, например

deny * * *1,*2,*3,*4,*5,*6,*7,*8,*9,*0
(можно запретить регуляркой с исползованием PCREPlugin)

 или ограничить доступ не по имени, а по IP адресам.

**Comment by antodemontoolsy** [comment]
> 
> 
> Скорей всего клиент запрашивает ресурс по адресу, а не по имени. Ты можешь запретить запрашивать ресурсы по IP адресу, например
> 
> deny * * *1,*2,*3,*4,*5,*6,*7,*8,*9,*0
> (можно запретить регуляркой с исползованием PCREPlugin)
> 
> или ограничить доступ не по имени, а по IP адресам.

Нет не скорее всего. точно нет. Я пишу что я зашел на порт с протоколом http с platezki.list. сайты не открываются. Зашел на сервер, сменил протокол у этого порта, перезагружаю страницу с этой прокси и вуаля, сайты открываются и запреты не работают.

**Comment by z3APA3A** [comment]
Если ты не видишь в логах прокси запросов по именам - значит их нет. Или запросы идут мимо прокси, или запросы идут по IP адресам, смотри в логах есть ли там запросы вообще.

**Comment by antodemontoolsy** [comment]
https://dropmefiles.com/AYDsV - я Вам вот записал видео. ознакомьтесь пожалуйста и проведите у себя тест такой. у Вас баг. я меняю протокол только. когда стоит http - лист запретов работает, когда стоит socks запреты не работают

**Comment by antodemontoolsy** [comment]
как запросы пойдут мимо прокси? стоит в браузере дополнение, я захожу проверить айпи, там IP мобильного оператора. Значит я подключился к прокси

**Comment by z3APA3A** [comment]
Проверь что в твоем дополнении стоит галочка типа "разрешать имена через прокси", без него запросы пойдут по IP адресам, а не по именам.

**Comment by antodemontoolsy** [comment]
> 
> 
> Проверь что в твоем дополнении стоит галочка типа "разрешать имена через прокси", без него запросы пойдут по IP адресам, а не по именам.

![изображение](https://user-images.githubusercontent.com/90263202/132485779-7806c7d2-0a0d-4fb2-9c3a-4766cf05eb8b.png) там нету такого

**Comment by z3APA3A** [comment]
Да? А это по-твоему что? 
![image](https://user-images.githubusercontent.com/7222768/132487114-6f3475d8-424c-4663-8d2c-12e14b3221b5.png)

**Comment by antodemontoolsy** [comment]
Спасибо, теперь я все понял
тут я не понял : 
![изображение](https://user-images.githubusercontent.com/90263202/132487604-ef9f0b87-0b16-44d2-b20a-2ad40c0207d9.png)
что это отправка запросов через адреса.

**Comment by antodemontoolsy** [comment]
только мне не понятно вот есть IP  QIWI сайта
![изображение](https://user-images.githubusercontent.com/90263202/132489206-66498159-0820-4f26-b005-3270df3dc39c.png)
![изображение](https://user-images.githubusercontent.com/90263202/132489244-4c5289cc-df4a-486a-bf1a-f629bb2b3e37.png)
вот так на сайт продолжает заходить. 
В мануале я не нашел как сделать запрет по IP адресам
и вопрос можно ли совместить запрет по именам и адресам?

**Comment by z3APA3A** [comment]
Посмотри синтаксис команды deny, у тебя она записана неправильно (не хватает пробелов и есть лишняя звездочка)
