### ISSUE TITLE
Кеширование адреса parent proxy

### ISSUE THREAD

**Issue by REDHAT3** [3proxy/3proxy#679]
Кешируется ли адрес parent proxy? Если да, то на какое время?
<img width="365" alt="Снимок экрана 2021-09-17 в 13 35 27" src="https://user-images.githubusercontent.com/22527108/133769244-e934400c-ed79-4617-ad37-cf7621fd58c0.png">

**Comment by z3APA3A** [comment]
В текущих версиях - при использовании nscache кешируется в соответствии с TTL записи, при отсутствии nscache используется стандартное системное разрешение имен.
