### ISSUE TITLE
[bug] Отключается запись логов в ODBC

### ISSUE THREAD

**Issue by REDHAT3** [3proxy/3proxy#680]
После обновления файла через monitor перестает писать логи через ODBC

Описываю свои действия:
1. service 3proxy start
2. Пишет в логи всё нормально
3. touch ../3proxy.ver
4. Сразу же перестает писать в логи
5. Меняю в конфиге запись логов в файл
6. Работает всё отлично
7. Меняю обратно на odbc
8. Продолжает работать нормально
9. Как только пишу touch ../3proxy.ver (перезапуск с тем же кончиком)
10. Перестает писать в odbc, хотя конфиг не менялся

**Comment by z3APA3A** [comment]
Наиболее вероятные причины, что в конфиге есть chroot или setuid и при этом конфигурационные файлы и/или динамические библиотеки odbc недоступны внутри chroot или пользователю, с которым работает 3proxy.

**Comment by REDHAT3** [comment]
> Наиболее вероятные причины, что в конфиге есть chroot или setuid и при этом конфигурационные файлы и/или динамические библиотеки odbc недоступны внутри chroot или пользователю, с которым работает 3proxy. Надо или пробросить библиотеки и файлы внутрь chroot или убрать chroot + использовать эккаунт у которого есть доступ.

Нету chroot и setuid, проблема в том что odbc работает до тех пор пока не дёрну через monitor обновление конфета

**Comment by REDHAT3** [comment]
@z3APA3A могу скинуть короткий видос на почту, либо в тг в чем заключается моя проблема, можно такое сделать?

**Comment by z3APA3A** [comment]
Для того чтобы проблему диагностировать нужен не видосик, а нормальное полное описание условий - конфиги, лимиты, пути и разрешения файлов, содержимое логов

**Comment by REDHAT3** [comment]
@z3APA3A Конфиг
```
nscache 65536
nserver 1.1.1.1
nserver 8.8.8.8

log &gates
logformat "Linsert into logs (gate_id, username, protocol, port, err, client_ip, client_port, server_ip, server_port, requested_ip, requested_port, in_bytes, out_bytes, request_host_name, specific_text, created_at) values(1, '%U', '%N', '%p', '%E', '%C', %c, '%R', %r, '%Q', %q, %I, %O, '%n', '%T', '%Y-%m-%d %H:%M:%S %z')"

config "/etc/3proxy/3proxy.cfg"

auth iponly strong
users user1:CL:pwd1

maxconn 250
allow user1
parent 1000 http example.com 20006
proxy -n -a -p10015 -i0.0.0.0
flush

monitor "/etc/3proxy/3proxy.ver"
system "rm /etc/3proxy/3proxy.lck"
```

Запускаю - всё работает, пишет логи в бд(постгрес) с помощью odbc

После чего наступает момент когда нужно заменить конфиг, делаю я это по мануалу в разделе highload
1. touch /etc/3proxy/3proxy.lck
2. меняю конфиг на вот такой(добавляю одну проксю)
```
nscache 65536
nserver 1.1.1.1
nserver 8.8.8.8

log &gates
logformat "Linsert into logs (gate_id, username, protocol, port, err, client_ip, client_port, server_ip, server_port, requested_ip, requested_port, in_bytes, out_bytes, request_host_name, specific_text, created_at) values(1, '%U', '%N', '%p', '%E', '%C', %c, '%R', %r, '%Q', %q, %I, %O, '%n', '%T', '%Y-%m-%d %H:%M:%S %z')"

config "/etc/3proxy/3proxy.cfg"

auth iponly strong
users user1:CL:pwd1

maxconn 250
allow user1
parent 1000 http example.com 20006
proxy -n -a -p10015 -i0.0.0.0
flush

maxconn 250
allow user1
parent 1000 http example.com 20007
proxy -n -a -p10016 -i0.0.0.0
flush

monitor "/etc/3proxy/3proxy.ver"
system "rm /etc/3proxy/3proxy.lck"
``` 
3. меняю содержимое файла /etc/3proxy/3proxy.ver и запихиваю туда sha256 хеш текущего конфига
4. Всё. После этих действий запись в бд прекращаеться, сам доступ к odbc работает(проверял через isql)

P.S. Чтобы возобновить запись в odbc нужно сначала поставить запись в файл ,а потом вернуть опять запись в Odbc и логирование восстановиться

**Comment by REDHAT3** [comment]
Похоже что заработало, в продет еще не тестил, но на новом развернутом серваке проблема пропала, так что думаю что можно закрывать, спасибо за помощь)
