### ISSUE TITLE
[QUESTION] Does multi-instance can increase performances ?

### ISSUE THREAD

**Issue by APX403** [3proxy/3proxy#682]
Hello,

Do you think that running one instance of 3proxy per proxy can increase performances ?

For example instead of having 30 proxy on one 3proxy instance, having 30 instances of 3proxy running one proxy each.

Thanks for your help !

**Comment by phantomcraft** [comment]
I don't know if 3proxy is multithreaded, if no, yes, it will increase the performance if you have a processor which has more than one core.

**Comment by z3APA3A** [comment]
3proxy creates thread for each connections, so generally there is no increase in performance while processing connections. However, you may want to create multiple instances to have separate configs, to avoid realoading all instances of 3proxy in the case configuration of 1 instance is changes. Reloading configuration takes a lot of resources and reloading single instances is more resource-effective.
Also, you may be interested in https://3proxy.ru/highload.asp
