### ISSUE TITLE
How to set up IP or USERS . authentication ?

### ISSUE THREAD

**Issue by thanhvodad** [3proxy/3proxy#683]
I'm looking for a command to configure two-factor authentication,
IPONLY STRONG, although it has provided the correct IP image without authentication, it still displays a dialog box asking for user input,
How do I configure
If IP allows, then no need to enter users pass
If the IP does not allow it, the user password is required
Please help me
`
users user_123:CL:123123
authcache ip 999999
auth iponly strong cache
allow * ip.xxx
allow user_123 *
`

**Comment by z3APA3A** [comment]
Check the log file and compare request parameters you have in log with ACL configured

**Comment by thanhvodad** [comment]
I need an example file, can you help me

**Comment by z3APA3A** [comment]
```
users ...
auth iponly strong
allow * ip1,ip2
allow user1,user2
deny *
proxy
```

**Comment by SalimF** [comment]
> allow * ip1,ip2

Does IP number support subnet like /16 etc ?
