### ISSUE TITLE
error code 00412

### ISSUE THREAD

**Issue by hunterhe23** [3proxy/3proxy#691]
for the same socks proxy server(10.50.3.4), some client requests succeed and some client requests fail with error code 00412.

succeed log:
11/Oct/2021:08:44:46 +0800 SOCK5 1080 00000 10.10.2.10 10.50.3.4 180.101.49.11 80 CONNECT www.baidu.com:80 0 0 2300

fail log(target IP/port and url are ZERO):
11/Oct/2021:08:44:46 +0800 SOCK5 1080 00412 10.10.1.10 10.50.3.4 0.0.0.0 0 UNKNOWN 0.0.0.0:0 0 0 1

my 3proxy config:
logformat "L%d%o%Y:%H:%M:%S %z %N %p %E %C %i %R %r %1-2T %I %O %D"
proxy -n
socks -n

looking forward for your replying.
thank you.

**Comment by z3APA3A** [comment]
412 means authentication data was not received from client (within timeout). If you believe this request comes from real client (it may actually come from bots probing your server for anonymous access) you can try to increase BYTE_LONG timeout, see `timeouts` in https://3proxy.ru/doc/man3/3proxy.cfg.3.html. If it comes from random bots you may just ignore it. Also you can check client is configured to use authentication.

**Comment by z3APA3A** [comment]
412 error means means client selected authentication with username and password, 3proxy sent authentication request to client and authentication data was not received within timeout. If you require username+password authentication client must be configured with username and password. If you never check username and password, you can run `socks -u` to prevent socks from indicating username+password authentication is supported.
