### ISSUE TITLE
"command: "proxy" failed with code 40, line 18"

### ISSUE THREAD

**Issue by xLightness** [3proxy/3proxy#703]
"Service not started on line: 18
Command: "proxy" failed with code 40, line 18"
Using Centos 7 

I am trying to create IPv6 using this https://github.com/avcvv/ipv6proxies repository, I get this error that I do not know how to fix 
I am very new to Linux so I do not know how to provide more pieces of information. Please be detailed in what I need to do to get help and get it working! Thank you. I tried to look in older issues but I do not know how to use that information sorry

**Comment by z3APA3A** [comment]
Check line 18 of 3proxy config, there is something wrong with it. For https://github.com/avcvv/ipv6proxies you better ask this project developers for support.
