### ISSUE TITLE
ACL userlist and auth strong

### ISSUE THREAD

**Issue by hunterhe23** [3proxy/3proxy#705]
excuse me.
does userlist of ACL work only when auth strong is configured?
if userlist is configured, but no auth strong, how does that work?

**Comment by z3APA3A** [comment]
userlist works with any authentication except 'none' and 'iponly'.

**Comment by hunterhe23** [comment]
3proxy 10.1.1.10 configured auth strong.
gernerate user:
sh add3proxyuser.sh test Qwe123
cat passwd:
test:CR:$1!26679$0qEhuJh6hzDknYl9zciKI.
configured ACL "allow test 10.1.2.10 www.baidu.com"
request from 10.1.2.10:
curl -x 10.1.1.10:3128 --proxy-user test:Qwe123 www.baidu.com
result: 403 Forbidden
3proxy log error code: 00005
what's wrong?

**Comment by z3APA3A** [comment]
This hash doesn't match to password Qwe123, probably due to `!` sign added after `$1`. Probably you've added this character accidentally, add3proxyuser.sh can not generate salt like this.

**Comment by hunterhe23** [comment]
sorry, i made a written mistake when wirting this issue. the hash is $1$26679$0qEhuJh6hzDknYl9ZciKI.
run conmand "sh add3proxyuser.sh test Qwe123" again, i got another hash.
is that right?

**Comment by z3APA3A** [comment]
provide all configuration files and log records for request

**Comment by hunterhe23** [comment]
i read user guide again and check my config, lack of "users $/conf/passwd".
now auth success.
thank you.
