### ISSUE TITLE
Kill Established Connection After X Seconds

### ISSUE THREAD

**Issue by Al-Bsharat** [3proxy/3proxy#706]
Hello,
There is any way to kill establish a connection after x seconds? Because some of the requests come with the keep-alive option, it will use the same IP repeatedly.

3proxy come with any practical option to solve this?

All the best

**Comment by z3APA3A** [comment]
See timeout command, CONNECTION_LONG is timeout for idle connection. For connection with active data transfer there is no timeout value and it's something unexpected for proxy to kill active connection.
