### ISSUE TITLE
How to use socks DNS instead of tor Dns?

### ISSUE THREAD

**Issue by antouraj77** [3proxy/3proxy#707]
My config is following.
#1
internal 192.168.22.1
daemon
plugin /lib/3proxy/TransparentPlugin.ld.so transparent_plugin
flush
auth iponly
allow * * * *
parent 1000 socks5 127.0.0.1 9050
parent 1000 socks5 173.67.89.21 35674
tcppm -i192.168.22.1 6666 127.0.0.1 11111

Which line I should add to get dns socks or socks of country?
Would be glad for any help!
Thanks

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtoe.asp#NAMES
use socks5+ instead of socks5 + you may want to use fakeresolve to avoid additional name resolution.

**Comment by antouraj77** [comment]
Can you show example plz? Cause I am stuck and little confused! Tnx

**Comment by z3APA3A** [comment]
change

parent 1000 socks5 127.0.0.1 9050
parent 1000 socks5 173.67.89.21 35674

to

parent 1000 socks5 127.0.0.1 9050
parent 1000 socks5+ 173.67.89.21 35674

and add "fakeresolve" to config.
