### ISSUE TITLE
Вопрос по шлюзам

### ISSUE THREAD

**Issue by Olegars** [3proxy/3proxy#708]
Подскажите, как решился вот этот вопрос?
[https://github.com/3proxy/3proxy/issues/180](url)
Не увидел в последней версии "-Di (Входящий интерфейс), -De (Исходящий интерфейс)". Отказались от этого?
Как правльно задействовать нужный шлюз? Через роутинг?
На текущий момент (ubuntu) берет шлюз у которого metric меньше

**Comment by z3APA3A** [comment]
https://3proxy.ru/doc/man3/3proxy.cfg.3.html - есть в последней версии -De/-Di, но лучше делать через source roting, т.к. биндинг к интерфейсу требует прав рута.
