### ISSUE TITLE
Logformat "L" не срабатывает

### ISSUE THREAD

**Issue by srvh** [3proxy/3proxy#709]
Почему-то не срабатывает logformat "L%H:%M %z %E %p %U %C %R %O %I %T"
Имею в виду, что время всегда показывается по Гринвичу, а не локальное.
Проверяю на сервере командой date - показывается верное время моего сервера по часовому поясу +5 GMT
Но 3proxy почему-то логирует все равно по Гринвичу (часовой пояс 00:00) и записывает логи по гринвичу.

В чем может быть проблема?

**Comment by z3APA3A** [comment]
В дефолтной конфигурации под Linux 3proxy выполняется с chroot в /usr/local/3proxy, где недоступны системные файлы в т.ч. информация о временной зоне, можно либо запускать 3proxy без chroot, либо скопировать нужные системные файлы (скорей всего /etc/localtime и /etc/timezone) в /usr/local/3proxy/etc/ (именно скопировать содержимое, т.к. симлинки работать не будут).

**Comment by srvh** [comment]
Спасибо. Все сработало
