### ISSUE TITLE
Переадрессация

### ISSUE THREAD

**Issue by alsosed** [3proxy/3proxy#710]
Как в конфиге прописать ссылку (или текст), на которую будет переадресован пользователь, если этот сайт заблокирован в 3proxy? Пример: пользователь пытается открыть запрещённый сайт и попадает на страницу типа: "данный сайт запрещён политикой организации"

**Comment by z3APA3A** [comment]
Можно использовать StringsPlugin чтобы заменить HTTP-ответы которые дает прокси, но если сайт https:// то подменить или переадресовать не получится без подмены сертификата. Пример файла со строками https://github.com/3proxy/3proxy/blob/master/rus.3ps 

Подмену сертификата можно сделать через SSLPlugin, но я бы не рекомендовал это использовать на живых сотрудниках.
