### ISSUE TITLE
looking to have an ipv6 proxy for an ipv4 subnet

### ISSUE THREAD

**Issue by bramm98** [3proxy/3proxy#714]
Good morning all,

I've been playing around with 3proxy for a couple of days now and I'd like to set it up as a translation proxy from ipv4 to ipv6.

My main idea is to select the proxy in my browser on my ipv4 computer and surf the ipv6 internet.

I've got a IPV6 tunnel set up from my router that works as it should, my subnet is all ipv4 and for now I would like to keep it that way,

my configuration looks as follows:

nscache 65536
nserver 2001:4860:4860::8888
nserver 2001:4860:4860::8844
proxy -6
config /conf/3proxy.cfg
monitor /conf/3proxy.cfg
log /logs/3proxy-%y%m%d.log D
rotate 60
external 2001:xxx:xxxx:9::2
internal 192.168.98.1
auth none
admin -p9090

What am I doing wrong here?

Thanks,

Bram

**Comment by z3APA3A** [comment]
Do you experience any issues? `external` (and may be `internal` depending on configuration you expect) must be set prior to `proxy`, but usually it does not affect connectivity.

**Comment by bramm98** [comment]
hi z3APA3A,
thanks for your reply.
my config now looks like this and it's running on the router itself

nscache 65536
nserver 2001:4860:4860::8888
nserver 2001:4860:4860::8844
config /conf/3proxy.cfg
monitor /conf/3proxy.cfg
log /logs/3proxy-%y%m%d.log D
rotate 60
auth none
proxy -6 -i"192.168.98.1" -e"2001:xxx:xxxx:9::2"

I get a:
"502 Bad Gateway
Host Not Found or connection failed"

Is there a way to debug? I couldn't find anything in the man page about debugging"
this is an ipv6 ip from a tunnelbroker (he), and when i'm on the router i can browse ipv6 sites.

thx,

Bram

**Comment by bramm98** [comment]
Hi z3APA3A,

I fixed it. For some reason google's ipv6 nameservers didn't work, I've set the local caching bind server on my router and all works superb!

thanks for your time

Bram
