### ISSUE TITLE
Трафик в логах

### ISSUE THREAD

**Issue by srvh** [3proxy/3proxy#718]
Записываю трафик в логи поминутно такими строками:
log /logs/3proxy.log C
logformat "L%U %I %O"

Заметил проблему, что не считается часть трафика.
При посещении обычных html сайтов, трафик считается корректно.

Но если я сохраняю файл с сайта (например, какой-нибудь archive.zip), то скачивание этого файла не учитывается в трафике.
Также я пробовал загрузить страницу youtube.com
Инспектор в браузере показывает переданные данные в размере 2,2 Мб
По логам 3proxy показывает только 0,9 Мб

Как-то можно исправить эту проблему?

**Comment by z3APA3A** [comment]
Запись в логе появится в момент закрытия соединения, браузер может держать коннект достаточно долго. Можно либо закрыть браузер, чтобы закрылись активные соединения либо воспользоваться командой logdump - в ней можно установить лимит трафика при достижении которого будет добавляться промежуточная запись в лог-файл.

**Comment by srvh** [comment]
Добавил logdump.
Трафик стал считаться корректно.
Спасибо

**Comment by srvh** [comment]
Можно ли вести учет трафика в 2 разных файла с разными параметрами.
Например, так

log /logs/3proxy.log C
logformat "L%U %I %O"

log /logs/other/all.log D
logformat "L%U %I %O %E %T"

**Comment by z3APA3A** [comment]
Нет, но скорей всего тебе нужны не логи, а счетчики трафика, см counter и файлы отчетов

**Comment by srvh** [comment]
Я пробовал использовать countall, какое-то время это работало.
Но при количестве пользователей 200 и ограничении трафика 200-300 Гб, и большом трафике через прокси начала зависать админка 3proxy, в которой идет подсчет трафика.
Если она зависает, то прокси перестает работать. Приходиться рестартить 3proxy.
Последнее время даже рестарт не помогал. Сразу зависала.
Я убрал счетчики и проблема сразу ушла, все работает корректно. Но приходиться трафик считать по логам.

**Comment by srvh** [comment]
При этом с countall в моменты зависания логи 3proxy не выдавали никаких ошибок
