### ISSUE TITLE
Цепочка parent может работать с Socks?

### ISSUE THREAD

**Issue by srvh** [3proxy/3proxy#719]
3proxy настроен с цепочкой parent на другой http прокси с авторизацией:

parent 1000 http 192.12.12.12 1080 login pass
socks -u2 -i10.10.10.10 -e10.10.10.10 -p1513
proxy -s0 -osTCP_NODELAY -ocTCP_NODELAY -a -n -i10.10.10.10 -e10.10.10.10 -p1514

При этом подключение к http proxy 10.10.10.10 работает корректно.
А подключение к Socks 5 не работает. Вижу, что отсылается запрос, но обратно ничего не получает. Затем подключение по timeout отключается.

Пробовал в цепочку parent ставить connect и connect+
Но тогда не авторизуется внешний прокси.

Есть ли решение?
Цель - получить socks 5 с авторизацией по логину/паролю.

**Comment by srvh** [comment]
Есть ли решение по данной проблеме?

Пробовал просто оставлять строки так:
auth iponly
allow *
parent 1000 http 192.12.12.12 1080 login pass
socks -i10.10.10.10 -e10.10.10.10 -p1513

При подключении вижу, что первый запрос на открытие сайта отправляется, весит около 700 байт. Но ответа не приходит.

Пробовал вместо строки socks сделать proxy так:
proxy -a -n -i10.10.10.10 -e10.10.10.10 -p1513
В этом случае все корректно работает
Как добиться работы с Socks5 ?
Такое ощущение, что цепочка parent не срабатывает при разных типах прокси.

**Comment by z3APA3A** [comment]
Что в логах?

**Comment by srvh** [comment]
Логформат имеет такую запись:
logformat "L%U %E %I %O %n - %T"

Вот подключение через socks5, аутентификация iponly
- 00000 0 517 23.239.16.110 - CONNECT 23.239.16.110:443
- 00000 0 517 5.45.205.241 - CONNECT 5.45.205.241:443
- 00000 73 345 23.239.16.110 - CONNECT 23.239.16.110:80
- 00000 73 298 23.239.16.110 - CONNECT 23.239.16.110:80

Сайт висит и не открывается.

Когда меняю тип прокси с socks на proxy, то сразу все работать начинает и сайты открываются.
Лог с типом proxy такой
- 00000 215 802 23.239.16.110 - CONNECT 23.239.16.110:443 HTTP/1.1
- 00000 948 543 23.202.229.179 - CONNECT 23.202.229.179:80 HTTP/1.1
- 00000 13605 2471 23.239.16.110 - CONNECT 23.239.16.110:443 HTTP/1.1

То есть ошибок 3proxy не показывает. Или как-то по другому нужно их вывести?
Напомню, что моя задача сделать socks5 прокси, который по цепочке parent перенаправляет трафик в http прокси.

**Comment by z3APA3A** [comment]
http как парент поддерживается только для http прокси, для SOCKS надо использовать парент connect или connect+. Если родительский прокси не поддерживает connect на 80й порт, можно добавить локальный редирект в http-прокси и тогда использовать parent http.

**Comment by srvh** [comment]
Спасибо огромное, заработало.
