### ISSUE TITLE
Что значат * и почему их столько сколько их есть?

### ISSUE THREAD

**Issue by emoxam** [3proxy/3proxy#720]
Например в команде allow * * * 443,8443 HTTPS
что означают три * ? Почему их три ?
В cron расписано за что отвечает каждая * а тут не ясно. Нигде не могу найти.
Спасибо

**Comment by ezbik** [comment]
allow <userlist> <sourcelist> <targetlist> <targetportlist> <commandlist> <weekdays> <timeperiodslist>

**Comment by ezbik** [comment]
```
  allow <userlist> <sourcelist> <targetlist> <targetportlist> <commandlist> <weekdays> <timeperiodslist>
```

**Comment by ezbik** [comment]
https://3proxy.ru/howtor.asp

**Comment by emoxam** [comment]
о! понял. спасибо!

**Comment by emoxam** [comment]
auth iponly
proxy -p8888 -i2.2.2.2
allow * 1.1.1.1
deny *
значит ли это что доступ к прокси на 2.2.2.2 будет только у айпи 1.1.1.1 ?

**Comment by z3APA3A** [comment]
нет, не значит, потому что ACL должен идти ДО запуска сервиса

**Comment by emoxam** [comment]
auth iponly
allow * 1.1.1.1
deny *
proxy -p8888 -i2.2.2.2

и прокси пускает отовсюду..

**Comment by z3APA3A** [comment]
добавь логгирование и посмотри что в логах

**Comment by z3APA3A** [comment]
Если больше никаких записей не было, значит твой клиент не ходит в прокси.
И почитай таки How To. Порядок команд важен, конфигурация сервиса должна задаваться до его запуска.

**Comment by emoxam** [comment]
Записи в логе есть, но с задерджкой. но лог никак не объясняет почему доступ есть отовсюду.  Зачем мне его надо было смотреть то вообще?

**Comment by emoxam** [comment]
Виноват, проверял telnet, а надо былопрвоерять браузером, указав прокси в нём!

**Comment by z3APA3A** [comment]
По идее, 0.9+ при такой конфигурации должен был и для telnet сразу закрыть соединение, не дожидаясь запроса.

**Comment by emoxam** [comment]
Однако ж нет
pwd
/usr/local/3proxy/conf

 cat 3proxy.cfg
auth iponly
allow * 77.37.204.239
deny *
proxy -p8888 -i5.61.34.58
