### ISSUE TITLE
Отличие цепочек chain->extpass и param->extpassword

### ISSUE THREAD

**Issue by srvh** [3proxy/3proxy#725]
Настроены прокси и socks с цепочками parent

auth r_auth strong
allow *
parent 1000 http 10.10.10.10 1201 login password
proxy -a -n -i12.12.12.12 -e12.12.12.12 -p1501
flush

auth r_auth strong
allow *
parent 1000 socks5+ 10.10.10.10 1202 login password
socks -u2 -i12.12.12.12 -e12.12.12.12 -p1502
flush

Используется самописный плагин r_auth, который берет пароль пользователя (param->password) и разбивает его на 2 части.
Вторая часть пароля должна добавиться к паролю цепочки parent (в примере ниже это password).
Результат работы плагина r_auth - это модификация пароля в parent цепочке так: password_somethingelse

Проблема в том, что:
1) если модифицируется param->extpassword - то работает только http прокси. Socks5 не срабатывает.
2) если не трогать param->extpassword и модифицировать только цепочку chain->extpass, то работает и http и socks5. Но возникает проблема, что исходный параметр в цепочке chain->extpass = password уже не хранится, и постоянно туда записывается конечная цепочка плагином r_auth.

Можете объяснить в чем различие между этими цепочками?
И почему Socks5 не срабатывает при изменении только param->extpassword ?

**Comment by z3APA3A** [comment]
extpassword это не пароль родительского прокси, а пароль внешнего сервера назначения, например FTP, предназначен он для сервисов типа pop3p, smtpp, ftppr и передается в прикладном протоколе (FTP/POP3/SMTP) а не в протоколе родительского прокси. Для HTTP видимо сработал потому что протоколы совпали, но по идее не должен был. Менять chain неправильно, т.к. он используется разными клиентами и это может приводить к race condition'ам. Можно предложить делать
`parent 1000 socks5+ 10.10.10.10 1202 * *`
тогда для родительского прокси используется username/password с которым пришел клиент. Его можно устанавливать в плагине после проверки авторизации (т.е. не делать двойную авторизацию, 
`auth r_auth strong`
а делать только
`auth r_auth`
а в коде плагина делать что-то типа
```
param->username=... ; //первая часть
param->password=...; //первая часть
res = strongauth(param);
param->username = ...; //вторая часть
param->password = ....;//ваторая часть
return res;
```

**Comment by srvh** [comment]
Спасибо большое.
Это классное решение.

Единственный минус, что тогда password из цепочки parent нужно жестко прописать в плагине.
Password всегда есть, плюс к нему добавляется вторая часть пароля клиента.
Пароль password может периодически меняться. Можно ли прописать в конфиге 3proxy этот пароль в какую-то переменную? Чтобы затем достать ее в плагине?

**Comment by z3APA3A** [comment]
можно в параметры плагина прописать

**Comment by srvh** [comment]
Есть ли пример такой записи в актуальных плагинах 3proxy?

**Comment by srvh** [comment]
Честно говоря, не совсем понял как вытащить затем переменную эту?
Ограничения на использование символов нет, если я передам param1 как login_password ?

**Comment by z3APA3A** [comment]
при вызове плагина просто добавите еще один аргумент к команде plugin. 
Например
plugin myplugin.so func mystrongpassword

Внутри функции func которую вызываете (которая PLUGINAPI int PLUGINCAL ...)
`if(argc > 1) ... // в argv[1] будет "mystrongpassword"`

**Comment by z3APA3A** [comment]
На команде plugin загружается динамическая библиотека (myplugin.so  в примере) из нее вызывается функция (func в примере) со счетчиком аргументов и массивом строк с аргументами, нулевой аргумент - имя функции (func в примере), в данном случае argc = 1, argv[0] = "func", argv[1] = "mystrongpassword".

**Comment by srvh** [comment]
Спасибо за развернутые ответы.
Плагин переписал. Заработало корректно и с http и с socks5.

В конфиге 3proxy добавил строку:
plugin /libexec/AuthPlugin.ld.so AuthPlugin login password

Соответственно параметры должны быть:
argv[1] = login
argv[2] = password

Вот только не могу никак понять, как получить эти параметры в самом плагине.

Пробовал функцию написать так:
void savearg(struct pluginlink *pluginlink, int argc, unsigned char ** argv) {
	if(argc > 1) {
		unsigned char *extl = (unsigned char *)strdup((char *)(pluginlink->argv[1]));
		unsigned char *extp = (unsigned char *)strdup((char *)(pluginlink->argv[2]));
	}
}

И затем вызвать ее в нужном мне месте так:
savearg(pluginlink);

Но сыпятся ошибки.

**Comment by srvh** [comment]
Все получилось. Удалось, использовать argv[1]

Правда вылез один конфуз: в логах теперь пишется в параметре %U - login от удаленного сервера (в нашем примере login), а не реальный логин пользователя, с которым он зашел на сервер.

Это можно как-то побороть?

**Comment by z3APA3A** [comment]
Можно, но если делать совсем правильно, чтобы ничего не отвалилось -  то получится довольно кудряво. Если делать просто, то можно в качестве функции авторизации для r_auth (сейчас там прописан CheckACL) поставить функцию которая будет делать
```
param->username=... ; //вторая  часть
param->password=...; //вторая часть
res = CheckACL(param);
param->username = ...; //первая часть
param->password = ....;//первая часть
return res;
```

т.е. будет восстанавливать обратно username/password после проверки ACLей и редиректов. Альтернативно, можно просто сделать статический chain и struct acentry который на него указывает , в конфигурации не писать parent, а вызвать из функции авторизации handleredirect, типа

```
struct chain *ch;
struct acentry *ace;
...
ace->chains = ch;
....
res = CheckACL(param);
handleredirect(param, ace);
return res;
```

**Comment by srvh** [comment]
По поводу первого решения.
Правильно ли я понимаю, что нужна в целом такая концепция кода?

param->username=... ; //первая часть
param->password=...; //первая часть
res = strongauth(param);
param->username=... ; //вторая  часть
param->password=...; //вторая часть
res = checkACL(param);
param->username = ...; //первая часть
param->password = ....;//первая часть
return res;

Еще при вызове в таком виде выдает ошибку:
/bin/3proxy: symbol lookup error: /libexec/AuthPlugin.ld.so: undefined symbol: checkACL

**Comment by z3APA3A** [comment]
нет, checkACL надо делать в другой функции. В struct auth передается две функции - одна для аутентификации (.authenticate) вторая для авторизации (.authorize), надо в .authorize передать собственную функцию которая будет дергать checkACL. checkACL можно получить через pluginlink (pluginlink->checkACL). В authenticate по идее тоже можно, предварительно проверив что res == 0, но тогда в .authorize надо передать функцию которая всегда будет возвращать 0.

**Comment by z3APA3A** [comment]
а pluginlink ты не забыл проинициализировать? pluginlink передается в функцию инициализации, а тут у тебя глобальная переменная скорей всего, он у тебя туда точно попал?

**Comment by srvh** [comment]
Да, вы правы.

Исправил так:

```
        alwaysauth.authenticate = aufunc;

		int mycheckacl(struct clientparam * param, struct pluginlink * pluginlink) {		
			int res = pluginlink->checkACL;
			free(param->username);
			free(param->password);
			param->username = (unsigned char *)strdup((char *)(clientl));
			param->password = (unsigned char *)strdup((char *)(clientp));
			print_log(param, "Chain 3 log");
			return res;
		}

	alwaysauth.authorize = mycheckacl;
```

Методом проб и ошибок понял, что если добавляешь  pluginlink->checkACL(param) - то 3proxy вылетает с ошибкой
Сейчас эта функция похоже срабатывает, потому что print_log выдает измененные данные логина и пароля.

В логе 3proxy появились строки вида (test логин клиента):
00000 test PROXY 0 0 CONNECT

Но проблема в том, что Интернет теперь не работает. То есть прокси в браузере выдает ошибку:
Secure Connection Failed (PR_END_OF_FILE_ERROR)

Такое ощущение, что происходит ошибка обращения к цепочке parent.



При сборке плагина появляется 2 предупреждения:

```
В функции «mycheckacl»:
предупреждение: при инициализации указатель преобразуется в целое без приведения типа [по умолчанию включена]
int res = pluginlink->checkACL;
               ^
В функции «ResidentAuthPlugin»:
предупреждение: несовместимый тип указателя в присваивании [по умолчанию включена]
alwaysauth.authorize = mycheckacl;
                                     ^
```

**Comment by z3APA3A** [comment]
pluginlink->checkACL это указатель на функцию, а вернуть надо результат функции. В mycheckacl никто не будет передавать pluginlink, его передают в функцию инициализации плагина. Сохрани там указатель на pluginlink в глобальную переменную и вызывай через эту переменную.

**Comment by srvh** [comment]
Еще подскажите, заметил по логу, что функция .authorize иногда выполняется дважды, иногда трижды, но чаще всего 1 раз.
Это нормальное поведение?

**Comment by z3APA3A** [comment]
https://3proxy.ru/donations/?l=RU
донаты лучше всего через https://www.tinkoff.ru/sl/P223p57JPc

Про .authorize не уверен что ты имеешь ввиду, authenticate и authorize всегда вызываются в паре.  Если что-то не так логается - значит что-то не так логаешь. Повторная авторизация может происходить например при обновлении конфигурации, см команды force/noforce, но будет вызываться и authenticate и authorize.

**Comment by srvh** [comment]
Спасибо.

**Comment by srvh** [comment]
Данный плагин корректно работал с СentOS 7.
В связи с закрытием проекта CentOS 7 решил перейти на Debian 12.
Делаю все также, как и на CentOS. При сборке 3proxy с плагином никаких ошибок не возникает.
Только warning:
AuthPlugin.c:79:19: warning: implicit declaration of function ‘strongauth’; did you mean ‘strncat’? [-Wimplicit-function-declaration]
Насколько я помню такой же warning был и на СentOS (плагин работал корректно).

На Debian плагин не работает. Прокси выдает ошибку:
curl: (56) Proxy CONNECT aborted

Добавил в плагин строку с объявлением функции (перед строкой с использованием strongauth) такую:
int strongauth(struct clientparam *);
Warning при сборке пропала, но в syslog при попытке подключиться к прокси выдает такое сообщение:
symbol lookup error: /libexec/AuthPlugin.ld.so: undefined symbol: strongauth

Есть ли какие-то особенности сборки для Debian ?
Установлены последние версии програм из стандартного репозитория Debian
libgmp3-dev libssl-dev libc6-dev git gcc make

По логу самого плагина вижу, что плагин доходит до строчки использования strongauth и затем процесс падает в ошибку.
Поискал в Интернете как решить проблему с undefined symbol: strongauth
Не понял, что нужно сделать. Недостаток опыта.

Буду благодарен любым рекомендациям. Спасибо.

**Comment by z3APA3A** [comment]
strongauth можно получить как указатель 
```
int (*strongauth)(struct clientparam *);
...
strongauth = pl->findbyname("strongauth");
```

**Comment by srvh** [comment]
Ранее strongauth в плагине брался так:
int strongauth = strongauth(param);

Сейчас заменил на такие 2 строки:
int (*strongauth)(struct clientparam *);
strongauth = pl->findbyname("strongauth");

При сборке появляется такой warning:
warning: returning ‘int (*)(struct clientparam *)’ from a function with return type ‘int’ makes integer from pointer without a cast

Теперь прокси стал проходить по всем цепочкам плагина, но прокси как будто зависает, не работает.
Наверное из-за warning strongauth не до конца срабатывает ?

**Comment by srvh** [comment]
Спасибо, все получилось.

При использовании неверного логина/пароля в логах создаются такие записи:
1709563685.518 PROXY.3003 00006 test 88.99.22.33:50531 0.0.0.0:0 0 0 0 CONNECT google.com:443 HTTP/1.1
Можно ли как-то их убрать?
Дело в том, что по таким логам идет учет трафика. И таких пустых записей очень много создается.
Не получается использовать встроенный счетчик трафика в 3proxy, так как возникает проблема переноса бинарного файла трафика между разными серверами.

**Comment by z3APA3A** [comment]
Можно добавить в начало ACL строчки
```
deny -
nolog
```
первая строчка запрещает неавторизованных пользователей, вторая говорит что запросы попавшие под это правило не надо логировать

**Comment by z3APA3A** [comment]
но есть шанс что сработает это только с
auth iponly strong

**Comment by srvh** [comment]
Не совсем понятно в какое место нужно вставить.
У меня конфиг вида:

auth myauth
allow *
parent 1000 http 123.23.43.34 1203 * *
proxy
flush

**Comment by srvh** [comment]
Да, теперь такие логи не сыплются, но видимо из-за этой строки в моем плагине авторизация сломалась:
    struct chain *chain = param->srv && param->srv->acl ? param->srv->acl->chains : NULL;

Всегда попадает здесь в NULL

**Comment by z3APA3A** [comment]
Вполне ожидаемо, потому что chains у тебя ушел во второе правило (param->srv->acl->next), сделай цикл по списку param->srv->acl и найди элемент с ненулевым chains

**Comment by srvh** [comment]
Огромное спасибо, все получилось.

**Comment by srvh** [comment]
Подскажите, еще пожалуйста, у меня запущен 3proxy.
При старте все процессы на сервере занимают в памяти 1,5 Гб. Нагрузка на 3proxy есть ощутимая.

Через 5-6 дней 3proxy подъедает практически всю оперативную память. Занято 7-7,5 из 8 Гб оперативки.
Пока не было свапа периодически 3proxy умирал с состоянием Out of memory.
Добавил swap - теперь 3proxy не умирает, но оперативная память занята на 85-95%
Если сделать рестарт сервиса, то общая нагрузка возвращается к 1,5 Гб. При этом в конфиге есть параметр noforce. То есть клиенты не отваливаются при рестарте. Нагрузка остается такой же.

В плагине, я вроде бы везде очищаю переменные через параметр free.
Можете посоветовать что можно сделать?

**Comment by z3APA3A** [comment]
В 3proxy сейчас известных утечек памяти, по крайней мере масштабных, нет. Значит или не очищаешь или просто очень много используешь. Если потребление памяти быстро растет а потом рост постепенно останавливается - то  это скорей всего не утечка. Если ты используешь большой stacksize - то потребление ожидаемо будет большим.

**Comment by srvh** [comment]
Подскажите, а можно ли в 3proxy организовать двойную проверку одновременно по ip и логину/паролю ?
Если используешь iponly strong - то сначала проверяется IP и если не подходит, то срабатывает strong.
А мне нужно разрешить доступ только с определенного IP для каждого пользователя, но при этом авторизовывать по логину/паролю.

Список разрешенных IP адресов разный у каждого клиента. У кого-то может быть доступ с любого IP адреса.

**Comment by z3APA3A** [comment]
```
auth strong
...
allow ivanov 192.168.1.1
allow petrov 192.168.1.2
allow sidorov *
deny *

```

**Comment by srvh** [comment]
Спасибо, в обычном конфиге работает отлично.
Но в моем случае самописный плагин меняет логин и пароль, чтобы авторизоваться на parent прокси
Строка в конфиге:
parent 1000 http someproxy.com 1080 * *

То есть пользователь подключается с логином ivanov и паролем pass_133
И происходит авторизация на текущем сервере через функцию alwaysauth.authenticate

Далее для функции alwaysauth.authorize происходит замена Логина на other_133
То есть из пароля (pass_133) добавляется часть после знака _
В итоге для цепочки parent логин используется уже как other_133
Далее происходит:
pl->checkACL(param)

Все работает корректно. Пользователи авторизуются и перекидываются на второй прокси сервер.

Проблема только в том, что не срабатывает данное правило:
allow ivanov 192.168.1.1
В итоге нужно использовать такое правило:
allow other_133 192.168.1.1
А оно не совсем корректно, так как ведется учет пользователей по начальным логинам типа ivanov.

Как-то можно для правил allow использовать старый логин. А для parent уже преобразовывать и ставить новый логин?
Я так понимаю, что обе команды allow и parent заложены в едином алгоритме pl->checkACL(param) ?

Благодарю за ответ
