### ISSUE TITLE
Запрос функции: Блокировка отдельных страниц/файлов сайта

### ISSUE THREAD

**Issue by allekszhur** [3proxy/3proxy#727]
![image](https://user-images.githubusercontent.com/75319363/150242375-61bcf981-233c-45c4-838e-3f48a71e7ee7.png)
Добавьте возможность блокировать не только сайтов полностью по Url. А допустим определенную страницу пользователя в vk.com или же какой ни будь .png файл на сайте по url https://site.ru/image/1.png к примеру

**Comment by z3APA3A** [comment]
https://3proxy.ru/plugins/PCREPlugin/
но с HTTPs это не будет работать, т.к. прокси не видит адреса страниц, если только еще и делать подмену сертификата
https://3proxy.ru/plugins/SSLPlugin/

**Comment by allekszhur** [comment]
Извиняюсь, но не могу понять. в конфиге пишу
`daemon
plugin PCREPlugin.dll pcre_plugin
stacksize 65536
maxconn 1000
nserver 1.1.1.1
nscache 65536`

мне выдается ошибка
Command: 'plugin' failed with code 1, line 2

И я так понял плагин блокирует если есть совпадения фразы в url? 
Или так-же запрет на загрузку файла с сайта. Допустим я входу на vk.com
и мне нужно заблокировать отображение логотипа. Как это сделать?
Был бы очень признателен если бы вы мне помогли.

**Comment by z3APA3A** [comment]
В какой ОС?

**Comment by allekszhur** [comment]
Ubuntu 20.04

**Comment by allekszhur** [comment]
Уже попробовал, не помогло

**Comment by allekszhur** [comment]
Вывод ошибки 
Command: 'plugin' failed with code 1, line 8

**Comment by z3APA3A** [comment]
а что говорит ls -l /usr/local/3proxy/PCREPlugin.ld.so

**Comment by allekszhur** [comment]
ls: cannot access '/usr/local/3proxy/PCREPlugin.ld.so': No such file or directory
Странно. Хотя файл находится в папке. Минутку

**Comment by z3APA3A** [comment]
vk.com использует https и прокси не видит заголовки HTTP-запроса, т.к. он идет внутри TLS

**Comment by allekszhur** [comment]
Подскажите. SslPlugin.dll для Windows.
Как быть с *nix системами?

**Comment by allekszhur** [comment]
Подскажите. На WIndows 
plugin /path/to/SslPlugin.dll ssl_plugin
А на *nix системах что использовать вместо SslPlugin.dll?

**Comment by allekszhur** [comment]
Подскажите, с чем может быть связана ошибка ?
symbol lookup error: /usr/local/3proxy/plugins/SSLPlugin.ld.so: undefined symbol: OPENSSL_init_ssl
