### ISSUE TITLE
Proxy и Socks на одном IP адресе и порту

### ISSUE THREAD

**Issue by srvh** [3proxy/3proxy#732]
Есть необходимость поднять proxy и socks на одном IP адресе и порту.

Пробовал делать так:

```
auth strong
allow *
proxy -s0 -olSO_REUSEADDR,SO_REUSEPORT -osTCP_NODELAY -ocTCP_NODELAY -a -n -i1.1.1.1 -e1.1.1.1 -p1505
flush

auth strong
allow *
socks -u2 -olSO_REUSEADDR,SO_REUSEPORT -i1.1.1.1 -e1.1.1.1 -p1505
flush
```

Но подвисает Socks. Срабатывает через раз.
При большой нагрузке стоит ли вешать на один порт 2 сервиса? Или лучше разъединить по портам?

**Comment by z3APA3A** [comment]
В твоей конфигурации два сервиса слушают один порт, один из них получит запрос, а дальше как повезет. Так как ты ожидаешь это не работает, http и socks должны слушаться на разных портах.
