### ISSUE TITLE
Is there an opportunity to map socks' login:password to different proxies?

### ISSUE THREAD

**Issue by netms7** [3proxy/3proxy#733]
Hi. I've been using 3proxy for a while. You did a great job. Thank you for this awesome project.
I want to know if 3proxy provides an opportunity to listen for 1 socks5 port and then forward the traffic to different proxies (or deny) depending on socks5' login:password specified?
Is there any way to do that?
If there is no way, then is it planned to implement it?
Hope for your answer! Best regards

**Comment by z3APA3A** [comment]
see allow/parent directive, what you need is something like

```
allow user1
parent 1000 socks5 parent1 login1 password1
allow user2
parent 1000 socks5 parent2 login2 password2
```
