### ISSUE TITLE
About Socks5 proxy

### ISSUE THREAD

**Issue by mustafasevincc** [3proxy/3proxy#734]
Hello,

I have virtual server. I have multiple IP addresses on this server. Can I give different IPs to different users?
E.g : 
IP of xxx.xxx.xxx.20 to user User1
IP of xxx.xxx.xxx.21 to user user2
IP of xxx.xxx.xxx.22 to user user3

My server's operating system is linux.  Can I do this with 3proxy? How can I do it?

**Comment by z3APA3A** [comment]
```
auth strong
users ...
allow user1
parent 1000 extip xxx.xxx.xxx.20 0
allow user2
parent 1000 extip xxx.xxx.xxx.21 0
allow user3
parent 1000 extip xxx.xxx.xxx.22 0
proxy

```
or via RADIUS parameter if RADIUS is used for authentication
