### ISSUE TITLE
received these requests per email?

### ISSUE THREAD

**Issue by f1-outsourcing** [3proxy/3proxy#736]
Did you get these emails on 3proxy@3proxy.ru? 

**hostname in source list would also be nice**
hostname in source list would also be nice

**3proxy internal / external config option**

Hi 

Maybe add an option to specify a range for internal (and external) because if you launch it in a container the ip addresses could be dynamic. 

something like 
internal 192.168.0.0/16

And maybe an option to exclude internal addresses from the external so you can just leave external to 0.0.0.0

**Comment by z3APA3A** [comment]
Source list supports names (resolved on configuration reading to IP) and ranges, but if you want to authenticate based on DNS name you should consider

auth dnsname

as a more reliable mechanism.

**Comment by f1-outsourcing** [comment]
> Source in ACL supports names (resolved on configuration reading to IP) and ranges, but if you want to authenticate based on DNS name you should consider
> 
> auth dnsname
> 
> as a more reliable mechanism.

It is just that I have some containers that get random ip addresses, so I have to use names. With some I even use also a user. I am building https://github.com/z3apa3a/3proxy on alpine. It looks like this is not supported.

This allows me to connect to a website:
```
auth iponly
deny * * 127.0.0.1
#allow * test.local * 80,443
allow * 192.168.220.111 * 80,443
```

This refuses me the connection to the same website:
```
auth iponly
deny * * 127.0.0.1
allow * test.local * 80,443
#allow * 192.168.220.111 * 80,443
```

**Comment by f1-outsourcing** [comment]
> Source in ACL supports names (resolved on configuration reading to IP) and ranges, 
>
Would be nice to have this resolved more often. I am not really scaling tasks dynamically. But if I would scale task test.local to 3 instances I would get 2 extra ip addresses that 3proxy does not know of, something like, 

```
[test2 image-3proxy]# dig +short test.local
192.168.220.111
192.168.220.211
192.168.220.10
```
Which translates into 3 ACL's

**Comment by f1-outsourcing** [comment]
> for internal/external - use ifup/ifdown scripts to generate interface-specific 3proxy configuration, it's a standard approach. See e.g. https://askubuntu.com/questions/41400/how-do-i-make-the-script-to-run-automatically-when-tun0-interface-up-down-events

I am not sure what you mean. I am running 3proxy in a container and when I launch the container I have no idea what the ip address is of an interface. But maybe the options -Di and -De are better for this.

[1]
https://3proxy.ru/doc/man3/3proxy.cfg.3.html
