### ISSUE TITLE
3proxy deny targetlist

### ISSUE THREAD

**Issue by mobileproxy** [3proxy/3proxy#738]
Можно ли указывать в списке запретов конкретные URL или маски URL?
Если да, то как?
Например: *google.com/bussines* - и запрет будет касаться доступа только с таким адресом

**Comment by alexeykudr** [comment]
Привет, удалось ли решить проблему? У меня вроде конфиг нормальный, но сайты все равно открываются, так что по сути проблема та же

**Comment by z3APA3A** [comment]
Можно использовать PCREPlugin, но надо понимать, что в HTTPS прокси не видит URL запроса, только в HTTP.
