### ISSUE TITLE
Filter by domain

### ISSUE THREAD

**Issue by erol1602** [3proxy/3proxy#741]
Hello.

I dont want to deny other accesses. I want them to redirect to another port.

allow * * google.com
auth strong
allow user1
parent 1000 http 127.0.0.1 3000 #port and proxy works on 3000.
deny *
proxy -p3128

allow *
auth strong
allow user1
parent 1000 http 127.0.0.1 3000 #port and proxy works on 3001.
deny *
proxy -p3129

I want when user1 access to proxy with 3128, it will use 3000 port for access google.com. If he use the same port for other domains, I want it use from -p3129 to 3001 port.

How can I do this?

**Comment by z3APA3A** [comment]
1. 'parent' is applied to previous 'allow' command. In order to redirect traffic to google.com you need corresponding 'parent' after `allow * * google.com`.
2. 'flush' is required to start new ACL, if you want different ACLs between 2 `proxy` specify `flush` between.

**Comment by R1602** [comment]
Is it correct?

#METHOD 1
auth strong
allow * * myip.com,*.myip.com _#URL https://api.myip.com/ NEEDS TO SHOW IP1_
parent 1000 http IP1 PORT1
allow * * ipify.org,*.ipify.org _#URL https://api.ipify.org/ NEEDS TO SHOW IP2_
parent 1000 http IP2 PORT2
proxy -n -p3128 -a
flush


#METHOD 2
auth strong
allow * * myip.com,*.myip.com _#URL https://api.myip.com/ NEEDS TO SHOW IP1_
parent 1000 http IP1 PORT1
allow * * ipify.org,*.ipify.org _#URL https://api.ipify.org/ NEEDS TO SHOW IP2_
parent 1000 http IP2 PORT2
allow * _#ALL OTHER CONNECTIONS TO IP3_
parent 1000 http IP3 PORT3
proxy -n -p3129 -a
flush

**Comment by z3APA3A** [comment]
If IP1:PORT1 / IP2:PORT2 / IP3:PORT2 are ip's of external http proxy it should probably work as you expect, if I correctly understand your expectations. If IP1/IP2/IP3 are configured on the same host, you should use parent `extip`, e.g. `parent 1000 extip IP1 0` instead of `http` parent.
