### ISSUE TITLE
Прокси не всё передаёт

### ISSUE THREAD

**Issue by YaZanuda111111** [3proxy/3proxy#742]
Здравствуйте, не так давно я воспользовался вашим прокси сервером и вроде загружает страницы и всё хорошо но почти все всплывающие окна не грузит а так же на некоторых страницах он не грузит и чат. Возможно я что то неверно настроил или ваш сервер. Может мне кто то помочь?

**Comment by YaZanuda111111** [comment]
maxconn 100
flush
auth strong
log
users qiht:CL:~gerg43gfdc
allow qiktrefhdert
proxy -n -a -p3128 -i"ТУТ ИП" -e"ТУТ ИП"

Вот мой конфиг

**Comment by z3APA3A** [comment]
прокси все передает, начни например с просмотра логов в браузере и в прокси-сервере чтобы понять что именно и почему не проходит. Возможно тебе, например, 100 коннектов не хватает.

**Comment by YaZanuda111111** [comment]
![image](https://user-images.githubusercontent.com/78689718/155170102-b1728f42-36b7-4cb2-bf2e-1202104f6b10.png) - остальное всё грузит
Я не нашел где хранятся логи прокси сервака.

**Comment by YaZanuda111111** [comment]
Решение, сменил браузер который использовал прокси с firefox на opera (с расширением ProxyControl). 3proxy плохо работает с firefox лично у меня
