### ISSUE TITLE
правило UDP associate

### ISSUE THREAD

**Issue by nss1987** [3proxy/3proxy#743]
Здравствуйте! У меня есть некий скрипт на базе openvpn. Требуется установить для 3proxy правило udp assoiate(3proxy использую для windows) Цитирую инструкцию скрипта. Заранее благодарю за помощь
"Желательно, чтобы у прокси было настроено элементарное правило udp associate. Если
оно есть то это позволит устанавливать соединение с маскировкой dns то есть вы будете

полностью засекречены, dns будет передаваться тот же, что и на вашем прокси. Весь
трафик по udp-протоколу будет проксироваться и это скроет вас максимально.
Если udp нет, то возможен просвет dns вашего сервера на котором поднимается vpn. Для
многих случаев это ни на что не влияет, но например для фейсбука это критично.
Как узнать, подключено ли правило udp? Если у вас покупной прокси то задайте вопрос
продавцу, как правило это правило)) уже работает у них.
Если у вас поднятый самостоятельно, то udp включается простой командой. Например
если вы поднимали прокси через dante (этот метод чаще всего встречаю в сети) то просто
в графу command добавьте вот эти параметры: "udpassociate bindreply udpreply" и правило
будет включено."

**Comment by z3APA3A** [comment]
UDP associate это функция SOCKSv5, в 3proxy она реализована и отдельного включения не требует.
