### ISSUE TITLE
dual extip

### ISSUE THREAD

**Issue by armpdq** [3proxy/3proxy#744]
возможно ли использовать два extip в паре с parent ? например: 
```
allow user1
parent 1000 extip ipv6 extip ipv4  0
socks -64 -p40000  

```
в текущем виде выход наружу по в6 работает, по в4 падает с ошибкой 00012
версия 3proxy: 0.9.4

задача: выпускать юзеров по обоим протоколам.
@z3APA3A

**Comment by z3APA3A** [comment]
как-то так:

```
allow user1 0.0.0.0/0
parent 1000 extip (ip4)
allow user1 ::0/0
parent 1000 extip (ip6)
```
