### ISSUE TITLE
del ICQ from debian/3proxy.manpages

### ISSUE THREAD

**Issue by ezbik** [3proxy/3proxy#752]
```
--- a/debian/3proxy.manpages
+++ b/debian/3proxy.manpages
@@ -1,10 +1,9 @@
 man/3proxy.8
 man/3proxy.cfg.3
 man/ftppr.8
-man/icqpr.8
 man/pop3p.8
 man/proxy.8
```

.. so `dpkg-buildpackage -b` will work.

**Comment by z3APA3A** [comment]
Seems it's already removed in master https://github.com/3proxy/3proxy/blob/master/scripts/debian/3proxy.manpages

**Comment by ezbik** [comment]
What is the difference between 

`./scripts/debian/`  & `./debian/` folders? The latter seems outdated?
