### ISSUE TITLE
Вопрос: Перенаправление на внешний IP раутера

### ISSUE THREAD

**Issue by dca00** [3proxy/3proxy#754]
Пользователь ВПН обратился: может зайти на любой сайт кроме одного. Этот сайт перенаправляет его на внешний айпи моего раутера. Я сам на тот же сайт из локалки могу зайти, хоть с той же машины где 3proxy, что с любой другой. Почему такое может происходить с тем, кто заходит в локалку по ВПН и что делать?

Если я беру IP этого сайта и обращаюсь по ниму, то он отвечает заглушкой (какое-то облако). Пользователь ВПН видит то же самое. То есть только если он обращается по ДНС имени, то происходит перенаправление, а если по айпи, то нет (но и на сам сайт разумеется попасть не может в виду именованного хоста у их облака).

Спасибо огромное за Ваш продукт и помощь!

**Comment by z3APA3A** [comment]
Смотри по логам 3proxy  и/или в браузере на стороне пользователя какие обращения и куда были от пользвоателя. Может быть сайт отдает редирект если считает пользователя ботом, например.
