### ISSUE TITLE
Конвертация трафика http в socks5

### ISSUE THREAD

**Issue by 69leo** [3proxy/3proxy#756]
Добрый день!
Возможно ли настроить 3proxy в качестве промежуточного локального прокси для передачи http трафика Squid в Shadowsocks?

**Comment by z3APA3A** [comment]
Если я правильно понимаю что ты хочешь, то

```
fakeresolve
auth iponly
allow *
parent 1000 socks5+ 127.0.0.1 номер_порта_socks5
proxy -i127.0.0.1 -pНомер_порта_http_прокси
```

**Comment by 69leo** [comment]
daemon
nscache 65536
# DNS Servers
nserver 1.0.0.1
nserver 1.1.1.1
timeouts 1 5 30 60 180 1800 15 60
# Директория под логи (создаст сам)
log /var/log/3proxy/log D
rotate 60

# Включаем авторизацию
#auth strong
# Описываем пользователей (Имя:ТИП:Пароль)
#users 3proxy:CL:fk59ck,aio()56cnUFkR;
#users user2:CL:password2
# Какие порты обслуживаем
#allow * * * 80 HTTP
#allow * * * 443 HTTPS
# Запрещаем остальные порты
#deny *
# Либо разрешаем все
allow *
 
# Описываем наши сетевые интерфейсы,
# если интерфейс один, один IP в ext. и int (или можно не указывать).
external 0.0.0.0
internal 127.0.0.1

# Количество соединений
maxconn 150
# SOCKS5 сервер на 1060 порту
socks -p1060
# HTTP Proxy-server на 1070 порту
proxy -n -p1070
setgid 65534
setuid 65534

fakeresolve
auth iponly
allow *
parent 1000 socks5+ 127.0.0.1 1080      #Адрес и порт Shadowsocks
proxy -i127.0.0.1 -p1070


При http на 1070, трафик пойдет через Shadowsocks ?

**Comment by 69leo** [comment]
root@OPNsense:~ # curl --socks5 localhost:1080 ip.sb
55.37.124.214
root@OPNsense:~ # curl localhost:1070 ip.sb
curl: (28) Failed to connect to localhost port 1070 after 75227 ms: Operation timed out

**Comment by z3APA3A** [comment]
я не очень понимаю что ты хочешь сделать таким конфигом. Зачем ты запускаешь еще один proxy -n -p1070 ? Если ты хочешь в этом же конфиге запускать еще и socks на 1060 - поставь после запуска socks flush, чтобы начать новый ACL. Но я бы рекомендовал запускаться отдельным конфигом, потому что для SOCKS тебе скорей всего надо чтобы DNS резолвился а для перенаправления в shafowsocks - нет, а конфигурация DNS общая

**Comment by 69leo** [comment]
Ошибку понял, исправил:

# Количество соединений
maxconn 50
# SOCKS5 сервер на 1060 порту
#socks -p1060
# HTTP Proxy-server на 1070 порту
#proxy -n -p1070
setgid 65534
setuid 65534

Но трафик не идет:

root@OPNsense:~ # sockstat -4 | grep 3p
nobody   3proxy     96474 5  tcp4   127.0.0.1:1070        *:*

root@OPNsense:~ # curl localhost:1070 ip.sb
<html><head><title>502 Bad Gateway</title></head>
<body><h2>502 Bad Gateway</h2><h3>Failed to connect parent proxy</h3></body></html>
185.94.184.232

**Comment by z3APA3A** [comment]
полный конфиг какой сейчас?

**Comment by 69leo** [comment]
daemon
nscache 65536
# DNS Servers
nserver 1.0.0.1
nserver 1.1.1.1
timeouts 1 5 30 60 180 1800 15 60
# Директория под логи (создаст сам)
log /var/log/3proxy/log D
rotate 60

# Включаем авторизацию
#auth strong
# Описываем пользователей (Имя:ТИП:Пароль)
#users 3proxy:CL:fk59ck,aio()56cnUFkR;
#users user2:CL:password2
# Какие порты обслуживаем
#allow * * * 80 HTTP
#allow * * * 443 HTTPS
# Запрещаем остальные порты
#deny *
# Либо разрешаем все
#allow *

# Описываем наши сетевые интерфейсы,
# если интерфейс один, один IP в ext. и int (или можно не указывать).
external 0.0.0.0
internal 127.0.0.1
# Количество соединений
maxconn 50
# SOCKS5 сервер на 1060 порту
#socks -p1060
# HTTP Proxy-server на 1070 порту
#proxy -n -p1070
setgid 65534
setuid 65534

fakeresolve
auth iponly
allow *
parent 1000 socks5+ 127.0.0.1 1080      #Адрес и порт Shadowsocks
proxy -i127.0.0.1 -p1070
`# Количество соединений
maxconn 50
# SOCKS5 сервер на 1060 порту
#socks -p1060
# HTTP Proxy-server на 1070 порту
#proxy -n -p1070
setgid 65534
setuid 65534

fakeresolve
auth iponly
allow *
parent 1000 socks5+ 127.0.0.1 1080      #Адрес и порт Shadowsocks
proxy -i127.0.0.1 -p1070

**Comment by 69leo** [comment]
> у тебя было
> 
> allow *
> 
> ...
> 
> allow * parent
> 
> в результате работает первый allow который без parent. Поэтому надо или убрать первый allow или добавить flush чтобы начать новый ACL со вторым allow

Да, это уже исправил

**Comment by 69leo** [comment]
'root@OPNsense:~ # sockstat -4 | grep 3p
nobody 3proxy 96474 5 tcp4 127.0.0.1:1070 :

root@OPNsense:~ # curl localhost:1070 ip.sb

<title>502 Bad Gateway</title>
502 Bad Gateway
Failed to connect parent proxy
185.94.184.232'

**Comment by z3APA3A** [comment]
Что в конфиге? Что в логах?
