### ISSUE TITLE
Постоянно увеличивается количество процесcов 3proxy

### ISSUE THREAD

**Issue by Cutter33** [3proxy/3proxy#757]
Работаю на убунту  21
Запускаю 40 различных конфигов 3прокси, каждый отдельным процессом
в результате  появляется много процессов, которые как-бы отработали и висят просто занимая thr 
Лмиты - делал
все перепробовал - не получается

 67468 root       20   0 2087M 54788  1724 S  0.0  1.4  0:00.00 /usr/local/3proxy/3proxy /usr/local/3proxy/cfg/130.cfg
 67502 root       20   0 2061M 42304  1972 S  0.0  1.1  0:00.00 /usr/local/3proxy/3proxy /usr/local/3proxy/cfg/138.cfg
 67504 root       20   0 2017M 19480  1808 S  0.0  0.5  0:00.00 /usr/local/3proxy/3proxy /usr/local/3proxy/cfg/118.cfg
 67517 root       20   0 2068M 45388  2020 S  0.0  1.1  0:00.00 /usr/local/3proxy/3proxy /usr/local/3proxy/cfg/137.cfg
 67518 root       20   0 2017M 19480  1808 S  0.0  0.5  0:00.00 /usr/local/3proxy/3proxy /usr/local/3proxy/cfg/118.cfg
 67533 root       20   0 2017M 19480  1808 S  0.0  0.5  0:00.00 /usr/local/3proxy/3proxy /usr/local/3proxy/cfg/118.cfg
 67639 root       20   0 2087M 54788  1724 S  0.0  1.4  0:00.00 /usr/local/3proxy/3proxy /usr/local/3proxy/cfg/130.cfg
 67645 root       20   0 2017M 19480  1808 S  0.0  0.5  0:00.00 /usr/local/3proxy/3proxy /usr/local/3proxy/cfg/118.cfg
 67683 root       20   0 2068M 45388  2020 S  0.0  1.1  0:00.00 /usr/local/3proxy/3proxy /usr/local/3proxy/cfg/137.cfg
 67691 root       20   0 2017M 19480  1808 S  0.0  0.5  0:00.00 /usr/local/3proxy/3proxy /usr/local/3proxy/cfg/118.cfg
 67838 root       20   0 2017M 19480  1808 S  0.0  0.5  0:00.00 /usr/local/3proxy/3proxy /usr/local/3proxy/cfg/118.cfg
 67872 root       20   0 2087M 54788  1724 S  0.0  1.4  0:00.00 /usr/local/3proxy/3proxy /usr/local/3proxy/cfg/130.cfg
 68029 root       20   0 2087M 54788  1724 S  0.0  1.4  0:00.00 /usr/local/3proxy/3proxy /usr/local/3proxy/cfg/130.cfg
 68031 root       20   0 2087M 54788  1724 S  0.0  1.4  0:00.00 /usr/local/3proxy/3proxy /usr/local/3proxy/cfg/130.cfg
 68065 root       20   0 2087M 54788  1724 S  0.0  1.4  0:00.00 /usr/local/3proxy/3proxy /usr/local/3proxy/cfg/130.cfg
 68079 root       20   0 2025M 22292  1816 S  0.0  0.6  0:00.00 /usr/local/3proxy/3proxy /usr/local/3proxy/cfg/113.cfg
И так далее до 65 350 штук, потом прокси постепенно начинают тупить и на ВПС не зайти даже через консоль, пока не перезагрузить
такая проблема как на мощных , так и не очень ВПСах 
Если сократить до 20 конфиг файлов, то процесс замедляется, но процессы все-равно бесконтрольно идут в рост и просто "висят"

**Comment by z3APA3A** [comment]
thr это потоки, а не процессы, 3proxy использует подход одно соединение - один поток, поэтому число потоков будет примерно соответствовать числу активных соединений, продробней тут
https://3proxy.ru/highload.asp
