### ISSUE TITLE
Is my project feasible with 3 proxies? 

### ISSUE THREAD

**Issue by Soowarez** [3proxy/3proxy#760]
Hello,

I want to make proxy (Shared proxy, unique proxy)

I made a small Sheïma in order to better understand what I want to do.

- Before launching myself in this project, I would like to know if it is feasible or not?

- If yes, how to proceed?

- Should I use OpenVPN?

![Proxy-Server](https://user-images.githubusercontent.com/93844477/160378153-7300c01a-01db-4907-80d3-9efe01b893b6.png)

Thank you very much in advance for your answers

**Comment by ezbik** [comment]
>If yes, how to proceed?

Learn Linux, networking, firewalls, routing.
Develop scripts for automatic management of the 4g modems.

Openvpn is suitable, there are many alternatives, but openvpn is good to start with.

**Comment by ezbik** [comment]
> What is the purpose for multiple proxies here?

E.g. for bandwidth accounting. It might be required to count bandwidth per user differently on different modems.

 Yet users may want to have different proxy passwords on different modems, with the same login.

**Comment by Soowarez** [comment]
Sur le schéma les proxy sont les clients.
selon vous quel est la meilleur solution pour faire ce que je souhaite ?

Mon but et de vendre des proxy a des personnes qui bot sur des jeux, il aurons donc besoin de proxy avec user:password:proxy:port

j'ai deja installer 3proxy en local a mon domicile et fonctionne super bien mais je veut partir sur un vps car je n'ais pas envie que mon ip public soie visible

**Comment by ezbik** [comment]
@Soowarez kindly contact me by the website in my profile.

**Comment by Soowarez** [comment]
> @Soowarez kindly contact me by the website in my profile.

By email?
