### ISSUE TITLE
3proxy under high traffic and unstable Server

### ISSUE THREAD

**Issue by 0xff1f** [3proxy/3proxy#766]
Hello Folks ,

3proxy -v
Usage: 3proxy [conffile]

 if conffile is missing, configuration is expected from stdin

3proxy tiny proxy server 3proxy-0.8.9 (170202011430)
(c)3APA3A, Vladimir Dubrovin & 3proxy.ru
Documentation and sources: http://3proxy.ru/
Please read license agreement in 'copying' file.
You may not use this program without accepting license agreement

 cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)

uname -a 
Linux Spentaz.io 4.9.7 #1 SMP Sun Oct 4 13:30:11 -05 2020 x86_64 x86_64 x86_64 GNU/Linux

i have 255 proxies in one session .
as below config file :

###################################################
daemon
nscache 65536
nserver 8.8.8.8
nserver 8.8.4.4
maxconn 256
log /var/log/3proxy/Sxtfir.log D
rotate 60
#######################################################
auth strong
deny * * 127.0.0.1
allow *
flush
stacksize 6000
auth strong
#######################################################
##UsersListStart
users 4319264447:CL:2611407933
allow 4319264447
##UsersAllowedEnd
socks -4 -n -a -p5512 -i12.13.16.247 -e23.2.22.1
socks -4 -n -a -p5513 -i12.13.16.247 -e23.2.22.2
socks -4 -n -a -p5514 -i12.13.16.247 -e23.2.22.3
socks -4 -n -a -p5515 -i12.13.16.247 -e23.2.22.4
socks -4 -n -a -p5516 -i12.13.16.247 -e23.2.22.5
socks -4 -n -a -p5517 -i12.13.16.247 -e23.2.22.6
socks -4 -n -a -p5518 -i12.13.16.247 -e23.2.22.7
socks -4 -n -a -p5519 -i12.13.16.247 -e23.2.22.8
socks -4 -n -a -p5520 -i12.13.16.247 -e23.2.22.9
socks -4 -n -a -p5521 -i12.13.16.247 -e23.2.22.10
socks -4 -n -a -p5522 -i12.13.16.247 -e23.12.22.11
socks -4 -n -a -p5523 -i12.13.16.247 -e23.12.22.12
socks -4 -n -a -p5524 -i12.13.16.247 -e23.12.22.13
socks -4 -n -a -p5525 -i12.13.16.247 -e23.12.22.14
socks -4 -n -a -p5526 -i12.13.16.247 -e23.12.22.15
socks -4 -n -a -p5527 -i12.13.16.247 -e23.12.22.16
socks -4 -n -a -p5528 -i12.13.16.247 -e23.12.22.17
socks -4 -n -a -p5529 -i12.13.16.247 -e23.12.22.18
socks -4 -n -a -p5530 -i12.13.16.247 -e23.12.22.19
socks -4 -n -a -p5531 -i12.13.16.247 -e23.12.22.20
socks -4 -n -a -p5532 -i12.13.16.247 -e23.12.22.21
.
.
..
Up to 255 ips 
######################################

I have in kernel logs:

[439142.186206] TCP: request_sock_TCP: Possible SYN flooding on port 8442. Dropping request.  Check SNMP counters.
[439159.835354] TCP: request_sock_TCP: Possible SYN flooding on port 5157. Dropping request.  Check SNMP counters.
[439177.826076] TCP: request_sock_TCP: Possible SYN flooding on port 8824. Dropping request.  Check SNMP counters.
[439229.666735] TCP: request_sock_TCP: Possible SYN flooding on port 5196. Dropping request.  Check SNMP counters.
[439281.092282] TCP: request_sock_TCP: Possible SYN flooding on port 5014. Dropping request.  Check SNMP counters.
[439290.735638] TCP: request_sock_TCP: Possible SYN flooding on port 7180. Dropping request.  Check SNMP counters.
[439303.327926] TCP: request_sock_TCP: Possible SYN flooding on port 6047. Dropping request.  Check SNMP counters.
[439346.632819] TCP: request_sock_TCP: Possible SYN flooding on port 5373. Dropping request.  Check SNMP counters.
[439367.022858] TCP: request_sock_TCP: Possible SYN flooding on port 5584. Dropping request.  Check SNMP counters.

i followed most docs online to increase kernel sysctl but i have no luck .
https://access.redhat.com/solutions/30453

the issue i have is the server is very slow once the 3proxy session take and handle traffic .

My 3proxy handle about 3 Gbps traffic BW , i confirm no slowness in the network , but if i do top/htop or netstat or ps aux ... all those commands are slow .

Im not sure what is best i can do for 3proxy for high traffic usage .

is there any option like "Workers" in 3proxy to stabilize it ?

Looking to hear from you .

Thanks

**Comment by z3APA3A** [comment]
Try to start with
https://3proxy.ru/highload.asp
3proxy creates thread ("worker") for every connection, so it's already high.
Under high load you may try 0.9, there is a chance you get some improvement, and in some cases it may be impressive.

Next, identify the bottleneck (CPU? interrupts? bus? network? processes?)

If you use VPS - do not expect high load at all, because VPS usually do not provide any guaranteed resources. E.g. if you have 2GHz VPS it just means the host has a 2GHz core, but this core is not yours 100% of time. The actual amount of time you have this CPU is never visible, so 100% CPU usage within VPS does not mean you work at 2GHz. You may actually have only 0.2GHz at average or even less if CPU is assigned to your virtual host 10% of time. You can try to measure actual performance with some test.

**Comment by 0xff1f** [comment]
Hello Vladimir ,
Thank you for your reply .

I used 3proxy 0.9 version but it was unstable on centos , the only one that did not crash was .0.8.x so i stuck with it .

we have a sever R820  96 cores 4x of 2.7 Ghz CPU , CPU load is 30 %  only 
Ram free is 300 G.


if i use top to watch the CPU i see the cpu for the 3proxy session as 9600 % which mean its 100 x96 cores of my server .
i confirm the network traffic is normal , but the server is very very slow if i make like ls , or ss -s , or netsstat -x | grep 


So its like networking stack is fast but the Server itself is very slow .

I dont know where should i start to check .
FYI , my logs is full of :
[439142.186206] TCP: request_sock_TCP: Possible SYN flooding on port 8442. Dropping request. Check SNMP counters.
[439159.835354] TCP: request_sock_TCP: Possible SYN flooding on port 5157. Dropping request. Check SNMP counters.
[439177.826076] TCP: request_sock_TCP: Possible SYN flooding on port 8824. Dropping request. Check SNMP counters.
[439229.666735] TCP: request_sock_TCP: Possible SYN flooding on port 5196. Dropping request. Check SNMP counters.


As 3proxy is being hit with huge traffic around 3Gbps .

Is there anything we can build 3proxy with ?
is seperating conf file to several smaller files will help ?

is there speciifc config i can use for my case ?

Thanks

**Comment by z3APA3A** [comment]
If 0.9 crashes try to remove 'stacksize' command. stacksize is dangerous command and should only be used with reason.

**Comment by z3APA3A** [comment]
can you describe the traffic you have through the proxy? E.g. you have N connections with average X bps incoming and Y bps outgoing traffic each, connection live for T seconds in average?

**Comment by 0xff1f** [comment]
i really not able to measure bec the sever is very very very slow to respond me to ss or netstat .
but the server has 10 sessions , each session has 255 ips .
total in/out traffic is 3.5/3.5 Gbps .


top/htop/iftop ---> all those are slow and barely work .

the thing that make me feel strange is , the network is stable , but the server local services like top/htop is very slow .

im not sure if i need to  redesgin 3proxy or recompile it with specific tags .

i can provide you access to the server in production if needed .

Thanks

**Comment by 0xff1f** [comment]
during compilation i saw :
-DFD_SETSIZE=4096

does increasing this value to 2x or 5x can make sense ?

**Comment by z3APA3A** [comment]
FD_SETSIZE is not used on Linux, 3proxy uses poll() instead of select() where available.

**Comment by 0xff1f** [comment]
Thank you for your reply ,
How about my questions,

////////
i really not able to measure bec the sever is very very very slow to respond me to ss or netstat .
but the server has 10 sessions , each session has 255 ips .
total in/out traffic is 3.5/3.5 Gbps .

top/htop/iftop ---> all those are slow and barely work .

the thing that make me feel strange is , the network is stable , but the server local services like top/htop is very slow .

im not sure if i need to redesgin 3proxy or recompile it with specific tags .

i can provide you access to the server in production if needed .

//////


Thanks

**Comment by 0xff1f** [comment]
Do you think we can do anything or may be kernel change ?
Looking to hear from you .

**Comment by z3APA3A** [comment]
0.8.9 is not supported. Have you tried with 0.9.4? Can you characteristics of your tarffic in addition to bps? RPS, PPS, number of parallel connections (or average connection lifetime)?

**Comment by z3APA3A** [comment]
and what do you have in log?

**Comment by z3APA3A** [comment]
3proxy uses 1 connection <-> 1 thread model. This model is not the best one for high loads and creates a lot of threads (sometime shown as processes). It can make some utilities which enumerate threads/process to run slow due to large list. All commands you mentioned may deal with a list of processes.
