### ISSUE TITLE
more than one nserver in included file

### ISSUE THREAD

**Issue by basinilya** [3proxy/3proxy#767]
My network script generates two files for the current wi-fi AP:
`3proxy-external.inc: external 192.168.2.225`
`3proxy-external-dns.inc: nserver 192.168.2.1`

They're included in the main config:
```
flush
auth iponly
allow *
#nserver 192.168.2.1
$"C:\keep\3proxy-external-dns.inc"
#external 192.168.2.225
$"C:\keep\3proxy-external.inc"
proxy -i127.0.0.1 -p3127
```

Some access points provide two DNS servers. When I try to put both in a single included file 3proxy fails with `Unknown command: 'nserver' line 21`

If instead I try to generate and include an extra file for the second DNS then when it's empty 3proxy fails with: 
```
C:\keep\3proxy-external-dns2.inc: No error
Parse error line 22```

**Comment by z3APA3A** [comment]
Use `include` command rather than inline $ macro.
