### ISSUE TITLE
bandwidth counters are reset at restart

### ISSUE THREAD

**Issue by ezbik** [3proxy/3proxy#768]
### Conf file

```
auth strong
allow *
proxy -p8082
flush
users alice:CL:alice
counter "/var/lib/3proxy/counter/3proxy.counter"
countin  1002/in_alice         M 5  alice
countout 1003/out_alice        M 5  alice
```

So the user **alice** has 5MB monthly quota.

### Testing script:

```

_test_dl() {
curl -x localhost:8082  -U alice:alice  https://pathos.tanatos.org/file10m.txt -m10 -Ss -o - |pv > /dev/null;
}

    systemctl stop  3proxy ; rm /var/lib/3proxy/counter/3proxy.counter ;

    for i in 1 2 3 ; do
    echo =test attempt $i
            systemctl restart 3proxy ; sleep 3; _test_dl
    done

```

So 3 times in a row , download a 10MB file via https.

### Output:

```
=test attempt 1
curl: (18) transfer closed with 5275648 bytes remaining to read                                                          ]
4.97MiB 0:00:06 [ 807KiB/s] [            <=>                                                                             ]
=test attempt 2
curl: (18) transfer closed with 5275648 bytes remaining to read                                                          ]
4.97MiB 0:00:06 [ 777KiB/s] [            <=>                                                                             ]
=test attempt 3
curl: (18) transfer closed with 5275648 bytes remaining to read                                                          ]
4.97MiB 0:00:06 [ 800KiB/s] [            <=>                                   
```

### Expected result
 1st run downloads 5MB, 2nd and 3rd requests are dropped.

### Actual result
 1,2,3 requests download each 5MB

**Comment by ezbik** [comment]
My theory is that because the counter is so fresh, it is not get written to disk after restarts. But I am seeing the updated counter in webadmin /C page. I am out of ideas.

**Comment by z3APA3A** [comment]
counter must be configured before `proxy`. proxy should be the last command in your config.

**Comment by ezbik** [comment]
Now my config is  ( I moved counters to the top). The issue persisted. It downloads 5MB three times.
3proxy-0.9.4

```
counter "/var/lib/3proxy/counter/3proxy.counter"
countin  21002/in_alice         M 5  alice
countout 21003/out_alice        M 5  alice

auth strong
allow alice
users alice:CL:alice
proxy -p8082

```

**Comment by z3APA3A** [comment]
have you restarted the proxy with new config?

**Comment by ezbik** [comment]
Yes, my testing script contains restart.  Pseudocode is

stop 3proxy ; del counter; 
then 3 times:  restart &  download 10MB

so each of attempts downloads 5MB.

**Comment by z3APA3A** [comment]
How do you run and restart 3proxy? Under default Linux configuration 3proxy runs in chroot, and counter file must be located within chroot, path in configuration file must be relative (default config contains valid example). Also, counter file is updated once in the minute, if you do something like kill -9 on restart it may not be updated.

**Comment by ezbik** [comment]
`counter file is updated once in the minute,`

Oh it is the answer. I added delays between attempts, the bug disappeared. Thank you.
