### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by vuongtungan** [3proxy/3proxy#770]
I have run 3proxy --install in the 3proxy directory but it has some error 
![image](https://user-images.githubusercontent.com/36131573/165203176-85a030b1-cbe2-475c-b0e0-ee0f0b9031c1.png)
Can anyone tells me how to fix this?

**Comment by Justpenz233** [comment]
The same issue, did u fix this?

**Comment by z3APA3A** [comment]
Run cmd.exe as administrator.
