### ISSUE TITLE
Use remote proxy as child proxy

### ISSUE THREAD

**Issue by Demuss** [3proxy/3proxy#772]
Hello

I'm newbie :D 

It is possible, to use 3proxy server as main server and second as child server (using 3proxy or other server), using user and password. Or i'm asking to much?

main -i1.2.3.4  users main:CL:3gproxy
remote1 1.1.1.1:8000   users test1:CL:3gproxy
remote2 2.2.2.2:8000   users test2:CL:3gproxy
remote3 3.3.3.3:8000  users test3:CL:3gproxy

**example** 

main 1.2.3.4:5000 <--> remote1 1.1.1.1:8000
main 1.2.3.4:6000 <--> remote2 2.2.2.2:8000
main 1.2.3.4:7000 <--> remote3 3.3.3.3:8000

Thank you

**Comment by z3APA3A** [comment]
Probably, you mean parent proxy. See `parent` command description.

**Comment by Demuss** [comment]
Probably, I didn't find any examples
Thank you

**Comment by z3APA3A** [comment]
Try to strart with [HowTo](https://3proxy.ru/howtoe.asp#REDIR), [manuals](https://3proxy.ru/doc/man3/3proxy.cfg.3.html) are also useful.
