### ISSUE TITLE
Dynamically define user and pass for parent proxy

### ISSUE THREAD

**Issue by jameshooddisc** [3proxy/3proxy#773]
There is a way to define dynamically the user and pass for the parent proxy, instead of having it hardcoded in the config file?

**Comment by simonsww** [comment]
It's a good question , i also wanna know

**Comment by z3APA3A** [comment]
You can use * as username and password,  in this case authentication data is passed to parent proxy.

**Comment by jameshooddisc** [comment]
But this means i need to create in 3proxy level the same username/pass of the parent proxy, or i can leave the 3proxy unauthenticated and it will forward the credentials anyway?

Thanks

**Comment by z3APA3A** [comment]
yes, you can use e.g. auth iponly in 3proxy to let parent proxy to check username/password.

**Comment by jameshooddisc** [comment]
I'm trying with:

auth iponly
allow * * * 443,8443 HTTPS
parent 1000 http parent_host parent_port * *

But i'm still getting denied by 3proxy:

< HTTP/1.0 407 Proxy Authentication Required
< Proxy-Authenticate: Basic realm="proxy"
< Proxy-Connection: close
< Content-type: text/html; charset=us-ascii

I'm calling it from localhost with command:

curl -i -vv -k -x localhost:23456 -U "user:pass" "https://ipinfo.io/?aaa=bbb" // also with http.

Do you know what im doing incorrectly?

Thanks

**Comment by z3APA3A** [comment]
What do you have in log?

**Comment by z3APA3A** [comment]
try to user `auth useronly`

**Comment by jameshooddisc** [comment]
The thing is that the username i pass to parent is dynamic, every time different, with useronly i need to have a fixed username?

**Comment by z3APA3A** [comment]
No, it only requires username to present in the request.

**Comment by jameshooddisc** [comment]
Oh, now worked, thanks a lot!

Another question:

- I need to find a way to exclude some file extensions to go through the parent, both in HTTP and HTTPS, is something that can be done with a combination of 3proxy SSL/TLS plugin and PCREPlugin ?

Are both plugins available in the CentOS distributed package?

Thanks

**Comment by z3APA3A** [comment]
Yes, you can do it with SSLPlugin + PCREPlugin. I'm not sure what is distributed with CentOS, rpm package provided by 3proxy contains both.

**Comment by jameshooddisc** [comment]
Super, let me explore.

Which would be the config line in linux?

plugin /path/to/SslPlugin.dll ssl_plugin

Could not find anywhere in the docs.

**Comment by jameshooddisc** [comment]
Hi,

I'm trying to load the config with SSLPlugin and i'm getting this error:

May 18 12:45:13 host 3proxy[119952]: Command: 'plugin' failed with code 1, line 20
May 18 12:45:13 host 3proxy[119952]: Command: 'include' failed with code 20, line 20

My config for this part is:

plugin /libexec/SSLPlugin.ld.so ssl_plugin
ssl_certcache /certs/
ssl_mitm

And all i did was to change Makefile as follows:

LIBS = -lcrypto -lssl -ldl 
#LIBS = -ldl 
PLUGINS = SSLPlugin StringsPlugin TrafficPlugin PCREPlugin TransparentPlugin PamAuth
#PLUGINS = StringsPlugin TrafficPlugin PCREPlugin TransparentPlugin

And install pam-devel.

What i'm doing wrong?

Thanks

**Comment by z3APA3A** [comment]
If you run 3proxy within chroot (default install creates chroot environment), make sure plugin library is available within chroot, in any way check proxy account has execution permissions.

**Comment by jameshooddisc** [comment]
I think it is:

#!/bin/3proxy
#daemon
pidfile /var/run/3proxy/3proxy.pid
chroot /usr/local/3proxy proxy proxy
include /conf/3proxy.cfg

[root@host 3proxy]# pwd
/usr/local/3proxy
[root@host 3proxy]# ls -la
total 4
dr-xr-x---   7 proxy proxy   66 May 18 12:37 .
drwxr-xr-x. 13 root  root  4096 May 18 12:19 ..
drwxr-xr-x   2 proxy proxy   98 May 18 12:42 certs
dr-xr-x---   2 proxy proxy   93 May 18 14:21 conf
drwxr-x---   2 proxy proxy    6 May 18 12:19 count
dr-xr-x---   2 proxy proxy  153 May 18 12:35 libexec
drwxr-x---   2 proxy proxy   30 May 18 12:30 logs
[root@host 3proxy]# ls -la libexec/
total 192
dr-xr-x--- 2 proxy proxy    153 May 18 12:35 .
dr-xr-x--- 7 proxy proxy     66 May 18 12:37 ..
-r-xr-xr-x 1 proxy proxy 125512 May 18 12:35 PCREPlugin.ld.so
-r-xr-xr-x 1 proxy proxy  23376 May 18 12:35 SSLPlugin.ld.so
-r-xr-xr-x 1 proxy proxy  10272 May 18 12:35 StringsPlugin.ld.so
-r-xr-xr-x 1 proxy proxy  10232 May 18 12:35 TrafficPlugin.ld.so
-r-xr-xr-x 1 proxy proxy   6344 May 18 12:35 TransparentPlugin.ld.so
-r-xr-xr-x 1 proxy proxy  10256 May 18 12:35 pamauth.ld.so

Do you see something incorrect?

**Comment by jameshooddisc** [comment]
I found it, about permissions. basically i removed all chroot thing, to continue my testing.

Next problem:

IF i run a curl against the proxy in HTTPS, the proxy only arrives to the CONNECT, but is not forwarding the GET part. Is something im missing here?

CURL:
curl -i -vv -k -x localhost:23456 -U "user:pass" "https://ipinfo.io/"

3proxy Log:
220518124314.578 23456 00000 user 127.0.0.1:14145 parent_host:parent_port 251 19 1 CONNECT ipinfo.io:443 HTTP/1.1

My cURL only receives the CONNECT back, but not the HTTP GET.

Thanks

**Comment by z3APA3A** [comment]
See https://3proxy.org/plugins/SSLPlugin/
you need
ssl_certcache /path/to/cache/
ssl_mitm

ssl_certcache - path to certificates cache. For transparent spoofing cache must contain 3 files: 3proxy.pem - public self-signed certificates, 3proxy.key - key for public certificates, server.key - this key will be used to generates spoofed certificates. Generated certificates will be placed to the same path. 

server.key and 3proxy.key can actually be the same. Client must trust to 3proxy.pem as a root CA.

**Comment by jameshooddisc** [comment]
Yes, i have the 3 files inside the directory, and also both commands in the config.

In fact, i'm receiving the CONNECT perfectly, but there is no HTTP GET after it:

< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< 

* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=ipinfo.io
*       start date: Apr 23 01:09:02 2022 GMT
*       expire date: Jul 22 01:09:01 2022 GMT
*       common name: ipinfo.io
*       issuer: CN=XX,O=XX,ST=XX,C=XX
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: ipinfo.io
> Accept: */*

My config seems like:

plugin /usr/local/3proxy/libexec/SSLPlugin.ld.so ssl_plugin
ssl_certcache /usr/local/3proxy/certs/
ssl_mitm

auth useronly
allow * 127.0.0.1 * * * * *
parent 1000 http host port * *

AND Log file:

220518125528.522 23456 00033 user 127.0.0.1:9494 host:port 0 341 1 CONNECT ipinfo.io:443 HTTP/1.1

Thanks

**Comment by z3APA3A** [comment]
Does it work without parent proxy?

**Comment by z3APA3A** [comment]
Try
allow * 127.0.0.1 * 80
parent 1000 http host port * *
allow * 127.0.0.1 * 443
parent 1000 connect+ host port * *

**Comment by jameshooddisc** [comment]
Is very strange, i got 3 different results:

One got stucked in CONNECT.
220518135216.848 23456 00000 user 127.0.0.1:22362 host:port 251 19 1 CONNECT ipinfo.io:443 HTTP/1.1

One got 502 Bad Gateway.
220518135218.669 23456 00033 user 127.0.0.1:22572 host:port 0 341 1 CONNECT ipinfo.io:443 HTTP/1.1

One was correct, did CONNECT and i received the response JSON correctly.
220518135221.036 23456 00000 user 127.0.0.1:22776 host:port 251 19 1 CONNECT ipinfo.io:443 HTTP/1.1

Why do you think this can be happening?

**Comment by z3APA3A** [comment]
which configuration was active for every request?
http parent may work incorrectly with SSL stripping, because proxy thinks it works via parent HTTP proxy and HTTP operations are different with HTTP proxy, use connect+

**Comment by jameshooddisc** [comment]
I tested with both following configs, and results were same results then my previous post:

===================
plugin /usr/local/3proxy/libexec/SSLPlugin.ld.so ssl_plugin
ssl_certcache /usr/local/3proxy/certs/
ssl_mitm

auth useronly

// one time this
allow * 127.0.0.1 * 80
parent 1000 http host port * *
allow * 127.0.0.1 * 443
parent 1000 connect+ host port * *

// other time this
allow * 127.0.0.1 * 80,443
parent 1000 connect+ host port * *

proxy -n -p23456
=====================

But the problem is see, is that ALWAYS goes first to parent before analyzing the request, there is no way to analyze the request first and then decide what to do? Skip the parent VS going through parent?

Thanks

**Comment by jameshooddisc** [comment]
Sorry, can be that something is getting cached?

Because without parent in the config, and after restart the service, some requests try to go to the parent...

**Comment by z3APA3A** [comment]
Have you rebuilt both 3proxy and plugin?

**Comment by jameshooddisc** [comment]
Yes i do:

-rwxr-xr-x 1 root root 194744 May 18 17:32 /usr/bin/3proxy
-rwxr-xr-x 1 root root 194744 May 18 17:32 /bin/3proxy

And SSL code have the lines of your commit...

**Comment by z3APA3A** [comment]
Are 3proxy logs the same?

**Comment by z3APA3A** [comment]
Try current master with d20e76bbc9438c69de27b50c0886eaf47aefb40a, it should work

**Comment by jameshooddisc** [comment]
Tried but no luck yet.

I think i'm doing something incorrect, for more than 12h i have been without "parent" line, and 3proxy is still trying to stablish a tunnel with parent host...

There is any kind of cache or something? I checked and i'm loading correct config (because i changed log destination and writes to new file).

Also, sometimes gives me 502, sometimes goes through parent and got stucked on CONNECT, sometimes goes through parent and retrieve correct response, and sometimes goes directly.

Really really strange.

Thanks!

**Comment by z3APA3A** [comment]
```
plugin ./SSLPlugin.so ssl_plugin
ssl_certcache ./
ssl_mitm
proxy

```

 ```
./3proxy 3proxy.cfg 
220519084643.266 8080 00000 - 0.0.0.0:8080 0.0.0.0:0 0 0 0 Accepting connections [40808/133951488]
220519084643.465 3128 00000 - 0.0.0.0:0 0.0.0.0:0 0 0 0 Accepting connections [40808/134029312]
220519084650.641 3128 00000 - 127.0.0.1:58153 142.250.74.46:443 127 703 0 GET http://google.com/ HTTP/1.1

```
 ```
curl -k -x127.0.0.1:3128 https://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>

```

**Comment by z3APA3A** [comment]
Check you _really_ updated both 3proxy and SSLPlugin.so binaries used.

**Comment by z3APA3A** [comment]
And I checked it works with parent connect+

```
log
proxy -i127.0.0.1 -p12345
auth iponly
allow *
parent 1000 connect+ 127.0.0.1 12345
plugin ./SSLPlugin.so ssl_plugin
ssl_certcache ./
ssl_mitm
proxy

```

```
/3proxy 3proxy.cfg 
220519094220.788 12345 00000 - 127.0.0.1:12345 0.0.0.0:0 0 0 0 Accepting connections [43883/230330368]
220519094220.792 3128 00000 - 0.0.0.0:0 0.0.0.0:0 0 0 0 Accepting connections [43883/230408192]
220519094222.854 3128 00000 - 127.0.0.1:59410 127.0.0.1:12345 127 801 1 GET http://google.com/ HTTP/1.1
220519094222.855 12345 00000 - 127.0.0.1:59411 142.250.74.46:443 541 7969 0 CONNECT google.com:443 HTTP/1.0
```

**Comment by jameshooddisc** [comment]
Yes, it works now!!!!!!!!!

I cleaned everything and compile and start again and now is working both HTTP and HTTPS.

May i ask you last thing, if i want to have 2 parents, one for dynamic files and one for static files, how i can do with PCREPlugin?

Should be something like:

```
plugin /usr/local/3proxy/libexec/SSLPlugin.ld.so ssl_plugin
ssl_certcache /usr/local/3proxy/certs/
ssl_mitm


plugin /usr/local/3proxy/libexec/PCREPlugin.ld.so pcre_plugin

auth useronly
allow * 127.0.0.1 * 80,443


pcre request allow "\.gif|\.png"
parent 1000 connect+ host1 port1 * * //parent1 static

pcre request deny "\.gif|\.png"
parent 1000 connect+ host2 port2 * * //parent2 dynamic


proxy -n -p23456
```


Thanks a lot!!!!!!

**Comment by z3APA3A** [comment]
it's currently impossible, connection is established and SSL is handshaked with both client and server on CONNECT request, before HTTP request is ever sent.

**Comment by jameshooddisc** [comment]
So my use case about analyzing the request (both http and https), and depending on the URL (path and filename), sending to one parent or other, is impossible?

And if instead of 2 parents, i use 1 parent and other option skip the parent?

Thanks

**Comment by z3APA3A** [comment]
if you control clients you can use WPAD or proxy auto configuration file (PAC) to instruct client to use e.g. different proxy ports.

**Comment by jameshooddisc** [comment]
Thats a good idea, i will check, thanks a lot!!!!!!!!!!!

**Comment by jameshooddisc** [comment]
Btw, can i get one email to contact you? Or please drop me a line in james.hood.disc@protonmail.com

Thanks!

**Comment by z3APA3A** [comment]
contact to z3apa3a@gmail.com
