### ISSUE TITLE
Не могу подключить SSL PLUGIN

### ISSUE THREAD

**Issue by serton952** [3proxy/3proxy#777]
Написал конфиг, в итоге прокси не работают.
Без подключения SSL всё в порядке, скорее всего где-то ошибся при добавлении плагина.
Помогите пожалуйста, ниже представлен неработающий код

```
monitor C:\3proxy\bin64\monitor.txt
nscache 65536
timeouts 1 5 30 60 180 1800 15 60

auth strong
users login:CL:password
allow login

plugin C:\3proxy\bin64\SslPlugin.dll ssl_plugin
ssl_certcache C:\3proxy\bin64\cache\
ssl_mitm
proxy -n -a -p1080 -i192.168.1.126 -e192.168.6.178
proxy -n -a -p1082 -i192.168.1.126 -e192.168.228.178
proxy -n -a -p1084 -i192.168.1.126 -e192.168.2.178
proxy -n -a -p1086 -i192.168.1.126 -e192.168.12.179
proxy -n -a -p1088 -i192.168.1.126 -e192.168.9.178
flush
```

Еще чуть ниже работающий код

```
monitor C:\3proxy\bin64\3proxy.cfg
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
auth strong
users login:CL:password
allow login
proxy -n -a -p1080 -i192.168.1.126 -e192.168.6.178
socks -n -a -p1081 -i192.168.1.126 -e192.168.6.178
proxy -n -a -p1082 -i192.168.1.126 -e192.168.228.178
socks -n -a -p1083 -i192.168.1.126 -e192.168.228.178
proxy -n -a -p1084 -i192.168.1.126 -e192.168.2.178
socks -n -a -p1085 -i192.168.1.126 -e192.168.2.178
proxy -n -a -p1086 -i192.168.1.126 -e192.168.12.179
socks -n -a -p1087 -i192.168.1.126 -e192.168.12.179
proxy -n -a -p1088 -i192.168.1.126 -e192.168.9.178
socks -n -a -p1089 -i192.168.1.126 -e192.168.9.178
flush
```

**Comment by Bolshaksa** [comment]
Добрый день!

Присоединяюсь к вопросу.
В мануале по плагину указана маска пути для плагина и сертификата:

plugin /path/to/SslPlugin.dll ssl_plugin
ssl_certcache /path/to/cache/

Но в папке с плагином нет ни одного dll файла. Там следующие файлы:
Makefile  Makefile.inc  my_ssl.c  my_ssl.h  ssl_plugin.c
До какого указывать путь командой plugin?

ssl_certcache предопределенная папка (уже создана где то) или ее можно создать в любом месте внутри папки 3proxy?
Сертификаты генерируются плагином или нужно сгенерировать вручную?

**Comment by z3APA3A** [comment]
обсуждается в https://github.com/3proxy/3proxy/issues/561

@Bolshaksa DLL файлы лежат в директории с бинарными файлами, там же где 3proxy.exe, а не с исходным кодом
