### ISSUE TITLE
Не работает в хроме macos через proxifier

### ISSUE THREAD

**Issue by mardoksp** [3proxy/3proxy#779]
Привет.

Такая возникла проблема. Есть комп с 3proxy (win 10). Есть виртуалка с macos.

На виртуалке macos стоит proxifier -> socks5 -> 3proxy

Самое интересное, что не работает на macos только chrome, при открытии страниц ошибка - ERR_EMPTY_RESPONSE

В safari работает все отлично.

Вот в логах proxifier (открывал 1 сайт в хроме, а потом в сафари)

![image](https://user-images.githubusercontent.com/17234306/171701777-898ec259-0ab9-48ca-9269-88fd42a84675.png)

Конфиг 3proxy

```
service

nserver 8.8.8.8
nscache 65536
timeouts 1 5 30 60 180 1800 15 60

maxconn 100000

socks -n -a -p50001 -i192.168.1.11 -e192.168.9.100
```

Лог 3proxy
![image](https://user-images.githubusercontent.com/17234306/171701852-b645ecf5-d911-42e7-8e70-56f54266bffb.png)

С хром не возвращается ничего, а с сафари работает без проблем. 
Никаких настроек не сделано на macos, все с чистого листа.

**Comment by mardoksp** [comment]
Как вариант решения вместо proxifier на mac os настроил все через Tun2Socks.
Хром работает.

**Comment by z3APA3A** [comment]
Проксификатор обычно перехватывает обращение к определенным библиотечным функциям, скорей всего что-то недоперехватили, лучше такое поведение зарепортить авторам проксификатора. В прокси приходит запрос CONNECT 0.0.0.0.

**Comment by mardoksp** [comment]
> 

Возможно, но очень странно, так как другую виртуалку раньше настраивал через CCProxy и хром работал без проблем.
Но думаю, через tun2socks -> 3proxy лучше вариант :)

**Comment by z3APA3A** [comment]
Ну в любом случае прокси ничего не может сделать с запросом CONNECT 0.0.0.0
Возможно у тебя в виртуалке не работает разрешение имен и не включена опция в соксификаторе разрешать имена через прокси
