### ISSUE TITLE
Detected OS TCP/IP Fingerprint

### ISSUE THREAD

**Issue by Boris991420** [3proxy/3proxy#780]
Здравствуйте. Видел у одного пользователя такой конфиг
proxy -p40204 -sw10 -a -n -i192.168.88.18 -e172.16.0.100
proxy -p40205 -si14 -a -n -i192.168.88.18 -e172.16.0.100
proxy -p40206 -sa12 -a -n -i192.168.88.18 -e172.16.0.100

Соответственно каждый порт подставляет нужную сигнатуру
Windows
iOs
Android

Это реализовано у Вас в стандартном решении или нужны доработки?
Возможно Вам будет интересно и Вы это реализуете.

**Comment by z3APA3A** [comment]
У 3proxy нет таких опций
