### ISSUE TITLE
Plugin Log File

### ISSUE THREAD

**Issue by automators1** [3proxy/3proxy#781]
How can I see the printf or fprintf of my plugin during production env?
3proxy provide an output file or I need to handle on my own way ?

Thx

**Comment by z3APA3A** [comment]
you can use pl->logfunc(param, "somestring") for 3proxy logging or output something to file or stderr/stdout.  The way you can see stdout/stderr depends on your environment, you can not see stdout/stderr if you run 3proxy detached (with 'daemon' in config) or as a service.
