### ISSUE TITLE
ipv6 tunnel

### ISSUE THREAD

**Issue by b5414** [3proxy/3proxy#784]
Привет;

Я пытаюсь настроить несколько ipv6 туннелей(пока только один), вот мой конфиг

```py
# daemon
maxconn 20
nserver 8.8.8.8
nserver 8.8.4.4
nserver 1.1.1.1
nscache 65536
nscache6 65536
timeouts 1 5 30 60 180 1800 15 60
stacksize 6000

auth none
# auth strong
users admin:CL:pass

flush
log

proxy -6 -s0 -a -p27017 -i127.0.0.1 -ea72b:109b:04a0:b377:de9f:1e26:d9e0:74fe
```

С браузера где я захожу на этот прокси6 я получаю ошибку туннеля `ERR_TUNNEL_CONNECTION_FAILED`, открываю www.google.com

логи/poweshell:
```js
PS F:\3proxy\bin64> ./3proxy.exe  .\3proxy.cfg
220617191015.512 27017 00000 - 127.0.0.1:27017 a72b:109b:4a0:b377:de9f:1e26:d9e0:74fe:0 0 0 0 Accepting connections [1940/7008]
220617191020.156 27017 00012 - 127.0.0.1:65203 2a00:1450:4010:c05::54:443 0 0 0 CONNECT accounts.google.com:443 HTTP/1.1
220617191021.052 27017 00012 - 127.0.0.1:65204 2a00:1450:4010:c05::54:443 0 0 0 CONNECT accounts.google.com:443 HTTP/1.1
220617191023.622 27017 00012 - 127.0.0.1:65206 2a00:1450:4010:c05::54:443 0 0 0 CONNECT accounts.google.com:443 HTTP/1.1
220617191025.831 27017 00012 - 127.0.0.1:65207 2a00:1450:4010:c08::68:443 0 0 0 CONNECT www.google.com:443 HTTP/1.1
220617191029.125 27017 00012 - 127.0.0.1:65208 2a00:1450:4010:c08::68:443 0 0 0 CONNECT www.google.com:443 HTTP/1.1
220617191029.127 27017 00012 - 127.0.0.1:65209 2a00:1450:4010:c08::68:443 0 0 0 CONNECT www.google.com:443 HTTP/1.1
```

1. Что я делаю не так? 🙂
2. Возможно ли получить разный ип6, и как?

**Comment by Nothing4You** [comment]
https://3proxy.ru/howtoe.asp#ERRORS (https://3proxy.ru/howtor.asp#ERRORS in RU)

00012 -> 12 - failed to bind()

sounds like a72b:109b:04a0:b377:de9f:1e26:d9e0:74fe isn't available to bind to.
is that ip configured on your interface?
other than that, the config works for me if i replace it with my ipv6 address.

What do you  mean by getting a different ip6?

**Comment by b5414** [comment]
@Nothing4You I got this ip by randomizer...

I'm probably missing something important, but I want to get different ipv6 on the same device in order to use them as a proxy

**Comment by z3APA3A** [comment]
Чтобы использовать IPv6 адрес, тебе необходимо получить этот адрес от твоего провайдера (или от твоего маршрутизатора, или от туннельного брокера или от кого-то еще) и сконфигурировать его для внешнего интерфейса.
