### ISSUE TITLE
Get downloaded bytes from server

### ISSUE THREAD

**Issue by DRDLCN** [3proxy/3proxy#785]
Hi guys,

Is possible to retrieve the number of bytes passed through the proxy in and out, inside a plugin?
I see **unsigned bandlimitfunc(struct clientparam *param, unsigned nbytesin, unsigned nbytesout)** 
How can handle the **unsigned nbytesin, unsigned nbytesout** inside a plugin to make the internal calculation?

Where these parameters are passed to bandlimitfunc?

**Comment by z3APA3A** [comment]
param->statscli64 (client to proxy)
param->statssrv64 (server to proxy)
