### ISSUE TITLE
IP-адрес через имя интерфейса

### ISSUE THREAD

**Issue by dstd** [3proxy/3proxy#788]
Очень не хватает возможности указания имени интерфейса вместо IP – в командах internal/external и в правилах у extip.

Есть VPN который периодически переподключается, и клиенту выдаётся новый локальный IP. Из-за этого не получается реализовать стабильно работающий прокси.

У меня вот такой конфиг:
```
#!/usr/local/bin/3proxy

nserver 1.1.1.1
nscache 65536

auth iponly

allow * * *.facebook.com,facebook.com,*.fbcdn.net,fbcdn.net,*.instagram.com,instagram.com,*.cdninstagram.com,cdninstagram.com,play.google.com,*.twitter.com,twitter.com,*.twimg.com,twimg.com,*.branch.io,branch.io,api2.branch.io,*.syncfusion.com,syncfusion.com,*.t.co,t.co,*.inforesist.org,inforesist.org,*.threadreaderapp.com,threadreaderapp.com,*.cdnjs.cloudflare.com,cdnjs.cloudflare.com,*.saverudata.info,saverudata.info,support.google.com,*.windscribe.com,windscribe.com,*.googleapis.com,googleapis.com,whatismyipaddress.com,*.darnet.ru,darnet.ru,*.oculus.com,oculus.com
parent 1000 extip 10.241.180.208 0

allow *
#direct

proxy -p18888
```

Думал о макро-подстановке файла с адресом, но как-то костыльно получается, и придётся перезапускать 3proxy.

P.S. Сто лет не пользовался 3proxy, со времён когда мучал автора пока делал плагин для сохранения c Last.FM. Отрадно, что проект живой ^__^

**Comment by z3APA3A** [comment]
https://3proxy.ru/doc/man3/3proxy.cfg.3.html `-De` `-Di`, но надо понимать что биндинг по интерфейсу и IP это не одно и то же и они друг друга не заменяют.

**Comment by z3APA3A** [comment]
если надо биндиться именно к IP но обрабатывать смену адреса, то правильно делать ifup/ifdown скрипты которые будут генерировать конфиг и перезапускать прокси

**Comment by dstd** [comment]
К сожалению SO_BINDTODEVICE не на столько кроссплатформенная, в macOS её нет. У `curl` параметр `--interface` использует `getifaddrs` и `SIOCGIFADDR` если платформа не поддерживает опцию сокета.

А вариант с подстановкой IP и перезапуском 3proxy – все активные коннекты, которые идут напрямую, а не через этот VPN, всё-равно будут дропаться из-за перезапуска. Поэтому я от такого варианта отказался.

**Comment by z3APA3A** [comment]
Не будут, если просто конфигурацию обновлять (SIGUSR1) а не стопать прокси полностью.

**Comment by z3APA3A** [comment]
В c1beceb24b4a7a6b984c5f7ff5f251f83d03d869 сделал поддержку IP_BOUND_IF на MacOS, но не тестировал

**Comment by z3APA3A** [comment]
Нет, это так работать не будет, здесь во-первых течет память, во-вторых будут рейсы, т.к. srv используется одновременно всеми клиентами. Чтобы через parent'ы интерфейсы задавать, надо полностью отдельную логику делать, тут десятком строк не обойтись.
