### ISSUE TITLE
Using IPv6 with interface name?

### ISSUE THREAD

**Issue by ntit365** [3proxy/3proxy#789]
I have multiple PPPOE connection. I config proxy with -Depppoe-wan IPv4 working but when I add option -6 it not working. My config
proxy -n -p4001 -Depppoe-wan -a

**Comment by z3APA3A** [comment]
There should be no difference for SO_BINDTODEVICE between IPv4 and IPv6, but interface binding does not replace IP binding in all cases, check you bind to valid IPv6 address and you have IPv6 route via pppoe-wan interface.
