### ISSUE TITLE
3proxy suddenly crash

### ISSUE THREAD

**Issue by hunterhe23** [3proxy/3proxy#793]
version 0.9.4, qps 500, traffic 50Mbps, CPU 3%.
run for 6 months, then suddenly crashed without any manual changes.
the main process exists, but the port 3128/1080 is down.
no errors in /var/log/message.
how to troubleshooting?

**Comment by z3APA3A** [comment]
what do you mean by 'crashes'? Is the process running? If it really crashes, can you create crashdump?

**Comment by hunterhe23** [comment]
i mean 3proxy process is running, but proxy port 3128 and 1080 is down.
create crashdump?

**Comment by hunterhe23** [comment]
i am sure the config is correct, course it has been running normally for a long time.

**Comment by hunterhe23** [comment]
i didn't make any changes when proxy port is down.
and the load is very low, 3% cpu usage, 500 qps, 50Mbps.

**Comment by hunterhe23** [comment]
if config is wrong, there will be error log in /var/log/message. but there wasn't  in this case.

**Comment by hunterhe23** [comment]
what's the error log (not access log) path by default?

**Comment by z3APA3A** [comment]
the log is where you configured it, see `log` command. Startup errors may be logged to stderr.
