### ISSUE TITLE
Installing from deb on debian

### ISSUE THREAD

**Issue by llacqie** [3proxy/3proxy#800]
I think the problem is in the postinstall debian script

![image](https://user-images.githubusercontent.com/46074473/181587586-6b2c3bea-dade-448c-bf65-d27d31c916b4.png)

**Comment by llacqie** [comment]
![image](https://user-images.githubusercontent.com/46074473/181587910-6179a4a1-84ae-40e0-85e2-a27100e93440.png)

**Comment by llacqie** [comment]
also why is it trying to delete /usr/lib/systemd/system when uninstalling

![image](https://user-images.githubusercontent.com/46074473/181588867-bce081db-3b40-452e-93eb-44731258b151.png)

**Comment by z3APA3A** [comment]
3proxy does not explicitly remove any directories or stop any services, dpkg can do it on some reasons (e.g. these directories were created or services were started during 3proxy installation). I see no real problems here.
