### ISSUE TITLE
when use error user or password 3proxy return success in socks5. is it a issue?

### ISSUE THREAD

**Issue by hyz1021984053** [3proxy/3proxy#802]
I use this config to start 3proxy then use user:hyz password:123456780 to conenct but it return success
eg:
timeouts 1 5 30 60 180 1800 15 60

users **hyz:CL:12345678** hyz1:CL:1234567890

service

log /etc/3proxy/3proxy.log D

#logformat "- +_L%t.%.  %N.%p %E %U %C:%c %R:%r %O %I %h %T"

rotate 30

internal 192.168.200.55

auth strong
flush
allow hyz
socks -a -p1080

![image](https://user-images.githubusercontent.com/10987486/182098283-876fac05-d0c6-47cd-a3cf-d5728bd28a83.png)
![image](https://user-images.githubusercontent.com/10987486/182098397-709fd138-0700-4b69-b611-70436964f444.png)

**Comment by z3APA3A** [comment]
3proxy checks username/password later, upon destination request, it's required for compatibility with some authentication/authorization protocols, e.g. RADIUS.
