### ISSUE TITLE
How to send the username and password requested by the user to the parent

### ISSUE THREAD

**Issue by new008123** [3proxy/3proxy#803]
allow *
parent 1000 socks5 127.0.0.1 1234
parent 1000 socks5 1.1.1.1 1111
socks -p6665
proxy -p6666
flush

For example, the user connects to my proxy through the Firefox plug-in.
The user filled in the account password in the plug-in
127.0.0.1 6665 aaa bbb
How do I send "aaa" and "bbb" to 1.1.1.1 1111
"aaa" and "bbb" Is not fixed

**Comment by z3APA3A** [comment]
See https://3proxy.ru/doc/man3/3proxy.cfg.3.html.
>Optional username and password are used to authenticate on parent proxy. Username of ´*´ means username must be supplied by user.

```
fakeresolve
auth useronly
allow *
parent 1000 socks5+ 1.1.1.1 1111 * *
socks -p6665
proxy -p6666
```
