### ISSUE TITLE
3proxy + nextdns.io

### ISSUE THREAD

**Issue by tarampampam** [3proxy/3proxy#805]
Категорически приветствую!

Планирую подружить демона с nextdns и споткнулся на том, что в качестве резольвера dns нужно указывать IPv6 адрес - умеет ли это 3proxy? И стоит ли ждать поддержку DoH?

Много информации по nextdns можно найти тут - https://github.com/nextdns/nextdns/wiki

**Comment by z3APA3A** [comment]
IPv6 для DNS указывать можно, DoH клиент пока не в приоритете, все-таки DoH не предназначен для использования на серверах под существенной нагрузкой, если необходимо - правильней поставить локальный форвардер или делать нормальный VPN до резолвера. Как минмум, сначала будет поддержка TLS на входящих клиентских соединениях, без нее в DoH большого смысла нет.
