### ISSUE TITLE
Переадресация данных

### ISSUE THREAD

**Issue by wineSecure** [3proxy/3proxy#806]
Есть виртуальная машина (192.168.1.10), где раз в N секунд происходит ротация IP. Так же есть главный сервер (192.168.1.1), на котором размещено несколько таких ВМ. Я пытаюсь перенаправлять трафик по порту с главного сервера на виртуальную машину. Порт открывается, но подключение не происходит. В чем моя ошибка?

Настройка на виртуальной машине: 
```
proxy -p20000
```

Настройка на главном сервере:
```
tcppm -i0.0.0.0 10000 192.168.1.10 20000
```

**Comment by z3APA3A** [comment]
Добавь логгирование и посмотри, что происходит

**Comment by wineSecure** [comment]
Что ж, проблема была в том, что я не добавил в начало конфига `auth iponly` на главном сервере.
