### ISSUE TITLE
Outgoing problem Error code 00013

### ISSUE THREAD

**Issue by kamuran21** [3proxy/3proxy#810]
Hi, I am using a digitalocean droplet to use ipv6 subnet proxies.  when you enable ipv6 on digital ocean, it gives /124 subnet automaticaly. To add new ipv6 addresses out of range, you have to do it manually. 
I am adding new  sub ips like this
```
ip -6 addr add 2a08:14c0:100:200::2010/64 dev eth0
ip -6 addr add 2a08:14c0:100:200::2011/64 dev eth0
ip -6 addr add 2a08:14c0:100:200::2012/64 dev eth0
```
Proxy confs :
```
proxy -6 -n -a -p10000 -e2a03:xxxx:3:d0::f84:2001 #digitalocean's ipv6
proxy -6 -n -a -p10001 -e2a03:xxxx:3:d0::f84:2020 #mynew sub ipv6
```

When I use digitalocean's subnet (which were prepared automatically), proxies working well. 
But when I use my new sub ips, it return 00013 error code. I couldn't figure it out :( 
Do you have any suggestion to resolve this issue. 
LOGS:
```
1661559132.719 PROXY.10000 00000 testuser 31.XXX.8.107:52817 2607:XXXX:4010:c::2:443 634 6573 0 CONNECT_api64.ipify.org:443_HTTP/1.1
1661559133.950 PROXY.10000 00000 testuser 31.XXX.8.107:53554 2607:XXXX:4010:c::2:443 634 6573 0 CONNECT_api64.ipify.org:443_HTTP/1.1
1661559134.424 PROXY.10000 00094 testuser 31.XXX.8.107:53463 2607:XXXX:4010:c::2:443 369 0 0 CONNECT_api64.ipify.org:443_HTTP/1.1
1661559254.611 PROXY.10001 00013 testuser 31.XXX.8.107:52951 2607:XXXX:4010:c::2:443 0 0 0 CONNECT_api64.ipify.org:443_HTTP/1.1
1661559254.611 PROXY.10001 00013 testuser 31.XXX.8.107:53573 2607:XXXX:4010:c::2:443 0 0 0 CONNECT_api64.ipify.org:443_HTTP/1.1
```

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtoe.asp#ERRORS

13 means proxy failed to connect to destination host, it's either routing or firewall issue. Probably address you assigned is not actually routed. You can try to ping destination host using this address as a source. If you fail to ping - you will not be able to connect either.
