### ISSUE TITLE
Feature request: Bind to outgoing network interface by name on Windows

### ISSUE THREAD

**Issue by Phasip** [3proxy/3proxy#811]
There seems to be an option '-DeINTERFACE' available in the documentation, however it does not seem to be available for Windows users.

It would be nice to have this

**Comment by z3APA3A** [comment]
There is no such thing as interface binding on Windows. It's possible to find interface IP address and bind to this IP, but it's not what -De option is supposed to do. In e.g. Linux IP binding and interface binding are independent operations and may be combined.
