### ISSUE TITLE
Add IPv4 Subnet/Range at once

### ISSUE THREAD

**Issue by psadev** [3proxy/3proxy#812]
Hello,

Would it be possible to add an entire subnet at once (ipv4)? Config files grow easily in size as more subnets are added to single servers and it would be useful to minimize that.

Instead of doing

```
proxy -p3000 -a -i1.1.1.0 -e1.1.1.0
proxy -p3000 -a -i1.1.1.1 -e1.1.1.1
proxy -p3000 -a -i1.1.1.2 -e1.1.1.2
proxy -p3000 -a -i1.1.1.3 -e1.1.1.3
... (the rest of the list)
proxy -p3000 -a -i1.1.1.254 -e1.1.1.254
```

Do something like

```
proxy -p3000 -a -r_start1.1.1.0 -r_end1.1.1.254
```

With r_start meaning range_start (r_end = range_end) so that you can manually choose which ip range to use.

**Comment by z3APA3A** [comment]
Large config is OK for 3proxy. You can write a script to generate config required from the syntax you suppose, I don't think it's actually required on 3proxy side.
