### ISSUE TITLE
0 0 0 pthread_create(): Resource temporarily unavailable

### ISSUE THREAD

**Issue by 0xff1f** [3proxy/3proxy#817]
Hello Team ,

i have an error under a heavy instances of 3proxy ;

0 0 0 pthread_create(): Resource temporarily unavailable

with stack size 6k or 11k its the same error .
May i know the possible reasons with 3proxy for the error above ?

Best regards

**Comment by z3APA3A** [comment]
It means you have reached some limit, probably memory or threads, check running threads/consumed memory and hard/soft ulimits and kernel limitations, see https://3proxy.ru/highload.asp
