### ISSUE TITLE
Авторизация пользователей в 3proxy 

### ISSUE THREAD

**Issue by srvh** [3proxy/3proxy#818]
Наблюдается проблема с 3proxy, когда пользователь пытается подключиться к 3proxy с логином/паролем, которого нет среди разрешенных.
Другими словами, когда пользователь знает, что есть прокси с IP адресом и портом, но не знает пароль и использует любую связку.
3proxy корректно каждый раз такого пользователя не авторизует. Но если у пользователя стоит скрипт с авторизацией через прокси и этот скрипт постоянно пытается использовать прокси, то 3proxy периодически падает (точнее перестает отвечать на подключения с правильным логином/паролем).
В логах появляется такая строка. Цифры 0 0 - это количество потребленного трафика.
imf62lo4 0 0

Используется logformat "L%U %I %O"
И таких строк становится невероятное количество. То есть пользователь подключается, но авторизация его не проходит, так как используемый логин/пароль отсутствует в allow users

Можно ли как-то фильтровать данный момент с помощью 3proxy?
Я смог вручную заблокировать IP адрес такого пользователя, хотелось бы автоматическое решение.

**Comment by srvh** [comment]
Используется цепочка parent для авторизации на втором прокси.
так:
include /conf/users
auth strong
allow *
parent 1000 http 192.12.44.56 3122 imf62lo4 password

И указанная строка в логах imf62lo4 0 0 - это логин внешнего прокси, указанного в parent.

Когда такое случается, то 3proxy для корректного пользователя перестает отвечать и приходиться рестартить 3proxy, чтобы все заработало вновь. Но потом все повторяется вновь, так как у пользователя с неверным логином/паролем работает скрипт, который пытается все время подключиться к 3proxy.

**Comment by z3APA3A** [comment]
Логгируй код ошибки, иначе невозможно сказать что именно происходит. Для подсчета трафика лучше использовать счетчики, а логгирование использовать для логгирования.
