### ISSUE TITLE
http3 протокол.

### ISSUE THREAD

**Issue by FastSpace123** [3proxy/3proxy#821]
Всех приветствую. Скажите есть ли поддержка UDP и http3?

Тестирую тут: https://cloudflare-quic.com

Поднят конфиг 3proxy. 
1)Тестирую в браузере Firefox без прокси - **есть http3**.
2)Тестирую с прокси поднятым на 3proxy в браузере Firefox - **нет протокола http3.**
3)Тестирую без прокси браузере Firefox, но на айпи адресе который является прокси из пункта 2 - **есть http3**

P.S для https://cloudflare-quic.com теста http3 страницу надо 2 раза ребутать, чтобы проверить есть. Либо смотреть в консоли в разделе сеть.

**Comment by z3APA3A** [comment]
HTTP прокси работают по TCP. Для поддержки UDP необходимо использовать SOCKS.
