### ISSUE TITLE
Как запретить хосты из списка хостов для блокировщика рекламы и прочее?

### ISSUE THREAD

**Issue by maksam07** [3proxy/3proxy#822]
Добрый день. 
Не так давно задался вопросом, что через прокси идет лишний трафик, который на машине, использующей прокси, по какой-то причине не отрезается, хотя на машине блокировщик рекламы настроен. В общем, в чем суть. Хочу при помощи списка доменов и "deny" в конфиге отрезать все лишнее.
Составил небольшой скрипт на питоне, который из файла для hosts делает мне файл для 'deny' (домены через запятую, без пробелов и пр.). Доменов более 200к. Столнкулся с проблемой, что оно почему-то не работает.

Проверяю блокировщик таким сервисом: https://d3ward.github.io/toolz/adblock.html

Проблема в том, что все блоки остаются красными (кроме одного, но он и без блокировки зеленый)
Я попробовал вручную добавить хосты из блока "Google Ads": pagead2.googlesyndication.com,ads.google.com,adservice.google.com,pagead2.googleadservices.com,googleadservices.com
И после этого блок стал зеленый.
Но когда я использую свой сформированный список - блок красный. Хотя в списке есть все эти домены. То есть файл отсечения лишних доменов работает, но не при случае, когда я загружаю туда свой сформированный список.

Прикладываю сгенерированный список:
[list.txt](https://github.com/3proxy/3proxy/files/9533494/list.txt)

Просьба подсказать, в чем может быть проблема.

**Comment by z3APA3A** [comment]
Длина строки не должна превышать 64К.
Можно разбить на несколько deny, убирающихся в лимит.
В таком случае все равно лучше использовать PCREPlugin (без SSLPLugin) и блокировать через `pcre request deny "//(host1|host2|host3)"` (не забыв экранировать точки)
потому что PCRE компилирует выражение и это будет работать быстрей, чем поиск по подстрокам в обычном deny. Наверняка можно сильно сократить список если использовать список регулярок, а не хостнеймов.
Так же можно создать много записей типа

```
nscache 100500
nsrecord host1 0.0.0.1
nsrecord host2 0.0.0.1
```

задав достаточно большой nscache (чтобы в него гарантировано поместились все записи). Это выглядит громоздко, но на самом деле будет работать быстро, потому что для запиcей используется хеш-таблица. Список можно держать в отдельном файле, включать через `include`

**Comment by z3APA3A** [comment]
Конфигурация немного дольше читаться будет, но влиять это ни на что не должно.

**Comment by maksam07** [comment]
Она читается единожды при запуске или есть какая-то периодичность? Если единожды при запуске, то даже с 800к строками и на таком слабом сервере, сервис доволь быстро запускается. Тут главное, чтобы конфигурация не читалась при каждом обращении к сайтам, а то каждый раз чекать 800к доменов - может быть уже проблематично, я думаю)
