### ISSUE TITLE
Proxy (incoming) IPv4 ----> IPv6 (outgoing) IPv6 random on each request

### ISSUE THREAD

**Issue by slaiddominio** [3proxy/3proxy#823]
Hello everyone, I'm facing a problem creating the configuration I need!
The scenario is as follows:

0 - Debian Linux 11
1 - Server with a Public IPv4
2 - BGP Bird Session /39
3 - Do I need to sign the IPs and define the route and define the default route (how to proceed)?
4 - Use /39 for 3Proxy to randomize (randomly IPv6)
5 - Configure a single port, delivering a new IPv6 to each new request!

How can I proceed with this process?

**Comment by z3APA3A** [comment]
0.9.4+ supports IPv6 networks in `parent extip`, address is randomely choosen from the net
```

allow *
parent 1000 extip 1:2:3:4:5::/39 0

```

**Comment by DataFastProxies** [comment]
When using parameter 1000, this is related to weight, how does it work?
What are the existing weight variables?
allow *
parent 250 extip 1:2:3:4:5::/39 0?
parent 1000 extip 1:2:3:4:5::/39 0?
parent 2000 extip 1:2:3:4:5::/39 0?

**Comment by doim** [comment]
@z3APA3A   

every request alway get the same ipv6. what's wrong of my config?


0.
#ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 209.141.55.22  netmask 255.255.255.0  broadcast 209.141.55.255
        inet6 2605:6400:48:4185:73b2:d1dd:c794:1df4  prefixlen 48  scopeid 0x0<global>
        inet6 2605:6400:48:99c0:b3b6:cbbb:6415:9f16  prefixlen 48  scopeid 0x0<global>
        inet6 2605:6400:48:886f:ff7:b366:fd3f:160a  prefixlen 48  scopeid 0x0<global>
....

1.
#cat 3proxy.cfg    
--------
daemon
maxconn 5000
nscache 65536
log /var/log/3proxy/3proxy.log D
logformat "%e"
rotate 2  

nserver 8.8.8.8
nserver 8.8.4.4
nserver [2001:4860:4860:0:0:0:0:8888]
timeouts 1 5 30 60 180 1800 15 60
setgid 65535
setuid 65535

users usryourname:CL:pass065
authcache user 60
auth strong cache
flush
deny * * 127.0.0.1
allow usryourname
allow * * ::/0
parent 1000 extip 2605:6400:48::/48 0
proxy -6 -s0 -n -a -p3128

2.every request ,always get the same ipv6 "2605:6400:48:886f:ff7:b366:fd3f:160a"
# curl -x usryourname:pass098765@209.141.55.22:3128 icanhazip.com
2605:6400:48:886f:ff7:b366:fd3f:160a
# curl -x usryourname:pass098765@209.141.55.22:3128 icanhazip.com
2605:6400:48:886f:ff7:b366:fd3f:160a
# curl -x usryourname:pass098765@209.141.55.22:3128 icanhazip.com
2605:6400:48:886f:ff7:b366:fd3f:160a
root@localhost:/opt/3proxy#
