### ISSUE TITLE
Can't use mycrypt with salt, password not accepted by 3proxy

### ISSUE THREAD

**Issue by basinilya** [3proxy/3proxy#824]
Hi.
It works for me with **:CL:** or :NT: , but not with :CR:
Here's what I do 
```
# mycrypt aaa bbb
CR:$1$aaa$YkaxWbOMfsEHoaut0Rp3f0

/etc/3proxy/3proxy.cfg
users proxy:CR:$1$aaa$YkaxWbOMfsEHoaut0Rp3f0
...
auth strong
allow proxy


# systemctl restart 3proxy

~/.curlrc.proxy
proxy-user = "proxy:bbb"

#curl -v --config ~/.curlrc.proxy --proxy http://127.0.0.1:3130 https://www.yougetsignal.com/what-is-my-ip-address/
> Proxy-Authorization: Basic cHJveHk6YmJi
< HTTP/1.0 407 Proxy Authentication Required

```

What am I doing wrong? 3proxy version 0.9.4

**Comment by z3APA3A** [comment]
what do you have in logs?

**Comment by basinilya** [comment]
@z3APA3A I found the reason: I didn't double quote the hashed password in the main .cfg file. When I moved it into an included file it started working.

> what do you have in logs?

In case of a wrong password this is the only thing that's printed:

```
2022-09-19 19:31:05.049  PROXY.3130 00005 proxy 127.0.0.1:53788 0.0.0.0:0 0 0 0 CONNECT_www.yougetsignal.com:443_HTTP/1.1
```

**Comment by z3APA3A** [comment]
It should not affect `users`, because quotes are actually required only if the string contains whitespaces or quotes. May be, you had some unicode character like non-breaking space.

**Comment by basinilya** [comment]
I think the dollar sign $ was the reason
