### ISSUE TITLE
tls handshake too slow

### ISSUE THREAD

**Issue by hunterhe23** [3proxy/3proxy#825]
tcpdump shows when established tcp with a https server, 3proxy will wait 100ms to send tls handshake client hello. 
that results in a long request duration. 
why 100ms and could it optimized?

**Comment by z3APA3A** [comment]
https://3proxy.ru/highload.asp
see TCP_NODELAY.

**Comment by hunterhe23** [comment]
i test and it doesn't work.
it only appears with https request.
http is ok.

**Comment by z3APA3A** [comment]
It's better to check TCP_NODELAY is set in the client application for proxy connection. Proxy itself does not perform TLS.
