### ISSUE TITLE
Authentication by IP is User and Password using separate file

### ISSUE THREAD

**Issue by slaiddominio** [3proxy/3proxy#828]
Hello guys, I have a problem with the configuration of 3Proxy, I would like your help!

As a priority, 3Proxy will look for alttication by IP Address, if it is not on the list, request authentication by user and password!

I would like the authentication to be in separate files.

I have 2 /24 on a single server, I would like to separate authentication both by user and password, and by IP, for each /24 allocated on the server!

**Comment by z3APA3A** [comment]
check `auth` and `allow` commands. You should use something like

```
auth iponly strong

allow * ip1,ip2,net1,etc
deny -
```

`$` (for inline inclusion) and/or `include` (for config file inclusion) may be used to include external files.
