### ISSUE TITLE
Domain traffic control issues

### ISSUE THREAD

**Issue by derrick5788** [3proxy/3proxy#831]
I am using parent proxy, if I want domain A to go to parent proxy 1 and domain B to go to parent proxy 2, how should I set it?

**Comment by derrick5788** [comment]
Traffic coming in through 1 socks5 port

**Comment by z3APA3A** [comment]
You need something like
```
allow * * A
parent 1000 socks5+ proxy1 port1
allow * * B
parent 1000 socks5+ proxy2 port2
allow (if you need to allow traffic to another domains directly)
socks
```

Client must be set to resolve hostnames via socks.

**Comment by derrick5788** [comment]
tks
