### ISSUE TITLE
[question] how can rotate through ipv6 subnet ips

### ISSUE THREAD

**Issue by ralphrimwell** [3proxy/3proxy#832]
i have a /64 subnet on my vps. how can i set 3proxy to use a different ip each time?

**Comment by phantomcraft** [comment]
It's currently not possible (I think), but I know a LD_PRELOAD tool that maybe could work with 3proxy: https://github.com/electrorys/randsaddr

**Comment by z3APA3A** [comment]
Check current devel version, it supports IPv6 subnetworks for `parent` `extip`, e.g.

allow * * ::/0
parent 1000 extip 1:2:3:4::/64 0

**Comment by apirahim** [comment]
@z3APA3A Thanks for the solution, it's working but I have a problem the IP address is the same
I always get 2600:1900:4020:xxxx:: as my ip, I didn't want to open a duplicate ticket for this issue
when I try "curl --interface 2600:1900:4020:xxxx::1 ipv6.ip.sb" or  "curl --interface 2600:1900:4020:xxxx::2 ipv6.ip.sb"  ...etc I get a diffrent IP each time

this is my config

`nserver 1.1.1.1
nserver 2606:4700:4700::1111
config /conf/3proxy.cfg
monitor /conf/3proxy.cfg

log /logs/3proxy-%y%m%d.log D
rotate 60
counter /count/3proxy.3cf

users $/conf/passwd

include /conf/counters
include /conf/bandlimiters

auth strong
deny * * 127.0.0.1
allow *
proxy -n -6
socks
flush
allow admin

admin -p8080
allow * * ::/0
parent 1000 extip 2600:1900:4020:xxxx::/64 0
`

**Comment by z3APA3A** [comment]
Commands sequence is important for proxy, in your case

> allow * * ::/0
> parent 1000 extip 2600:1900:4020:xxxx::/64 0

are not applied to proxy or socks.

**Comment by z3APA3A** [comment]
probably you should also restrict access to host IPv6 network in addition to 127.0.0.1
