### ISSUE TITLE
Outgoing ipv6 only not working

### ISSUE THREAD

**Issue by minhdv92** [3proxy/3proxy#834]
Hi.

I tried config incomming ip and outgoing ipv6, its not working,
But when I try ipv6 fallback to ipv4, its working.
I'm using 3proxy-0.9.4

this is my config

daemon
maxconn 1000
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
setgid 65535
setuid 65535
flush
allow *
socks -6 -n -a -p30000 -i23.142.xxx.xxx -exxx:xxx:18c8:4cd:367:d615:efa8:f4de
flush

But when i used socks -64 its working and show me ipv4. Now, I want using outgoing ipv6 only.

Thanks

**Comment by z3APA3A** [comment]
What do you have in logs?

**Comment by minhdv92** [comment]
I tried single command and got this

![image](https://user-images.githubusercontent.com/77137924/197218557-9f817c5f-f260-432b-8603-55fb7107104d.png)

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtoe.asp#ERRORS

00012  means 3proxy can not bind to -e specified. Check this address is assigned to any interface.

**Comment by minhdv92** [comment]
hi @z3APA3A 
Sorry, I'm misstake. I changed to correct ip address. But still can not connect

![image](https://user-images.githubusercontent.com/77137924/197229253-2dba3b34-deed-4028-acad-2173aec077ce.png)

**Comment by z3APA3A** [comment]
Your client requests IPv4 address insted of IPv6 address or hostname. IPv4 address can not be accessed via IPv6. Set client to resolve name via proxy. e.g. curl --socks5-hostname or socks5h:// proxy URL.

**Comment by minhdv92** [comment]
Thank @z3APA3A 
I tried on client 
![image](https://user-images.githubusercontent.com/77137924/197243977-e9b14398-c8f2-4f9f-bb3a-932498842b70.png)
or using firefox like this
![image](https://user-images.githubusercontent.com/77137924/197244054-1319a091-3b00-40e7-9a9f-d845ebc21942.png)

The proxy will get Segmentation fault

![image](https://user-images.githubusercontent.com/77137924/197244145-a9ad6e20-be73-4405-820f-cdd6f6dad3b5.png)
