### ISSUE TITLE
What about HTTP/3 & QUIC

### ISSUE THREAD

**Issue by thisisclint21** [3proxy/3proxy#837]
Hey,

Do you have more information about http3, does 3 proxy will supports it etc.

Regards

**Comment by APX403** [comment]
Interessted too, thank you 👍

**Comment by ezbik** [comment]
It supports UDP, it's enough.
The thing is that browsers can't utilize it (quic over socks5).

**Comment by z3APA3A** [comment]
Currently, SOCKSv5 is compatible with QUIC. In addition to it, there are few potential things to implement:
1. Proxy definition in HTTP/3 (RFC 9114). HTTP/3 only defines 'CONNECT' operation with TCP support. So it does not allow to use QUIC with destination server, actually this is QUIC to TCP proxy.
2. Extension for UDP over CONNECT (http) proxy. There is an expired draft RFC from Google https://www.ietf.org/archive/id/draft-ietf-masque-connect-udp-06.html with no support in browsers (AFAIK). It's relatively easy to implement, but I see no reason in it as long as it's not supported and probably dead + I'm not sure it can really benefit over HTTP/2. May be, 1+2 were expected to be combined, but there is no information on it.
3. There is one more draft RFC from Google https://datatracker.ietf.org/doc/draft-pauly-masque-quic-proxy/  + Chrome probably supports some kind of QUIC proxy, at least there is an quic:// URI for proxy configuration. May be it's the same proxy protocol, but there are no details on it.  It's not simple to implement, and I need to be sure it does not share the fate of (2) before starting to work on it.

So, to be short, SOCKSv5 is the only standard way to proxy QUIC for a while.

**Comment by thisisclint21** [comment]
HAProxy announced to support `QUIC`, does its SOCKS5 too?

Reference: https://www.haproxy.com/fr/blog/announcing-haproxy-2-6/

**Comment by z3APA3A** [comment]
HAProxy is reverse proxy, it does not require proxy support on client side.

**Comment by thisisclint21** [comment]
Ah yes, but it also works on HTTP no?

**Comment by z3APA3A** [comment]
It works as HTTP server rather than HTTP proxy. E.g. it terminates TLS.
