### ISSUE TITLE
3proxy doesn't work from another computer

### ISSUE THREAD

**Issue by monkekode** [3proxy/3proxy#839]
Hi. I have 2 MacOS computers on the same LAN: `192.168.1.201` and `192.168.1.202`. The 3proxy config looks like this:

```
socks
```

When I run it, I can see using `lsof` that it listens on all interfaces:

```
3proxy    64544   a1    4u  IPv4 0xeae00056baed30d3      0t0  TCP *:1080 (LISTEN)
```

And it works fine from localhost (both work):

```
curl -x socks5h://192.168.1.201:1080 ifconfig.co
curl -x socks5h://127.0.0.1:1080 ifconfig.co
```

BUT, when I try to connect to the proxy from `192.168.1.202` it just hangs: `curl -x socks5h://192.168.1.201:1080 ifconfig.co`. However if I start a server on the same port like this `python3 -m http.server 1080` I can connect just fine. Also, if I try to use a non-existent socks on port 1081, it ends immediately instead of handing so it looks like the client connects to 3proxy, but it doesn't let it through for some reason?

How can I fix this?

Thanks

**Comment by z3APA3A** [comment]
Check your firewall settings
https://support.apple.com/guide/mac-help/block-connections-to-your-mac-with-a-firewall-mh34041/mac
