### ISSUE TITLE
Ошибка ограничения трафика при отсутствующем лимите трафика

### ISSUE THREAD

**Issue by slonopot** [3proxy/3proxy#841]
3proxy собран из исходников под Windows с использованием msvc.

У пользователя рандомно "кончается" трафик (ошибка 10 в логе), хотя `countin` в конфиге не используется вообще. Клиент при этом никакой нагрузки на прокси не создает. После перезапуска сервиса ошибка уходит.

Конфиг:

```service
maxconn 500000
timeouts 1 5 30 60 90 90 15 60 15 5
bandlimin 1500000 user
bandlimout 1500000 user
connlim 50 0 user
auth strong
users user:CL:password
deny * * 10.0.0.0/8
deny * * 172.16.0.0/12
deny * * 192.168.0.0/16
allow *
proxy -n -a -p1111 -i1.2.3.4 -e4.3.2.1
socks -n -a -p2222 -i1.2.3.4 -e4.3.2.1

**Comment by z3APA3A** [comment]
10 дается по всем лимитам. у тебя есть connlim.
