### ISSUE TITLE
Не работает countin/countout и countall при многопользовательском конфиге

### ISSUE THREAD

**Issue by x-amer-ngmx** [3proxy/3proxy#842]
Аффект следующий:

Если у пользователя заканчивается трафик то в лог эта информация перестаёт попадать. И все пользователи перестают работать. Информации по ним НЕТ в логах.

Если перезагрузить 3proxy то работа пользователей у которых ещё не достигнут лимит по трафику возобновится. Но как только поступят запросы от пользователей у которых лимит уже достигнут Все перестают работать. 

Всё Выше изложенное применимо ко всем управляющим командам countin/countout/coutnall

```
maxconn 100
nscache 65536
stacksize 6000
nserver 8.8.8.8
nserver 8.8.4.4
timeouts 1 5 30 60 180 1800 15 60
setgid 65535
setuid 65535

log /var/log/filelog.log D
logformat "L%C - %U [%d/%o/%Y:%H:%M:%S %z] ""%T"" %E %I %O %N/%R:%r"
archiver gz gzip %F
rotate 30

counter /var/log/counters.tc H /var/log/counter.log


>>>>countin "1/user1" H 10 user1 * * * *
>>>>countin "2/user2" H 20 user2 * * * *


auth strong
users user1:CL:passwd1
allow user1
proxy -n -a -64 -S0 -i0.0.0.0 -efff:0:ccc -p4001
flush

auth strong
users user2:CL:paswd2
allow user2
proxy -n -a -64 -S0 -i0.0.0.0 -efff:0:bbb -p4002
flush

```
![Снимок экрана от 2022-11-05 12-36-49](https://user-images.githubusercontent.com/12796779/200113711-ab413d69-7621-4861-a06b-4291e93035a3.png)

**Comment by z3APA3A** [comment]
По этому логу не видно проблем с таймаутами по разным юзерам, если они есть - покажи пример лога. По этому логу видно что в socks прокси приходит клиент другого типа и присылает что-то отличное от SOCKS, скорей всего неправильно порт на клиенте прописан

**Comment by z3APA3A** [comment]
P.S. и поскольку у тебя

setgid 65535
setuid 65535

проверь с этими gid/uid есть доступ к логу, файлу счетчиков и файлу с отчетами по трафику

**Comment by x-amer-ngmx** [comment]
Приветствую! Порт прописан верно(ведь до наступления лимита трафика Всё работает) к логам доступ есть у всех (777 на директорию). По этому багу более понятных логов нет, есть только поведение.  Смотрел даже системные логи (по этой проблеме ПУСТО) по ресурсам - Тоже Ничего (на первый взгляд) не течёт. Тесты были проведены на 3х серваках (Cenos 7.9 обсолютно чистая). Данный баг словлен на версии 0.9.3.

**Comment by x-amer-ngmx** [comment]
> Аффект следующий:
> 
> Если у пользователя заканчивается трафик то в лог эта информация перестаёт попадать. И все пользователи перестают работать. Информации по ним НЕТ в логах.
> 
> Если перезагрузить 3proxy то работа пользователей у которых ещё не достигнут лимит по трафику возобновится. Но как только поступят запросы от пользователей у которых лимит уже достигнут Все перестают работать.
> 
> Всё Выше изложенное применимо ко всем управляющим командам countin/countout/coutnall
> 
> ```
> maxconn 100
> nscache 65536
> stacksize 6000
> nserver 8.8.8.8
> nserver 8.8.4.4
> timeouts 1 5 30 60 180 1800 15 60
> setgid 65535
> setuid 65535
> 
> log /var/log/filelog.log D
> logformat "L%C - %U [%d/%o/%Y:%H:%M:%S %z] ""%T"" %E %I %O %N/%R:%r"
> archiver gz gzip %F
> rotate 30
> 
> counter /var/log/counters.tc H /var/log/counter.log
> 
> 
> >>>>countin "1/user1" H 10 user1 * * * *
> >>>>countin "2/user2" H 20 user2 * * * *
> 
> 
> auth strong
> users user1:CL:passwd1
> allow user1
> proxy -n -a -64 -S0 -i0.0.0.0 -efff:0:ccc -p4001
> flush
> 
> auth strong
> users user2:CL:paswd2
> allow user2
> proxy -n -a -64 -S0 -i0.0.0.0 -efff:0:bbb -p4002
> flush
> ```
> 
> ![Снимок экрана от 2022-11-05 12-36-49](https://user-images.githubusercontent.com/12796779/200113711-ab413d69-7621-4861-a06b-4291e93035a3.png)



> Приветствую! Порт прописан верно(ведь до наступления лимита трафика Всё работает) к логам доступ есть у всех (777 на директорию). По этому багу более понятных логов нет, есть только поведение. Смотрел даже системные логи (по этой проблеме ПУСТО) по ресурсам - Тоже Ничего (на первый взгляд) не течёт. Тесты были проведены на 3х серваках (Cenos 7.9 обсолютно чистая). Данный баг словлен на версии 0.9.3.

ПРОБЛЕМА АКТУАЛЬНА

**Comment by x-amer-ngmx** [comment]
Закрыл по ошибке(((
