### ISSUE TITLE
socks5+udp - 3proxy за NAT

### ISSUE THREAD

**Issue by ezbik** [3proxy/3proxy#844]
Проблема -- 3proxy за NAT, нужно socks5 + UDP.
Клиенты в интернете.
Пока решил так, что пробрасываю с внешки порты UDP 30000:65000 на LAN IP , где 3proxy.
Но это очень костыльно.
Может есть более элегантное решение?

**Comment by z3APA3A** [comment]
SOCKSv5+UDP требует открытия дополнительных портов, с NAT такая схема не совместима.  По-хорошему, это должен был бы поддерживать conntrack, он специально для этого создан, но он SOCKSv5, насколько я знаю, не поддерживает и не знаю, насколько сложно его этому научить. Поэтому хорошее решение - сделать туннель до прокси. Может быть, можно использовать какой-то соксификатор проходящего трафика, но я не знаю таких с поддержкой UDP.

**Comment by z3APA3A** [comment]
Еще это можно было бы реализовать с помощью UPnP, но на поддержку UPnP пока запросов не было
