### ISSUE TITLE
Перестаёт работать подключение через ssh после запуска службы

### ISSUE THREAD

**Issue by shulgadanilazxc** [3proxy/3proxy#845]
Все действия выполняю в соответствии с гайдом:
https://selectel.ru/blog/tutorials/how-to-install-and-configure-3proxy-proxy-servers-on-ubuntu/
Прокси работает, в логах никаких ошибок нет, однако на сервер через ssh не могу зайти ни по одному IP сервера
(internal выставлял тот-же, что и external, ставил один адрес сервера из 3)

**Comment by shulgadanilazxc** [comment]
fixed

**Comment by jmatg1** [comment]
А что ты сделал? Я поставил опен впн и прокси, и теперь не могу подключиться по ssh. Делал по той инструкции что скинул

**Comment by shulgadanilazxc** [comment]
> А что ты сделал? Я поставил опен впн и прокси, и теперь не могу подключиться по ssh. Делал по той инструкции что скинул

когда ставишь ufw 

sudo ufw allow *порт_прокси*
sudo ufw allow ssh
*остальные нужные тебе порты*
sudo ufw enable

**Comment by jmatg1** [comment]
Спасибо большое, помогло
