### ISSUE TITLE
How to pass login/pass from 3proxy to the parent proxy

### ISSUE THREAD

**Issue by artem-adline** [3proxy/3proxy#847]
I have **dynamic amount of users** on my parents proxies, can **I pass login/password** from 3proxy to parent proxy?
**For example:**
I have 3 customers that have their own credentials, I added this credentials to both proxies and I need to redirect from 3proxy with correct credentials 
3proxy.cfg, 
```
auth strong
users customer_1:CL:pass1 customer_2:CL:pass2 customer_3:CL:pass3
allow admin
parent 1000 http parent-proxy-1.com $(user1_login) $(user1_pass)
proxy -n
```

**Comment by z3APA3A** [comment]
`parent 1000 http parent-proxy-1.com * *`

use `auth useronly` if you do not want 3proxy to check password at all, but you can not mix `useronly` and `strong` within same service, you must either authenticate all users locally or all users remotely.
