### ISSUE TITLE
О комбинации socks + http parent

### ISSUE THREAD

**Issue by unspecd** [3proxy/3proxy#848]
В случае таких настроек:
```
allow *
parent 1000 http host port username password
socks -p1080
flush
```
-- прокси работает некорректно, и нужно использовать методы `connect` или `connect+` в качестве `parent`. Может быть, следует такую комбинацию сделать запрещенной и выдавать ошибку во время чтения конф. файла?

**Comment by unspecd** [comment]
Например, если в конфиге выше заменить socks на auto и попытаться выполнить такие запросы:
```console
curl -x http://username:password@127.0.0.1:1234 -L http://2ip.ru
curl -x socks5://username:password@127.0.0.1:1234 -L http://2ip.ru
```
-- и при этом смотреть, что происходит в wireshark, то в первом случае будет такой запрос в parent:
`GET http://2ip.ru/ HTTP/1.1`, а во втором - такой: `GET / HTTP/1.1`.

**Comment by z3APA3A** [comment]
Смотри документацию, для сервисов отличных от `proxy` `http` работает аналогично `tcp` и поведение выше ожидаемое. Чтобы оно работало так, как ты ожидаешь для socks надо делать дополнительный локальный редирект в proxy для http трафика.

**Comment by unspecd** [comment]
> локальный редирект в proxy для http трафика

Не соображу, можно пример? То есть редирект из socks в http, затем из http в http parent? Не вижу, что это даст.

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtor.asp#SOCKSREDIR
