### ISSUE TITLE
Ipv6 subnet problem

### ISSUE THREAD

**Issue by derrick5788** [3proxy/3proxy#849]
Hi,
I use the following profile

```
allow * * ::/0
parent 1000 extip 2001:xxx:xxxx::/48 0
socks -6 -p6110
proxy -6 -p6111
flush
```

My network configuration

```
sit1: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1480
        inet6 fe80::2d4c:1e0d  prefixlen 64  scopeid 0x20<link>
        inet6 2001:xxx:xxxx::  prefixlen 48  scopeid 0x0<global>
```

but error
log:
`221121223738.963 6110 00012 - xxx.xxx.xxx.xxx:52484 2606:4700:e0::ac40:6218:443 0 0 1 CONNECT 2606:4700:e0::ac40:6218:443`

**Comment by derrick5788** [comment]
3proxy tiny proxy server 3proxy-0.9.4 ()

**Comment by z3APA3A** [comment]
add external address to logformat and check if you can ping destination address with this address as a source. AFAIK assigning /48 network to interface does not actually assigns all addresses from this network to host.
