### ISSUE TITLE
Compile 3proxy in windows using MSYS2 with installed GCC 12.2 have error with PCREPlugin

### ISSUE THREAD

**Issue by laipg91** [3proxy/3proxy#851]
Hi,
When I compile source code version 0.9.4 it had an error about PCREPlugin
I'm using MSYS2 with GCC installed
Here is compile log

> $ make -f Makefile.win
> make[1]: Entering directory '/e/3proxy/src'
> make[2]: Entering directory '/e/3proxy/src/plugins/utf8tocp1251'
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS utf8tocp1251.c
> gcc -o ../../../bin/utf8tocp1251.dll -O2 -s -mthreads -shared utf8tocp1251.o -lws2_32 -lodbc32 -ladvapi32
> make[2]: Leaving directory '/e/3proxy/src/plugins/utf8tocp1251'
> make[2]: Entering directory '/e/3proxy/src/plugins/WindowsAuthentication'
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS WindowsAuthentication.c
> gcc -o ../../../bin/WindowsAuthentication.dll -O2 -s -mthreads -shared WindowsAuthentication.o -lws2_32 -lodbc32 -ladvapi32
> make[2]: Leaving directory '/e/3proxy/src/plugins/WindowsAuthentication'
> make[2]: Entering directory '/e/3proxy/src/plugins/TrafficPlugin'
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS TrafficPlugin.c
> gcc -o ../../../bin/TrafficPlugin.dll -O2 -s -mthreads -shared TrafficPlugin.o
> make[2]: Leaving directory '/e/3proxy/src/plugins/TrafficPlugin'
> make[2]: Entering directory '/e/3proxy/src/plugins/StringsPlugin'
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS StringsPlugin.c
> gcc -o ../../../bin/StringsPlugin.dll -O2 -s -mthreads -shared StringsPlugin.o
> make[2]: Leaving directory '/e/3proxy/src/plugins/StringsPlugin'
> make[2]: Entering directory '/e/3proxy/src/plugins/PCREPlugin'
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS pcre_compile.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS  pcre_config.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS pcre_dfa_exec.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS pcre_exec.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS pcre_fullinfo.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS pcre_get.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS  pcre_globals.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS  pcre_newline.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS  pcre_ord2utf8.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS  pcre_refcount.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS  pcre_study.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS  pcre_tables.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS  pcre_valid_utf8.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS  pcre_version.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS  pcre_xclass.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS pcre_plugin.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS pcre_maketables.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS pcre_ucd.c
> gcc  -O2 -s -c -mthreads -DWITH_STD_MALLOC -DNOIPV6 -DNORADIUS pcre_table.c
> gcc -o ../../../bin/PCREPlugin.dll -O2 -s -mthreads -shared pcre_compile.o pcre_config.o pcre_dfa_exec.o pcre_exec.o pcre_fullinfo.o pcre_get.o pcre_globals.o pcre_newline.o pcre_ord2utf8.o pcre_refcount.o pcre_study.o pcre_tables.o pcre_valid_utf8.o pcre_version.o pcre_xclass.o pcre_plugin.o pcre_maketables.o pcre_ucd.o pcre_table.o
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe
> : pcre_plugin.o:pcre_plugin.c:(.text+0x47b): undefined reference to `__imp_pcre_compile'
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe
> : pcre_plugin.o:pcre_plugin.c:(.text+0x730): undefined reference to `__imp_pcre_exec'
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe
> : pcre_plugin.o:pcre_plugin.c:(.text+0xc3a): undefined reference to `__imp_pcre_malloc'
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe
> : pcre_plugin.o:pcre_plugin.c:(.text+0xc63): undefined reference to `__imp_pcre_free'
> collect2.exe: error: ld returned 1 exit status
> make[2]: *** [Makefile.inc:61: ../bin/PCREPlugin.dll] Error 1
> make[2]: Leaving directory '/e/3proxy/src/plugins/PCREPlugin'
> make[1]: Leaving directory '/e/3proxy/src'

And here is gcc version

> $ gcc --version
> gcc.exe (Rev6, Built by MSYS2 project) 12.2.0
> Copyright (C) 2022 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

How can I fix this error for PCREPlugin, the bin folder doesnt have PCREPlugin.dll

**Comment by z3APA3A** [comment]
Do you have PCRE sources from 3proxy distribution or compile your own ones? 3proxy distribution has
#define PCRE_STATIC
at the beginning of config.h.

**Comment by laipg91** [comment]
> Do you have PCRE sources from 3proxy distribution or compile your own ones? 3proxy distribution has #define PCRE_STATIC at the beginning of config.h.

I compile 3proxy with distribution source, it have PCRE source in plugin folder, and when I remove #define PCRE_STATIC still have error
Did I need compile PCRE for static lib then what I need to do? Because I compiled them then make install but still have error
 
Enviroment i'm using is Windows, I think compile PCRE source then make install wont work because the lib is in MSYS2 enviroment, not in Windows
