### ISSUE TITLE
Как работают maxconn и connlim?

### ISSUE THREAD

**Issue by dvdavydov** [3proxy/3proxy#852]
Добрый день

Версия 3proxy 0.9.4 на Linux. В конфиге установлен только maxconn 1000, connlim не настроен, множество сервисов tcppm такого вида:
flush
allow * * * * *
tcppm 22 10.20.30.40 22
flush

Какими будут лимиты подключений - общий на сервер и на каждый из этих сервисов?

Удалось поймать момент, когда новые подключения перестают проходить, при этом похоже что упираемся в общий лимит 250 коннектов:
#netstat -p | grep 3proxy | wc -l
251

Хочется чтобы был большой общий maxconn (допустим, 5000) и не было лимитов по отдельным сервисам. Какими в этом случае должны быть корректные настройки?

**Comment by z3APA3A** [comment]
maxconn действует отдельно на каждый запущенный сервис, в данном случае отдельно на каждый tcppm

connlim действует согласно ACL который к нему приделан, т.е. весь трафик попадающий в ACL считается в данный connlim.

новые подключения могут не проходить не из-за упирания в maconn/connlim а из-за упирания в системные/пользовательские лимиты или ресурсы. см https://3proxy.ru/highload.asp
