### ISSUE TITLE
log requested URL?

### ISSUE THREAD

**Issue by akohlsmith** [3proxy/3proxy#859]
%T gives me GET/POST/etc and the host/port and method, but if I wanted to see (for example) the full URL of a youtube request, how could I get that URL in the log? My goal is to build up a way to filter a request based not just on the domain, but also on the requested URL.

**Comment by z3APA3A** [comment]
%T gives full URI for http, for https:// you only see CONNECT request, because GET/POST are sent inside TLS connection. You can use https://3proxy.ru/plugins/SSLPlugin/ for certificate spoofing to get unencrypted traffic.
