### ISSUE TITLE
ipv6 через parent - не пробрасывает адрес v6

### ISSUE THREAD

**Issue by ffcc999999** [3proxy/3proxy#860]
Версия 0.9.4
Такой конфиг для юзера
3proxy на ВПС, доступ к удаленному прокси через ВПН(что бы сгребсти в кучу много прокси к единому серверу)
auth strong
users user:123123123
deny * * * 21,22,25,465,587,3389,5900,5800,7070,6568,5938
allow user * * *
parent 1000 socks5+ 10.8.0.4 1080
fakeresolve
socks -n -p31802 -a
flush

Ситуация такая, если я через iptables прокину порт 31802 на 10.8.0.4:1080 и подключусь(типо напрямую к первому прокси), то всё как бы ок, сайты видят ipv4 и ipv6, всё вместе работает, но это не то решение что мне нужно.

Через 3proxy parent ipv6 где-то теряется, сайты его не видят, попытки socks -64 -n -p31802 -a ничего тоже не дали.
Это вообще должно работать через parent? Может есть другие варианты как заставить работать ipv4 + ipv6 именно через 3proxy и удаленный прокси сервер.

**Comment by z3APA3A** [comment]
А что в логах?

**Comment by ffcc999999** [comment]
> А что в логах?

ничего необычного.
при открытии сайта https://test-ipv6.com/ вот так
ipv4 без вопросов, ipv6 нет.
1670235668.836 SOCK5.31800 00057 user 11.11.11.11:61126 10.8.0.4:1080 0 74 2 CONNECT_ipv6.lookup.test-ipv6.com:443
1670235668.839 SOCK5.31800 00057 user 11.11.11.11:61128 10.8.0.4:1080 0 70 2 CONNECT_ipv6.ams2.test-ipv6.com:443
1670235668.885 SOCK5.31800 00000 user 11.11.11.11:61124 10.8.0.4:1080 1255 5433 1 CONNECT_ipv4.lookup.test-ipv6.com:443
1670235669.025 SOCK5.31800 00057 user 11.11.11.11:61130 10.8.0.4:1080 0 76 2 CONNECT_mtu1280.ams2.test-ipv6.com:443
1670235669.325 SOCK5.31800 00057 user 11.11.11.11:61134 10.8.0.4:1080 0 70 2 CONNECT_ipv6.ams2.test-ipv6.com:443
1670235669.489 SOCK5.31800 00057 user 11.11.11.11:9417 10.8.0.4:1080 0 76 2 CONNECT_mtu1280.ams2.test-ipv6.com:443

**Comment by ffcc999999** [comment]
сори, всё работает, дело было в ВПН, openvpn не поддерживает видимо такую возможность, хоть tcp хоть udp, через wireguard всё сразу заработало!
