### ISSUE TITLE
Как правильно настроить UDP на 3proxy?

### ISSUE THREAD

**Issue by FastSpace123** [3proxy/3proxy#863]
Помогите, что делают не так?

1)Конфиг 3proxy:

```
auth iponly
nserver 192.168.1.1
proxy -n -a -p35575 -i192.168.1.250 -e192.168.1.100
socks -n -a -p25575 -i192.168.1.250 -e192.168.1.100
```

2)В роутере открыл на внешку порт socks5 **25575** UDP и TCP. 

Пробовал подключится из ЛОКАЛЬНОЙ сети. 192.168.1.250:25575
Нет UDP

**Comment by z3APA3A** [comment]
-p это контрольный порт SOCKSv5, он должен быть доступен по TCP. Для UDP для каждого клиентского соединения используется отдельный дополнительный порт UDP, поэтому пробрасывать надо весь диапазон эфемерных портов UDP
Из локальной сети не работает скорей всего потому, что неправильно задал внешний интерфейс, смотри логи.

https://3proxy.ru/howtor.asp#INTEXT

**Comment by FastSpace123** [comment]
> -p это контрольный порт SOCKSv5, он должен быть доступен по TCP. Для UDP для каждого клиентского соединения используется отдельный дополнительный порт UDP, поэтому пробрасывать надо весь диапазон эфемерных портов UDP Из локальной сети не работает скорей всего потому, что неправильно задал внешний интерфейс, смотри логи.
> 
> https://3proxy.ru/howtor.asp#INTEXT

Хорошо, что если у меня в системе несколько сетевых адапетров. Как мне указать UDP от нужного? Или UDP берется со всей системы целиком?

**Comment by ezbik** [comment]
@FastSpace123 https://github.com/3proxy/3proxy/issues/844

**Comment by Boris991420** [comment]
Добрый день. А как можно ограничить диапазон выдачи  эфемерных портов по UDP на стороне 3proxy или  linux?
