### ISSUE TITLE
0.9.4 flagged as a known malware

### ISSUE THREAD

**Issue by levindecaro** [3proxy/3proxy#870]
Hi,
I'd like to report 3proxy 0.9.4 has been flagged as malware "Generic.Application.3Proxy.A.9983B543" from some of security vendor,are there are any workaround to get off from malware signature.?
 
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/36956864/208838125-ee8355b0-dfcd-448e-acf7-807f3c7f8885.png">

**Comment by johnalphared** [comment]
> Few antiviral products inadequately detect 3proxy as Trojan.Daemonize, Backdoor.Daemonize, etc and many detect 3proxy as a PUA (potentially unwanted program). It may cause browser warning on download page. 3proxy is not trojan or backdoor and contains no functionality except described in documentation. Clear explanation of this fact is given, for example, in [Microsoft](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Program:Win32/TinyProxy)'s article.

[https://3proxy.org/](https://3proxy.org/)
