### ISSUE TITLE
3proxy падает при использовании PAM?

### ISSUE THREAD

**Issue by Glebas-PRO** [3proxy/3proxy#871]
**Операционная система:** Linux Ubuntu 22.04 LTS
**Версия 3proxy:** 0.9.3
**Ошибка:** /usr/bin/3proxy: symbol lookup error: /var/lib/3poxy/pamauth.ld.so: undefined symbol: pam_start
**Описание проблемы:**
При попытке использовать PAM-аутентификацию в 3proxy, прокси сервер падает наглухо. При этом `auth strong iponly` прекрасно работает. В логах 3proxy ничего не поялвляется. В systemd нашёл: дек 26 17:19:35 nix-adserver.trainzcity.myftp.org 3proxy[12362]: /usr/bin/3proxy: symbol lookup error: /var/lib/3poxy/pamauth.ld.so: undefined symbol: pam_start.

Как правильно настроить PAM-аутентификацию в 3proxy?

**Comment by z3APA3A** [comment]
Попробуй в основном Makefile добавить -lpam в LIBS
