### ISSUE TITLE
Parent working with HTTPS but not SOCKS5

### ISSUE THREAD

**Issue by APX403** [3proxy/3proxy#873]
Hello,

I have a weird issue using this configuration : 

```
flush
users "user:CL:pass"
allow user* * * * * *
parent 1000 http 127.1.1.1 7777 parent_user parent_port
auto -p21001
```

Using "auto" the HTTP proxy on port 21001 is working but the SOCKS5 one is returning "HTTP error 400".

Do a HTTP parent can support https / socks5 protocol on the child proxy ?

Thanks for you help !

**Comment by APX403** [comment]
I'm still not able to find a solution, is a parent HTTP proxy can support a socks child ?

Thanks for your help

**Comment by z3APA3A** [comment]
Use connect / connect+ parent proxy type rather than http. Or, if parent does not support connect to port 80 
allow * * * 80
parent 1000 http ....
allow *
parent 1000 connect ...
