### ISSUE TITLE
Проблема с чтением большого файла passwd

### ISSUE THREAD

**Issue by savenko-egor** [3proxy/3proxy#874]
Здравствуйте.

Скажите, пожалуйста, возможно ли то, что файл с пользователями и их паролями читается не полностью когда в файле много записей?

Имею сервер на 3proxy версии 0.9.4. Файл паролей содержит ~3000 строк. Для теста был добавлен пользователь сначала в конец файла, а потом в начало.
В случае если запись пользователя находилась в конце файла, при авторизации на сервере в логах отображалась ошибка **00005**.
`Jan 09 11:43:15.901 PROXY.3128 00005 user ip_address:44496 0.0.0.0:0 0 0 0 CONNECT 2ip.io:443 HTTP/1.1`

Когда запись пользователя находилась в начале файла, то пользователь успешно проходил авторизацию на сервере.

Конфиг:
```
nscache 65536
nserver 8.8.8.8
nserver 8.8.4.4

config /conf/3proxy.cfg
monitor /conf/3proxy.cfg

log /logs/3proxy-%y%m%d.log D
rotate 60

logformat "L%o %d %H:%M:%S.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"

maxconn 3000

users $/conf/passwd

include /conf/counters
include /conf/bandlimiters

auth strong
deny * * 127.0.0.1
allow *
proxy -n
flush
```

По траффику видно что запрос на прокси уходит с правильными данными доступа, но ответ 407.
![Screenshot_20230109_142239](https://user-images.githubusercontent.com/38104662/211307133-766713e4-2272-4743-91a3-a0f79ba59023.png)

Спасибо.

**Comment by z3APA3A** [comment]
Для инлайн подстановок через $ ограничение на размер файла 64К, можно разбить файл на несколько и включить через несколько команд users

**Comment by savenko-egor** [comment]
А есть ли ограничение на размер главного конфигурационного файла?
Я к тому, если я перенесу всех пользователей из отдельного файла, в главный конфиг, будет ли это нормально работать?

**Comment by z3APA3A** [comment]
Есть ограничение на длину строки, но можно задавать каждого пользователя отдельной строкой.
Можно не переносить в главный конфиг, а добавить во включаемом файле перед каждым пользователем users и вместо
users $/conf/passwd
сделать
include /conf/passwd

Но вообще я бы не рекомендовал использовать такие большие списки пользователей, можно использовать внешнюю аутентификацию через pam или radius.

**Comment by savenko-egor** [comment]
Спасибо. Я понял.
