### ISSUE TITLE
3proxy дропает первые 1-5 коннектов в реверсе, помогите разобраться

### ISSUE THREAD

**Issue by dzatona** [3proxy/3proxy#876]
Привет. Конфиг следующий:

**1. Стоит машина за NATом, имеет IP 10.8.0.2 на ней запущен инстанс 3proxy, конфиг:**

```
nscache 65536
nserver 1.1.1.1
nserver 8.8.8.8
users <username>:CL:<password>
auth strong
allow <username>
socks -r10.8.0.1:1234 -De<interface>
proxy -r10.8.0.1:1236 -De<interface>
```

**2. Вторая машина (публичный сервер; имеет IP 10.8.0.1), имеет следующий конфиг:**

```
auth iponly
allow * * 10.8.0.2
tcppm -R0.0.0.0:1234 3128 10.8.0.2 3128
tcppm -R0.0.0.0:1236 3130 10.8.0.2 3130
```

Адресация локальная, т.к. трафик инкапсулируется в stateless-туннель. Проблема заключается в том, что при обращении на `<ip>:<port>` публичного сервера, первые 1-5 попыток соединиться не являются успешными. Потом оно заводится и далее начинает работать стабильно. Подскажите, почему так происходит, и как пофиксить?

Спасибо.

**Comment by dzatona** [comment]
@z3APA3A подскажете?

**Comment by z3APA3A** [comment]
Что в логах на обоих серверах?

**Comment by dzatona** [comment]
@z3APA3A где именно смотреть (и как включить если не?)

**Comment by fenix957** [comment]
> 

Нужно в конфиг добавить строчку 
log 
Чтобы вывод был в консоль 
log filename 
чтобы вывод был в файл 
А вообще это в документацииесть
