### ISSUE TITLE
fakeresolve problem with parent proxy type "connect"

### ISSUE THREAD

**Issue by basinilya** [3proxy/3proxy#877]
For certain reasons I want to use the CONNECT request even for HTTP sites when using a parent HTTP proxy.
```
fakeresolve

flush
auth iponly
allow *
parent 1000 connect 127.0.0.1 3131
proxy -olSO_REUSEADDR -i127.0.0.1 -p3132
```

Wireshark shows the following request sent by 3proxy:
```
CONNECT 127.0.0.2:80 HTTP/1.0
```

If I change the parent type to "http", it works:
```
GET http://openwrt.lan/ HTTP/1.1
```

I'm using 3proxy-0.9.3

**Comment by z3APA3A** [comment]
Use connect+ instead of connect.
