### ISSUE TITLE
Как ограничивать объем принимаемого трафика для пользователей

### ISSUE THREAD

**Issue by ia21301** [3proxy/3proxy#883]
Здравствуйте, команда countin позволяет установить лимит трафика на день, неделю или месяц. А если возможность утановить лимит для пользователя на 4 дня к примеру, т.е есть ли возможность задать количество дней?

**Comment by z3APA3A** [comment]
Нет, такой возможности нет, можно раз в 4 дня сбрасывать пользовательские счетчики.

**Comment by z3APA3A** [comment]
W - календарная неделя, M - календарный месяц
