### ISSUE TITLE
chroot in Makefile.Linux?

### ISSUE THREAD

**Issue by alexreg** [3proxy/3proxy#884]
What's all this chroot stuff in Makefile.Linux? Why is it trying to install to two different places? I don't see the actual `chroot` command being used anywhere, so it's all pretty confusing.

**Comment by z3APA3A** [comment]
See `chroot` command description in 3proxy documentation.

**Comment by alexreg** [comment]
@z3APA3A Thanks, but maybe I should ask about my end-goal instead... That is, how do I install to a staging area (a custom prefix)? Changing `DESTDIR` doesn't help, because it produces a very strange directory layout, with subdirs like `bin`, `usr/local/3proxy`, and `usr/lib`. I am writing a package manager formula, so it just needs to get staged in a directory with the usual subdirs like `bin`, `lib`, `libexec`, `man`, etc. Usually I would set the `PREFIX` var when calling Make, but this Makefile is different that way...

**Comment by alexreg** [comment]
@z3APA3A I should also say I get `error: unknown type name 'loff_t'; did you mean 'off_t'` when compiling with the Linux file on macOS. But I don't see a macOS Makefile, so not sure what to do...

**Comment by alexreg** [comment]
`Makefile.FreeBSD` could definitely use a configurable prefix as well...

**Comment by z3APA3A** [comment]
3proxy runs chroot'ed by default on Linux. If you can describe directory structure expected for configuration like this or point me to BCPs I can implement it in the next version.

For MacOS use Makefile.FreeBSD

**Comment by alexreg** [comment]
@z3APA3A Ah I see. (Sorry, upon rereading the source I just understood how the install of the chroot stuff works.) Anyway according to the GNU make documentation [here](https://www.gnu.org/prep/standards/html_node/DESTDIR.html) and [here](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html), your `Makefile.Linux` file already looks in good order.

What I would suggest, to enhance compatibility between the different makefiles and make them all more configurable like the Linux one, is to add [all these variables](https://github.com/3proxy/3proxy/blob/862405bdfdeec4798a2ba73c984d89e6de8caa54/Makefile.Linux#L45-L86) (minus the chroot ones for platforms where chroot doesn't exist) to the other makefiles, and also some targets like `install-man`, which only exist in the Linux makefile right now. (The Solaris makefile doesn't even have an `install` target, and the FreeBSD one is not as good as the Linux one in terms of completeness or configurability.)

If you like, I can submit a PR for the above for you to review?
