### ISSUE TITLE
Disconnect the connections which is longer then 60 seconds

### ISSUE THREAD

**Issue by proxyfactory** [3proxy/3proxy#887]
Hello,

I would like to cut the connection if the session is using after 60 seconds.

For example, if the client started a download file, after 60 seconds, connection will kill automaticly.

How can I do this limitation ? Is it possible with default configurations ?

Thank you,

King Regards,

**Comment by z3APA3A** [comment]
You can only limit inactive connections, see `timeouts` directive. Killing active connection after 1 hour does not sound like a good idea
