### ISSUE TITLE
3proxy как заставить слушать определенные адреса

### ISSUE THREAD

**Issue by mvbelik** [3proxy/3proxy#891]
Есть ли возможность настроить 3прокси для локальных адресов? Сейчас картина такая:
tcp        0      0 0.0.0.0:1080            0.0.0.0:*               LISTEN      2835922/3proxy
Необходимо настроить чтобы слушались только локальные адреса?
OS Linux Ubuntu 20.04 версия ПО  3proxy-0.9.4.x86_64

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtor.asp#BIND

**Comment by mvbelik** [comment]
Спасибо, но:
tcp        0      0 172.27.102.1:1080       0.0.0.0:*               LISTEN      1466561/3proxy
tcp        0      0 0.0.0.0:1080            0.0.0.0:*               LISTEN      1466561/3proxy
Как убрать прослушивание 0.0.0.0:1080

**Comment by z3APA3A** [comment]
не запускать на этом порту сервис без указания интерфейса

**Comment by mvbelik** [comment]
Ты имеешт ввиду https://3proxy.ru/howtor.asp#INTEXT ?
