### ISSUE TITLE
Disable pidfile creation in deb package by default

### ISSUE THREAD

**Issue by armanzor** [3proxy/3proxy#893]
3proxy 0.9.4 is installed form deb package with SystemD service support, that doesn'n need pidfile creation. But in default configuration pidfile has been created despite of this commit: https://github.com/3proxy/3proxy/commit/58cf0d8def704dd45b1026ae5579742d7d579eee
After reboot 3proxy directory has been deleting from /var/run by OS and 3proxy cannot start, because it doesn't have rights to create it again for creating pidfile in it

**Comment by z3APA3A** [comment]
https://github.com/3proxy/3proxy/commit/58cf0d8def704dd45b1026ae5579742d7d579eee
