### ISSUE TITLE
Некорректная работа с опциями counter

### ISSUE THREAD

**Issue by LovingFox** [3proxy/3proxy#899]
При использовании _counter_ и _countall_ (_countin_, _countout_) некоректное поведение программы.

Ниже приведен конфиг. У пользователя _user30001_ лимит на 1Мбайт в час. У пользователя _admin_ лимит на 100000Мбайт в месяц.

Пока _user30001_ не израсходует свой лимит, все работает нормально. Но как только _user30001_ израсходует свой 1Мбайт, _3proxy_ встает в ступор: TCP-сессия устанавливается и далее просто зависит. Не работают ни http, ни socks.

И админ-интерфейс так же не работает. Т.е. При заходе на админ-интерфейс запрашивается логин/пароль, но дальше все опять висит.

В логах ничего...

Версия _3proxy_: 0.9.3

```bash
$ cat /etc/3proxy/3proxy.30001.cfg
nserver 8.8.8.8
nserver 77.88.8.8
nscache 65536
timeouts 1 5 30 60 180 1800 15 60

users admin:CL:superadmin
users user30001:CL:password30001
auth cache strong

log
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"

counter /var/log/3proxy/3proxy.30001.3cf M /var/log/3proxy/3proxy.30001.txt
countall 1 M 100000 admin
countall 1 H 1 user30001

allow user30001
proxy -i10.0.0.5 -p30001
socks -i10.0.0.5 -p31001

allow admin
admin -i127.0.0.1 -p30001
```

**Comment by Surfang** [comment]
В версии 0.9.4 такая же проблема на freebsd

**Comment by z3APA3A** [comment]
У тебя два счетчика с одинаковым номером, второй перезаписывает первый при любом рестарте

**Comment by LovingFox** [comment]
[z3APA3A](https://github.com/z3APA3A), к сожалению, проблема не в этом.
В конфиге я допустил просто опечатку.

Конфиг счетчиков такой:
```
countall 1 M 100000 admin
countall 2 H 1 user30001

```
Проблема та же. Повторю ее текст:

Пока user30001 не израсходует свой лимит, все работает нормально. Но как только user30001 израсходует свой 1Мбайт, 3proxy встает в ступор: TCP-сессия устанавливается и далее просто зависит. Не работают ни http, ни socks.

И админ-интерфейс так же не работает. Т.е. При заходе на админ-интерфейс запрашивается логин/пароль, но дальше все опять висит.

В логах ничего...

**Comment by z3APA3A** [comment]
Попробуй использовать текущую версию из мастера, какие-то проблемы со счетчиками за последние годы точно правились.
