### ISSUE TITLE
Не работает SSLPlugin

### ISSUE THREAD

**Issue by Jestergnet** [3proxy/3proxy#900]
`Здравствуйте,` во время использования SSLPlugin получились две проблемы:
1. OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0
2. transfer closed with 11161 bytes remaining to read

Запущено в Debian 11 x64, но при этом запускаю такой же конфиг в Windows 10, то таких проблем нет в обоих случаях.
При этом вторая проблема как будто поток преривается на пустом месте...

В браузере с использованием прокси, идет загрузка сайта, после пары сенкуд ошибка: Ошибка при установлении защищённого соединения

Собирал из исходников, но так же пробовал и deb пакеты, проблема везде одна.

Конфиг:
```
plugin SSLPlugin.dll ssl_plugin
ssl_certcache ssl
ssl_mitm
timeouts 1 5 15 60 180 180 30 60
nserver 8.8.8.8
nserver 8.8.4.4
nscache 65536
auth strong
users admin:CL:admin
allow admin
proxy    -n -a -p3128  -i172.16.2.200 -e172.16.2.200
```

**Comment by z3APA3A** [comment]
SSLPlugin был переписан в мае прошлого года
