### ISSUE TITLE
How to listen to app IPs on a server?

### ISSUE THREAD

**Issue by botzill** [3proxy/3proxy#905]
Hi.

Is it possible to listen to all ips on a server?

I have a server on OVH where I did configure multiple failover IPs and I want to listen to all of them and make proxies.

Thanks for the great tool.

**Comment by z3APA3A** [comment]
By default (or with `internal 0.0.0.0` or `-i0.0.0.0`) 3proxy listens all available IPs or you can bind 3proxy to specific IPs, see https://3proxy.ru/howtoe.asp#BIND
