### ISSUE TITLE
I can't connect to different ports in the same time

### ISSUE THREAD

**Issue by itseyup** [3proxy/3proxy#909]
Hello, I am trying to connect two different ports (eg. 1000, 1020) but whenever I connect to second port, 3proxy crashes itself. There is no crashing log on the log file. My config file is like this:
```
nscache 65536

timeouts 1 5 30 60 180 1800 15 60

users myuser1:CL:myuserpw1 myuser2:CL:myuserpw2

daemon

log /home/myuser/logs.log

authcache user 60

auth strong

allow myuser1
proxy -6 -n -a -p1000 -iMYIPV4 -eMYFIRSTIPV6
flush
allow myuser2
proxy -6 -n -a -p1020 -iMYIPV4 -eMYDIFFERENTIPV6
flush
```

**Comment by z3APA3A** [comment]
See "known system issues" in https://3proxy.ru/highload.asp
and stack size setting in https://3proxy.ru/howtoe.asp#CRASH.
Usually, setting "nserver" fixes the issues. Also, in you configuration nscache6 is expected.

**Comment by itseyup** [comment]
Can I add this nameserver below `log`? Also, the `nscache` command should be like this? `nscache6 65536`
````
nserver 8.8.8.8
nserver 8.8.4.4
```

**Comment by itseyup** [comment]
@z3APA3A

**Comment by z3APA3A** [comment]
Yes, unless you need a large number of users. For high load, I do not recommend to use public resolvers, see the same article.

**Comment by itseyup** [comment]
The problem is still ongoing. I added nserver, stacksize but it didn't work. I have updated my current config.

**Comment by itseyup** [comment]
@z3APA3A

**Comment by z3APA3A** [comment]
Check you use actual supported version. Send logs, configuration, binaries and crashdump to 3proxy@3proxy.ru,
