### ISSUE TITLE
Не работаю звонки в WhatsApp

### ISSUE THREAD

**Issue by garik-code** [3proxy/3proxy#912]
Бро, в чем проблема? Конфиги?

**Comment by garik-code** [comment]
Идет гудок и дальше нет соединения

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtor.asp#ERRORS

**Comment by z3APA3A** [comment]
Ошибка 4 - клиент не отправляет имя/пароль, можно попробовать использовать
`socks -u2`

**Comment by z3APA3A** [comment]
И за NAT он в общем случае может не работать, в зависимости от реализации NAT и того как UDPPM используется в клиентском приложении
