### ISSUE TITLE
about timeouts config

### ISSUE THREAD

**Issue by hunterhe23** [3proxy/3proxy#913]
does SHORT reffer to http_proxy and LONG reffer to socks_proxy?

and what does BYTE/STRING/CONNECTION mean? 
would you please show me an example.

thanks.

**Comment by z3APA3A** [comment]
BYTE is timeout for single byte within protocol, STRING for string buffer, CONNECTION SHORT - for short living connection timeout (e.g. waiting for command), CONNECTION LONG - for established connections (e.g. HTTP CONNECT or SOCKS CONNECT)

**Comment by z3APA3A** [comment]
Shorter timeouts are used on the stream with small buffer reads, where no delays are expected.

**Comment by hunterhe23** [comment]
sorry, i don't quite understand.
when curl -x 3proxy_ip:3128 http://www.abc.com, which timeout parameter will take effect?

**Comment by z3APA3A** [comment]
There is no single timeout, different timeouts are used for different operations, e.g. DNS resolution, header line reading, pipelined command waiting, etc.
You can check the code for HTTP specific timeouts here
https://github.com/3proxy/3proxy/blob/master/src/proxy.c
and for common timeouts https://github.com/3proxy/3proxy/blob/master/src/common.c and https://github.com/3proxy/3proxy/blob/master/src/auth.c
