### ISSUE TITLE
Фильтрация DNS-имен по шаблону

### ISSUE THREAD

**Issue by JMKh3r** [3proxy/3proxy#914]
Возможно ли сделать что-то типа этого?

nsrecord *.vk.com 127.0.0.2

То есть чтобы все поддомены домена vk.com разрешались в 127.0.0.2.

**Comment by z3APA3A** [comment]
allow * * *.vk.com
parent 1000 tcp 127.0.0.2 0

**Comment by JMKh3r** [comment]
> allow * * *.vk.com parent 1000 tcp 127.0.0.2 0

Не, если используется только dns-прокси, но не используется http-прокси.
То есть, если 3proxy используется только как dns-сервер.
