### ISSUE TITLE
Passive OS fingerprint masking (TCP/IP Fingerprint)

### ISSUE THREAD

**Issue by smowtion** [3proxy/3proxy#915]
It's possible to detect an operating system of a device by analyzing its network traffic. Different implementations of the TCP/IP stack in operating systems help to determine which OS generated the package. In this context, a set of operating system-specific package parameters is called an OS fingerprint. Since this method involves observing passing traffic without sending any requests, it is called passive OS fingerprinting.

You can check this fingerprint on [browserleaks.com/ip](https://browserleaks.com/ip) under "TCP/IP Fingerprint". In Multilogin you may encounter the following results:

A proxy server intercepts your network packages and repacks them, that's why if you use a proxy, the above test may show an OS different from your original one (for example, Linux)
If you use Multilogin on a VM, the above test may show your original OS regardless of the OS selected in the [profile settings](https://docs.multilogin.com/l/en/article/ymlhur08ng-forbid-multi-start) (for example, if your original OS is macOS, the TCP/IP Fingerprint may show macOS even on a Windows VM with a Windows browser profile)
TCP/IP fingerprint is a connection fingerprint, and Multilogin cannot affect it in any way. Websites for the most part ignore this parameter, since mismatches between TCP/IP Fingerprint and actual OS are common in normal traffic. They are caused by certain network devices and configurations.
This is proxy
![This is proxy](https://i.imgur.com/IkERag9.png)

This is without proxy
![This is without proxy](https://i.imgur.com/GqABSLi.png)

**Comment by janisblaus** [comment]
@smowtion you probably want to use something like https://github.com/janisblaus/OSfooler-ng

**Comment by z3APA3A** [comment]
Proxy does not "intercept network packets", proxy acts on application layer& It can change some socket options, but it can not change OS fingerprint in general case.
