### ISSUE TITLE
DNS Flag?

### ISSUE THREAD

**Issue by thisisclint21** [3proxy/3proxy#916]
Hi,

We want to use a custom DNS server for block some websites, how its possible to differenciate proxies? does its possible to specify any flag?

Regards

**Comment by thisisclint21** [comment]
Let me add few more information @z3APA3A

I just want to build a custom DNS server and filter websites depending of which proxy/port is calling it, so for this I need to distinguish who is who,

Do you think its possible?

**Comment by z3APA3A** [comment]
You can use `nserver` / `nserver6` to set DNS server used by proxy.

**Comment by thisisclint21** [comment]
Yes but how to distinguishes proxies from the DNS side?

Thank you for your time
