### ISSUE TITLE
How to counter parent weight 

### ISSUE THREAD

**Issue by smowtion** [3proxy/3proxy#917]
Hello
I have 3 or 7 random parent. I set all weight to 1000 or 1000/3 but not random parent or not working  

auth iponly
allow *
parent 1000 http 10.1.1.101 0
parent 1000 http 10.2.1.101 0
parent 1000 http 10.3.1.101 0

But one get from  10.1.1.101 not radom with all parent 

if I set 
parent 300 http 10.1.1.101 0
parent 300 http 10.2.1.101 0
parent 300 http 10.3.1.101 0
will not working

Can you help me setup

**Comment by z3APA3A** [comment]
Use 333+333+334 because sum weight of parents must be even of 1000. Also, check the port number of parent proxy, 0 is probably not what you really need.
