### ISSUE TITLE
Socks5 connect to parent IPv6

### ISSUE THREAD

**Issue by smowtion** [3proxy/3proxy#919]
Hello
parent 1000 http 123.456.758 12344 user pass
socks -p15000 -u

parent is http Ipv6 proxy . 
but I connect not success if I settup socks5 in port 15000
but if set proxy it's working. 

Thanks

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtoe.asp#ERRORS

14 means getpeername() failure, usually it happens if remote side (123.456.758 in your example) closes connection immediately after connect.
