### ISSUE TITLE
Проблема с UDP, bind()

### ISSUE THREAD

**Issue by ffcc999999** [3proxy/3proxy#920]
Сервер за NAT двойным, если можно так сказать.
1 роутер с внешним IP, прописан DMZ на IP второго роутера, на первом разрешены все подключения.
На втором сделан проброс определенных TCP портов уже на сам сервер и полный проброс UDP на сервер.
Но при подключеннии по UDP я вижу ошибку
1682858016.090 SOCK5.22010 00012 uthz22010 65.21.19.162:37846 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0
1682858016.115 SOCK5.22010 00012 uthz22010 65.21.19.162:37844 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0

Работает это следующим образом, через tun2socks поднят интерфейс и подключается к прокси, через него шлются запросы в DNS, в tun2socks

INFO[4948] [UDP] 10.9.1.1:51612 <-> 8.8.8.8:53
INFO[4948] [UDP] 10.9.1.1:50531 <-> 8.8.8.8:53
INFO[4948] [UDP] 10.9.1.1:64369 <-> 8.8.8.8:53

запускаю прокси так, но пытался уже по всякому
socks -NВНЕШНИЙ_IP -p22010 -i192.168.88.254 -e192.168.11.100

192.168.88.254 - мой сервер.
192.168.10.100 - второй интерфейс с интернетом, там есть UDP, вешал на него vpn сервер отдельно и всё в порядке.

С чем может быть связана эта ошибка и что делать.

**Comment by ezbik** [comment]
>NAT двойным

на каждом NAT надо прокидывать UDP.

**Comment by ffcc999999** [comment]
> > NAT двойным
> 
> на каждом NAT надо прокидывать UDP.

так сказал же, UDP работает, я проверял через ВПН сервер, где он точно работает без бубнов) теперь хочу через прокси, но ошибка возникает бинда адреса.

**Comment by ffcc999999** [comment]
если я создам интерфейс с адресом внешним, просто как бы фиктивный, ошибки нет, но и подключения тоже, т.к по факту этот ип не принадлежит серверу для выхода в интернет

**Comment by ezbik** [comment]
>UDP работает, я проверял через ВПН

явно вы проверяли с фиксированным портом, а socks5 использует рандомные порты из широкого диапазона. Вот и все их и надо прокидывать.

**Comment by ffcc999999** [comment]
> > UDP работает, я проверял через ВПН
> 
> явно вы проверяли с фиксированным портом, а socks5 использует рандомные порты из широкого диапазона. Вот и все их и надо прокидывать.

они все прокинуты, на первом включен DMZ и на файрволе разрешены все коннекты, на втором прокинут весь UDP на сервер, через dst-nat, работает любой порт при проверке.

**Comment by ffcc999999** [comment]
вы не читаете ошибку которую я показал в начале, 00012 ошибка привязки, которой быть не должно

**Comment by ffcc999999** [comment]
если убрать -NВНЕШНИЙ_IP то никаких ошибок нет, но и UDP тоже не проходит

**Comment by ffcc999999** [comment]
да печально, так как поднял на простом vps без NAT и UDP заработал сразу, через NAT не хочет, при указании -N параметра который я так понял нужен для указания внешнего сервера для клиента, получается ошибка бинда, нашел что это еще с 2021 года и так и не решено.

**Comment by z3APA3A** [comment]
00012 при подключении означает что external задан неправильно, убедись что такой ip действительно сконфигурирован, например ifconfig'ом https://3proxy.ru/howtor.asp#INTEXT

-N в настоящее время не поддерживается, как будет работать через NAT'ы без него зависит от клиента и операции

**Comment by ffcc999999** [comment]
> 00012 при подключении означает что external задан неправильно, убедись что такой ip действительно сконфигурирован, например ifconfig'ом https://3proxy.ru/howtor.asp#INTEXT
> 
> -N в настоящее время не поддерживается, как будет работать через NAT'ы без него зависит от клиента и операции

так external задан IP usb модема, и всё чудесно работает по TCP, он действительно сконфигугирован, ошибка 12 только на UDP коннектах
