### ISSUE TITLE
My script working with only 1 ipv6

### ISSUE THREAD

**Issue by xploader** [3proxy/3proxy#923]
Hello! I'm trying to create from a Ubuntu server multiple ipv6 proxy. My server have and ipv6 like this 2a01:2ff:f0:3631::/64, and i'm trying to create multiple ipv6 proxy.
This is my config that is working with 1 ipv6

```
nserver 8.8.8.8
nserver 8.8.4.4
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
daemon
auth strong
users admin:CL:ZXC123
allow xp
proxy -6 -n -a -p3128 -i5.161.89.78 -e2a01:2ff:f0:3631::1
```
And if I add one more proxy 
`proxy -6 -n -a -p3127 -i5.161.89.78 -e2a01:2ff:f0:3631::2`
it is not working..

The only ipv6 that is working is when I set it 2a01:2ff:f0:3631:1

Any idea why is so?

**Comment by z3APA3A** [comment]
Check every address you use is local and is assigned to interface. You can check you can use this address e.g. with
nc -v -s SOURCE_IP DESTINATION_IP DESTINATION_PORT
