### ISSUE TITLE
LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to <url> error

### ISSUE THREAD

**Issue by Eimis** [3proxy/3proxy#924]
Might be a duplicate of https://github.com/3proxy/3proxy/issues/628

Hey,

I have a Rasbperry Pi with a 4G USB Dongle connected to it and my goal is to set up a very basic proxy and connect to it from anywhere outside of my network using username/password.

I did everything [according to this article](https://www.blackhatworld.com/seo/diy-how-to-create-your-own-4g-proxy.1234185/), set up port forwarding on my router and everything seems to work fine. When I do this **inside of** Raspberry Pi, it seems to work:

```
curl ifconfig.co/
returns modem's IP

curl ifconfig.co/ --interface usb0
returns different IP from USB dongle
```

Also, `ifconfig` shows different IP for `usb0` interface, which is good.

Although, when I do this from anywhere outside like this:

`curl --proxy http://username:pass@raspberry_pi_ip:port https://wtfismyip.com/text`

... it's giving me such error:

**`curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to wtfismyip.com:443`**

In both cases (when using curl inside of Rasperry Pi or in some other machine) I can see in 3proxy logs that it reaches 3proxy:

`230505075436.597 3128 00096 skylark1 31.44.103.201:51211 15.204.2.228:443 0 0 0 CONNECT wtfismyip.com:443 HTTP/1.1`

My iptables entries look like this:

```
sudo ip route add 192.168.0.0/24 dev usb0 src 192.168.0.100 table gw1
sudo ip route add default via 192.168.0.1 dev usb0 table gw1
sudo ip rule add from 192.168.0.100/32 table gw1
sudo ip rule add to 192.168.0.100/32 table gw1
```

Could anybody point me to the right direction? What could this `curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to wtfismyip.com:443` error mean?

**Comment by Eimis** [comment]
Here are some verbose logs from `curl` that might be helpful:

```
*   Trying 31.44.103.201:3128...
* Connected to saulelydis.tplinkdns.com (31.44.103.201) port 3128 (#0)
* allocate connect buffer
* Establish HTTP proxy tunnel to wtfismyip.com:443
* Proxy auth using Basic with user 'skylark1'
> CONNECT wtfismyip.com:443 HTTP/1.1
> Host: wtfismyip.com:443
> Proxy-Authorization: Basic c2t5bGFyazE6dEU4YzhERTlQc3dmN0JZQ1pxZTQ=
> User-Agent: curl/7.87.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.0 200 Connection established
<
* CONNECT phase completed
* CONNECT tunnel established, response 200
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to wtfismyip.com:443
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to wtfismyip.com:443
```

**Comment by z3APA3A** [comment]
What is your 3proxy config?

**Comment by Eimis** [comment]
> What is your 3proxy config?

Pasting it:

```
#! /usr/local/bin/3proxy

daemon

nserver 8.8.8.8

nscache 65536

timeouts 1 5 30 60 180 15 60

users skylark1:pass

log /var/log/3proxy.log

rotate 30

setgid 13

setuid 13

auth strong

allow skylark1

proxy -p3128 -e192.168.0.100

flush
```

**Comment by z3APA3A** [comment]
--interface usb0 selects interface, -e192.168.0.100 selects IP address, rather then interface. Under Llinux it's not the same thing. You must either configure source route to route source traffic from 192.168.0.100 via usb0 or bind interface, see -De option https://3proxy.ru/doc/man3/3proxy.cfg.3.html

This option does not work with setgid.

**Comment by Eimis** [comment]
@z3APA3A thanks, binding to `usb0` seemed to help!
