### ISSUE TITLE
iponly авторизация из под VPN

### ISSUE THREAD

**Issue by mobileproxy** [3proxy/3proxy#925]
Здравствуйте, подскажите пожалуйста.

Есть сервер с установленным 3proxy на котором 5 соединений, каждый для своего пользователя.
Перед сервером стоит VPN 
Клиенты подключаются к VPN, он переадресовывает их на сервер с 3proxy? а тот направляет по нужному соединению
У каждого клиента стоит авторизация по IP, соответственном в момент когда они проходят через VPN ip меняется и авторизация не срабатывает.
У каждого клиента свой IP который указан в авторизации.

Существует ли возможность и если да то какая заставить работать по такой схеме?
Если нет, то что можно сделать, что бы было наиболее надежно, заменить VPN? Какой то особенный протокол? Заменить на прозрачный прокси? Модифицировать авторизацию 3proxy iponly? Написать свой плагин авторизации?

Важно: Обязательно должен остаться сервер посредник между клиентом и 3proxy и должна использоваться авторизация по IP для прокси
Спасибо.

**Comment by z3APA3A** [comment]
Убери NAT между прокси и VPN если он есть, настрой маршрутизацию и сделай статическое назначение IP адресов клиентам VPN.
