### ISSUE TITLE
Ubuntu 20.04 SSLPlugin Error

### ISSUE THREAD

**Issue by Naota-Sensei-1** [3proxy/3proxy#930]
Доброго времени суток!
При сборке такие ошибки, уже не знаю что делать.

Package: libssl1.1
Version: 1.1.1f-1ubuntu2.18
3proxy 0.9.4

ssl_plugin.c: In function ‘ssl_plugin’:
ssl_plugin.c:399:17: warning: assignment to ‘size_t (*)(int,  const void *, size_t,  int)’ {aka ‘lon
 const void *, size_t,  int)’ {aka ‘int (*)(int,  const void *, long unsigned int,  int)’} [-Wincomp
  399 |   pl->so->_send = ssl_send;
      |                 ^
ssl_plugin.c:400:17: warning: assignment to ‘size_t (*)(int,  void *, size_t,  int)’ {aka ‘long unsi
e_t,  int)’ {aka ‘int (*)(int,  void *, long unsigned int,  int)’} [-Wincompatible-pointer-types]
  400 |   pl->so->_recv = ssl_recv;
      |                 ^
ssl_plugin.c:401:19: warning: assignment to ‘size_t (*)(int,  const void *, size_t,  int,  const str
uct sockaddr *, unsigned int)’} from incompatible pointer type ‘int (*)(int,  const void *, size_t,
truct sockaddr *, unsigned int)’} [-Wincompatible-pointer-types]
  401 |   pl->so->_sendto = ssl_sendto;
      |                   ^
ssl_plugin.c:402:21: warning: assignment to ‘size_t (*)(int,  void *, size_t,  int,  struct sockaddr
ed int *)’} from incompatible pointer type ‘int (*)(int,  void *, size_t,  int,  struct sockaddr *,
ompatible-pointer-types]
  402 |   pl->so->_recvfrom = ssl_recvfrom;

**Comment by Palymer** [comment]
Обновить либы у убунту

**Comment by z3APA3A** [comment]
Это ворнинги, а не ошибки
