### ISSUE TITLE
Proxy not working with Chrome

### ISSUE THREAD

**Issue by ltrtuan** [3proxy/3proxy#934]
Hi @z3APA3A 
I installed 3proxy in my vps, then i checked by proxycheker
The proxy works normally
But when i use it on Chrome (using SwitchyOmega) , i cannot access any website
![image](https://github.com/3proxy/3proxy/assets/4776640/77493941-4dbf-4c52-a05a-3c41c675911d)
![image](https://github.com/3proxy/3proxy/assets/4776640/8801a896-b584-4725-9389-87eebfd3d82b)

What is my problem?
Thanks so much

**Comment by ezbik** [comment]
why HTTPS?

**Comment by ltrtuan** [comment]
> why HTTPS?

thanks so much. i set it to HTTP and it works now
