### ISSUE TITLE
Config 3proxy with IPv6

### ISSUE THREAD

**Issue by ltrtuan** [3proxy/3proxy#935]
Hi there
This is my ipv6 address in my VPS
![image](https://github.com/3proxy/3proxy/assets/4776640/5e51a9ad-c709-482e-a4c4-72058726ab30)
I want to config like this
proxy -pPORT_NUMBER -iIP_V4 -eIP_V6
but i don't know exactly what is my IPv6 address and how my ip v6 work
I curl to a website by Ip v6 option, but it does not work
![image](https://github.com/3proxy/3proxy/assets/4776640/7ef88947-8c5d-439a-9413-5c902a6c4568)

**Comment by ltrtuan** [comment]
> Use
> 
> proxy -pPORT_NUMBER -iIP_V4 -6
> 
> if you want IPv6 only proxy and you do not need to bind to exact address.

Thanks for supporting
But seemly my ip v6 address doesn't work, right ? Can you help me explain why is it not working?

**Comment by z3APA3A** [comment]
What do you have in logs?

**Comment by z3APA3A** [comment]
You use curl without proxy and it fails, so you have networking issues unrelated to proxy.
