### ISSUE TITLE
Cannot update file /etc/3proxy/3proxy.cfg

### ISSUE THREAD

**Issue by ltrtuan** [3proxy/3proxy#937]
Hi there
After installed 3proxy, the configuration file is automatically generated /etc/3proxy/3proxy.cfg
And this is content of the file
![image](https://github.com/3proxy/3proxy/assets/4776640/49ea3209-77ca-4c32-b88e-8d9072c39e26)
I want to remove the <200b> character, but it doesn't work, after saved , it revert to original file (i use Vi editor)
My questions are:
1/ How can i remove <200b> character in /etc/3proxy/3proxy.cfg file
2/ I saw in the content of 3proxy.cfg, it automatically config for me (it's great), but i want to change the port, the username, the password, how should i do
Thanks so much

**Comment by z3APA3A** [comment]
3proxy never reverts config file and does not keep it open unless `writable` command is specified, probably you do not save your changes after editing.
