### ISSUE TITLE
counter and 3proxy stop/start

### ISSUE THREAD

**Issue by nevstas** [3proxy/3proxy#941]
I have set traffic limit 50Mb/month for each user.

User 'admin' downloaded 30 mb
After that I have restarted 3proxy
```
/etc/init.d/3proxy stop
/etc/init.d/3proxy start
```
After that user 'admin' downloaded 30 mb again
After that I have restarted 3proxy
After that user 'admin' downloaded 30 mb again
...Repeat many times
Why '3proxy.counter' doesn't collect data after restart?
But if user 'admin' downloaded at a time 50 mb he will be blocked.
I want user 'admin' can download 30Mb, restart, and 20Mb. But not 30Mb+restart+30Mb+restart+30Mb+...

Я установил лимит траффика 50Мб/месяц для каждого пользователя.
Пользователь админ потребил 30 Мб.
После этого я перезагрузил прокси.
После того пользователь админ потребил еще 30 Мб.
После этого я перезагрузил прокси.
После того пользователь админ потребил еще 30 Мб.
Итак до бескончености.
Почему '3proxy.counter' не верно считает траффик после перезагрузки?
Но если пользователь админ потребит 50 Мб за раз, то он будет заблокирован.
Я хочу чтобы пользователь админ потребил 30 Мб, перезагрузка, 20 Мб. Но не 30Мб+перезагрузка+30Мб+перезагрузка+30Мб+...

Version 0.9.4
Here my conf:
```
nserver 8.8.8.8
nscache 65536

daemon

counter "/etc/3proxy/3proxy.counter" H "/etc/3proxy/3proxy.log"
countall 1 M 50 admin
countall 2 M 50 admin2

timeouts 10 15 30 60 180 1800 15 60

auth strong
users admin:CL:pass
users admin2:CL:pass
allow admin * * * * * *
allow admin2 * * * * * *
proxy -n -a -p24531 -i194.163.182.32 -e194.163.182.32
socks -n -a -p24530 -i194.163.182.32 -e194.163.182.32
flush
```

**Comment by z3APA3A** [comment]
It means proxy fails to create and/or write counters file, check /etc/3proxy/3proxy.counter can be created/updated.

**Comment by nevstas** [comment]
I have set 777 to "3proxy.counter" and it is working well. Thanks!

Я установил права 777 на файл "3proxy.counter" и теперь работает как надо. Спасибо!
