### ISSUE TITLE
При долгой работе возникают "белые страницы"

### ISSUE THREAD

**Issue by Palymer** [3proxy/3proxy#942]
Конфиг выглядит данным образом, написана автоматизация с использованием bash скриптов для генерации ipv6 адресов и портов на подсети /51:

daemon
maxconn 1500
nserver 77.88.8.8
nserver 1.1.1.1
nscache 65536
nscache6 65536
setgid 65535
setuid 65535
flush
auth strong
users admin:CL:passwd
allow admin
internal 193.xxx.xx.xx
proxy -6 -n -a -p7000 -eIPV6ADDR
proxy -6 -n -a -p7001 -eIPV6ADDR
proxy -6 -n -a -p7002 -eIPV6ADDR
proxy -6 -n -a -p7003 -eIPV6ADDR
proxy -6 -n -a -p7004 -eIPV6ADDR

Через некоторое время начинаются глюки и лаги 3прокси, страницы перестает грузить и выдает ошибки соединения (либо просто белые страницы)

P.S. Ротация работает так же через bash скрипт, генерируется 1500 адресов и перезапускается 3proxy с использованием команд завершения процессов юзера 65535 (каждые 10 минут)
P.P.S. Дополнительно при каждой ротации чищу кеш ядра и файловый

**Comment by z3APA3A** [comment]
Прочитай https://3proxy.ru/highload.asp в частности про ulimit'ы (в дефолтные ты не влазишь) и про то, как правильно обновлять конфигурацию, т.к. возможно ты ловишь рейсы на обновлении и про использование публичных DNSов

**Comment by Palymer** [comment]
limits.conf
* soft nofile 500000
* hard nofile 500000

system.conf и user.conf
DefaultLimitDATA=infinity
DefaultLimitSTACK=infinity
DefaultLimitCORE=infinity
DefaultLimitRSS=infinity
DefaultLimitNOFILE=102400
DefaultLimitAS=infinity
DefaultLimitNPROC=10240
DefaultLimitMEMLOCK=infinity

sysctl.conf
net.ipv6.conf.ens3 .proxy_ndp=1
net.ipv6.conf.all.proxy_ndp=1
net.ipv6.conf.default.forwarding=1
net.ipv6.conf.all.forwarding=1
net.ipv6.ip_nonlocal_bind = 1
vm.max_map_count=95120
kernel.pid_max=95120


Забыл упомянуть, стоит еще ndppd (без него не заводилось)
route-ttl 30000
proxy ens3 {
   router no
   timeout 500   
   ttl 30000
   rule xxxx:xxxx:xxxx::/48 {
      static
   }
}

**Comment by z3APA3A** [comment]
что в логах?

**Comment by z3APA3A** [comment]
P.S. в parent extip можно указать IPv6 сеть, будет выбираться рандомный адрес

**Comment by Palymer** [comment]
> P.S. в parent extip можно указать IPv6 сеть, будет выбираться рандомный адрес

Спасибо за наводку, еще бы узнать как точно вводить значения)

> что в логах?

уже выяснил, что это лимиты на днс серверах

**Comment by z3APA3A** [comment]
allow * * ::/0
parent 1000 extip IPv6/cidr
