### ISSUE TITLE
Может ли 3proxy работать с паролями в digest формате?

### ISSUE THREAD

**Issue by Shekelshtein** [3proxy/3proxy#944]
Подскажите, имеется ли такой функционал, и если да - как правильно указать список пользосателей с паролями, просто как файл? 
users $/etc/3proxy/auth.digest

**Comment by z3APA3A** [comment]
только с MD5

`users testuser "CR:$1$salt$No6gqynaE4urT3jScs91F/"`

**Comment by Shekelshtein** [comment]
Спасибо за ответ!
