### ISSUE TITLE
Ошибки в логах

### ISSUE THREAD

**Issue by Palymer** [3proxy/3proxy#946]
После долгого чтения пришел к такому выводу:
собрал отдельно bind9 сервер с прокси

Конфиг привел к такому варианту на всех серверах (их несколько, каждый на 4к портов прокси), подсеть одна:
log /root/logs/proxy.log C
logformat "L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
rotate 20
maxconn 5200
nobandlimin * * * *
nobandlimout * * * *
noconnlim * * * *
nocountall * * * *
nserver ip_proxy_bind9
nserver 1.1.1.1

flush
auth strong
users login:CL:pass
allow login
proxy -n -a -6 -eipv6 -p10000 -osTCP_NODELAY -s0

В логах часто мелькают ошибки 00100 и 00095, помогите разобраться -___-

**Comment by Palymer** [comment]
После долгого чтения пришел к такому выводу:
собрал отдельно bind9 сервер с прокси

Конфиг привел к такому варианту на всех серверах (их несколько, каждый на 4к портов прокси), подсеть одна:
log /root/logs/proxy.log C
logformat "L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
rotate 20
maxconn 5200
nobandlimin * * * *
nobandlimout * * * *
noconnlim * * * *
nocountall * * * *
nserver ip_proxy_bind9
nserver 1.1.1.1

# клиент1
flush
auth strong
users login:CL:pass
allow login
proxy -n -a -6 -eipv6 -p10000 -osTCP_NODELAY -s0

В логах часто мелькают ошибки 00100 и 00095, помогите разобраться -___-

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtor.asp#ERRORS
100 - незарезолвилось имя
95 - отвалился клиент
небольшое количество 95х может быть по естественным причинам (например пользователь закрыл браузер), если ошибок много, особенно 100х ищи проблему в сети или сетевых ресурсах
