### ISSUE TITLE
Origin IP shown

### ISSUE THREAD

**Issue by x011** [3proxy/3proxy#950]
I've the following `3proxy.cfg` and it works fine, for the most part.

```
nserver 8.8.8.8
nserver 8.8.4.4
auth iponly
allow * x.x.x.x,x.x.x.x
include /conf/parents.txt
proxy -p56111 -u -a -n
flush
```
`/conf/parents.txt` contains a list of 400 remote proxies and each line is similar to:

`parent 2.5 http x.x.x.x xxx`

2.5 * 400 = 1000, which should be correct, right?

Most of the time, the visible IP is the remote proxy IP, which is correct, but on some requests, the IP shown is the local proxy IP, something that shouldn't happen. 
Any idea why this behavior?
Thank you.

**Comment by z3APA3A** [comment]
parent only accepts integer number as a weight, 2*400 = 800.
