### ISSUE TITLE
увеличить counter

### ISSUE THREAD

**Issue by skmachine** [3proxy/3proxy#954]
Добрый день, есть ли штатные методы инкрементить счетчик? Предположим, у пользователя есть 100 мб, требуется добавить еще 50 мб, не потеряв при этом счетчик уже использованного трафа. Изменение лимита в конфиге вызывает сброс счетчика..

```
countall "all/user1" * 100 user1
countin "in/user1" * 100 user1
countout "out/user1" * 100 user1
```

**Comment by z3APA3A** [comment]
Счетчикам надо задать номера, под этими номерами они сохраняются в файл, который задан командой counter. Если номера не задать, то счетчики не могут сохраниться, а потому и сбрасываются. 
countall "1/all user1" ...
