### ISSUE TITLE
How can I configure different ip for each user

### ISSUE THREAD

**Issue by thanhvodad** [3proxy/3proxy#955]
I can't open multiple ports, so I want to configure to use 1 port, with many different users, and each user is an IP
-PORT: 13000
-USER: user1, user2
With the below config file I can't run, please help

`daemon
maxconn 99999
nserver 8.8.8.8
nserver 8.8.4.4
nserver 2001:4860:4860::8888
nserver 2001:4860:4860::8844
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
setgid 65535
setuid 65535
stacksize 6291456

users user1:CL:123123 user2:CL:123123 
auth strong cache

allow user1
proxy -6 -n -a -p13000 -i12.110.37.10 -eIPV6::1

allow user2
proxy -6 -n -a -p13000 -i12.110.37.10 eIPV6::2
flush`

**Comment by z3APA3A** [comment]
```
allow user1
parent 1000 extip IP1
allow user2
parent 1000 extip IP2
proxy -p11
```
