### ISSUE TITLE
Prevent outbound connections directly to IP address (without hostname)

### ISSUE THREAD

**Issue by icmono** [3proxy/3proxy#956]
Hello

Is there a way to prevent clients from connecting directly to an IP address when using socks?
This will be helpful in order to force clients to specify a hostname and then do filtering at the DNS level.

**Comment by z3APA3A** [comment]
deny * * *1,*2,*3,*4,*5,*6,*7,*8,*9,*0

**Comment by icmono** [comment]
It worked perfectly with deny * * *1,*2,*3,*4,*5,*6,*7,*8,*9,*0
For some reason "pcre request" doesn't seem to work with socks. Tried using "pcre clidata" but it also behaves weirdly. I tried a bunch of regexp matches, including specific strings.

Also tested pcre with HTTP proxy and all works well.

Anyway it solved my issue. Thank you for the help.
I'll add a comment with what I've tested with pcre and socks.

**Comment by icmono** [comment]
I ended up using a generic regexp match:
`pcre clidata deny ".*\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}.*"`

`curl -x socks5://socks.domain.tld:1080 1.1.1.1`
Matches: Request blocked

`curl -x socks5h://socks.domain.tld:1080 one.one.one.one`
No match: Request passed. Notice socks5h used with curl to pass dns resolve to the proxy

`curl -x socks5://socks.domain.tld:1080 one.one.one.one`
No match: Request passed. This is resolved locally, and in the 3proxy log we can observe "CONNECT 1.1.1.1". In my mind this should match, and the request should be blocked.

As I've mentioned above, "pcre request deny" doesen't match anything.

**Comment by ezbik** [comment]
> `pcre clidata deny ".*\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}.*"`

What if you request `http://gmail.com?ip=1.1.1.1`  , will it be blocked?

**Comment by z3APA3A** [comment]
Try latest master, I've added request filtering to SOCKS with dc7e098e6b5563e1f31bdd1ad165a64f4983fd3c

**Comment by icmono** [comment]
compiled latest master.
I can confirm `pcre request deny` is working properly with socks.
