### ISSUE TITLE
3proxy compile for mips architecture

### ISSUE THREAD

**Issue by Chaxalyan** [3proxy/3proxy#957]
необходимо было компилировать 3proxy для архитектуры mips / mipsbe  ,для работы с openwrt

 на устройстве openwrt нет свободного места для компиляции ,, и пришлось сделать кросс компиляцию 

после переместил прогу на openwrt и когда пробую запустить ,система не видит файл 

root@metarouter:/usr/bin# 3proxy
/bin/ash: 3proxy: not found
root@metarouter:/usr/bin# ls
3proxy                   haserl                   smtpp
........................................

как быть

**Comment by z3APA3A** [comment]
chmod a+x 3proxy
./3proxy

**Comment by Chaxalyan** [comment]
![image](https://github.com/3proxy/3proxy/assets/35335774/d36fe6b3-3848-45b0-9e45-17c387510259)

dont solved
