### ISSUE TITLE
3proxy resolve RFC 6146 AAAA address instead of usual AAAA in socks5-mode

### ISSUE THREAD

**Issue by nohitmai** [3proxy/3proxy#958]
I have a VPS with one IPv4 address (192.0.2.1) and a /64 block of IPv6 addresses (2001:db8:0:2e::). I am attempting to set up a proxy where all clients can connect to the IPv4 address and access an IPv6-only resources. So, I'm expecting that any of client shouldn't resolve A-ns-records. However I've get AAAA-record with A-record content formatted according to RFC6146 but my VPS hasn't NAT64. That's makes socks5h mode unusable for IPv6. 

My config:

```
nserver 2001:4860:4860::8888
nserver 2001:4860:4860::8844

users proxyuser:CL:password
allow *
log
rotate 30
auth none
socks -6 -i192.0.2.1 -p31202 -e2001:db8:0:2e::2
```

Steps to reproduce:

- run server with `3proxy ./3proxy.cfg &`
- execute curl with socks options on the same machine

```
root@ubuntu:/tmp# curl --anyauth -x socks5h://192.0.2.1:31202/ -k https://icanhazip.com -v
*   Trying 192.0.2.1:31202...
* SOCKS5 connect to icanhazip.com:443 (remotely resolved)
* SOCKS5 request granted.
* Connected to (nil) (192.0.2.1) port 31202 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, decode error (562):
* error:0A000126:SSL routines::unexpected eof while reading
* Closing connection 0
curl: (35) error:0A000126:SSL routines::unexpected eof while reading
root@ubuntu:/tmp# curl --anyauth -x socks5://192.0.2.1:31202/ -k https://icanhazip.com -v
*   Trying 192.0.2.1:31202...
* SOCKS5 connect to IPv6 2606:4700::6812:7261:443 (locally resolved)
* Can't complete SOCKS5 connection to icanhazip.com. (5)
* Closing connection 0
curl: (97) Can't complete SOCKS5 connection to icanhazip.com. (5)
```

Logs:
```
230710213125.414 31202 00013 - 192.0.2.1:40192 ::ffff:46.137.136.169:443 0 0 0 CONNECT ::ffff:46.137.136.169:443
230710213443.429 31202 00013 - 192.0.2.1:35964 2606:4700::6812:7261:443 0 0 0 CONNECT 2606:4700::6812:7261:443
```

Version: 0.9.4

**Comment by z3APA3A** [comment]
In both cases proxy has not received hostname. In the first case IPv4 or RFC6146  address was received, and in the second case IPv6 was received. In the case of hostname, log record looks like this:

230711090917.995 1235 00000 - 127.0.0.1:60578 ::ffff:104.18.114.97:443 580 3159 0 CONNECT icanhazip.com:443
