### ISSUE TITLE
I am unable to add users and restrict IP addresses.

### ISSUE THREAD

**Issue by topmask** [3proxy/3proxy#959]
I have installed 3proxy on Debian, but I am unable to use /etc/3proxy/conf/add3proxyuser.sh to set the password for the admin user. It says I don't have sufficient permissions, even though I am using the root user. I checked and found that 3proxy is running with the proxy user's permissions. I don't know how to resolve this issue. Additionally, I am having trouble configuring the proxy to only allow incoming connections from my IP. Could you please help me take a look at the configuration?

```

nscache 65536
nserver 8.8.8.8
nserver 8.8.4.4
nserver 1.1.1.1
nserver 1.0.0.1

config /conf/3proxy.cfg
monitor /conf/3proxy.cfg

log /logs/3proxy.log D
rotate 7

counter /count/3proxy.3cf

users $/conf/passwd

include /conf/counters
include /conf/bandlimiters

auth iponly strong
allow * * 121.23.22.22
deny *

flush

socks -n -p2222 -a

flush

proxy -n -p3333 -a

allow

maxconn 50


```

**Comment by z3APA3A** [comment]
"flush" removes all previous ACLs. Also, you set your IP as destination instead of source. You need something like
```
auth iponly
allow * 121.23.22.22
deny *
socks ...
proxy ...

auth strong
admin
```
