### ISSUE TITLE
503 Service Unavailable Recursion detected

### ISSUE THREAD

**Issue by skorohim** [3proxy/3proxy#960]
Помогите пожалуйста кто сталкивался проблема с 3proxy ставлю на виндовс 11 в качестве личной прокси использую модем мегафона все работало на 10 винде пробую тут выскакивает ошибка рекурсии 2 день бьюсь вот простой конфиг который до этого работал service
monitor C:\3proxy\bin64\3proxy.txt
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
auth none
proxy -p5054 -i192.168.0.187 -e192.168.1.100
flush

пробовал на 2х машинах win 11 результат одинаковый

**Comment by z3APA3A** [comment]
Что именно выскакивает?

**Comment by skorohim** [comment]
По логам жалуется на 00013 я так понял что у меня Виндоус просто не даёт 2м одновременно устройствам получать интернет где то в реестре надо смотреть вай фай отключаю на модем спокойно кидает и пакеты идут тут не в 3proxy беда извиняюсь буду искать .... Нужно чтобы видна одновременно видела и модем и вайфай и одновременно получала с них инет так как когда вайфай включен и делаешь рестарт 3proxy она несколько пакетов которые идут к модему пропускает. Если кто знает где в реестре поправить напишите пожалуйста!

**Comment by skorohim** [comment]
Решено 
 Увеличение максимального количества одновременных TCP/IP-соединений в Windows 7/8/10
1. Запустите Редактор реестра (Win+R -> regedit -> Enter)

2. Перейдите по пути:

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Tcpip\Parameters

3. Создайте параметр DWORD (32-бита) с наименованием MaxUserPort и значением FFFE

4. Создайте параметр DWORD (32-бита) с наименованием EnableConnectionRateLimiting и значением 0

5. Перезагрузите компьютер".

"FFFE" в десятичной системе будет равно 65534.
