### ISSUE TITLE
Can't get the proxy to work on Windows

### ISSUE THREAD

**Issue by LeBesta** [3proxy/3proxy#961]
Hey, I apologize if this is not the place to ask for help, but I'm desperate.

I wanted a simple mapping to inject the authentication into a proxy, such a [this](https://github.com/sjitech/proxy-login-automator). So that any request that was sent to port 8081 would use the proxy. After aimlessly messing around I came to this, but nothing seems to get me through the "Failed to create service: No error" or "Failed to start service: No error" messages.

```
daemon

nserver 4.4.4.4
nserver 8.8.8.8
nscache 65536
nscache6 65536

auth none
external 0.0.0.0
internal 127.0.0.1

deny * * 127.0.0.1,192.168.1.1

allow * * * 80-88,8080-8088 HTTP
allow * * * 443,8443 HTTPS

socks -p8081

proxy -n -p7777 -i127.0.0.1 -eUserName:Password@proxy.url
```

Can someone enlighten me? 
If this is not the right place I will promptly close this issue.

**Comment by tranlam20220101** [comment]
@LeBesta proxy does not work latest version but sock still works
@z3APA3A you need to investigate this bug

**Comment by z3APA3A** [comment]
-e specifies external IP address (same as external), "HTTP" and "HTTPS" in allow does not work with SOCKSv5, "auth none" disables any ACLs and parents. Whay you need is something like this:
```

auth iponly
deny * * 127.0.0.1,192.168.1.1
allow * * * 80-88,8080-8088,443,8443
parent 1000 proxy_type proxy_ip proxy_port poxy_login proxy_password
deny *
socks -p8081
proxy -n -p7777
```
