### ISSUE TITLE
0.9.4 parent extip  ipv6  can't random ipv6 of every request?

### ISSUE THREAD

**Issue by doim** [3proxy/3proxy#965]
@z3APA3A   

every request alway get the same ipv6. what's wrong of my config?

## 0.   3proxy 0.9.4
#ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 209.141.55.22  netmask 255.255.255.0  broadcast 209.141.55.255
        inet6 2605:6400:48:4185:73b2:d1dd:c794:1df4  prefixlen 48  scopeid 0x0<global>
        inet6 2605:6400:48:99c0:b3b6:cbbb:6415:9f16  prefixlen 48  scopeid 0x0<global>
        inet6 2605:6400:48:886f:ff7:b366:fd3f:160a  prefixlen 48  scopeid 0x0<global>
....

## 1.
#cat 3proxy.cfg    
--------
daemon
maxconn 5000
nscache 65536
log /var/log/3proxy/3proxy.log D
logformat "%e"
rotate 2  

nserver 8.8.8.8
nserver 8.8.4.4
nserver [2001:4860:4860:0:0:0:0:8888]
timeouts 1 5 30 60 180 1800 15 60
setgid 65535
setuid 65535

users usryourname:CL:pass065
authcache user 60
auth strong cache
flush
deny * * 127.0.0.1
allow usryourname
allow * * ::/0
parent 1000 extip 2605:6400:48::/48 0
proxy -6 -s0 -n -a -p3128

### every request ,always get the same ipv6 "2605:6400:48:886f:ff7:b366:fd3f:160a"

#curl -x usryourname:pass065@209.141.55.22:3128 icanhazip.com
2605:6400:48:886f:ff7:b366:fd3f:160a
#curl -x usryourname:pass065@209.141.55.22:3128 icanhazip.com
2605:6400:48:886f:ff7:b366:fd3f:160a
#curl -x usryourname:pass065@209.141.55.22:3128 icanhazip.com
2605:6400:48:886f:ff7:b366:fd3f:160a
root@localhost:/opt/3proxy#

**Comment by z3APA3A** [comment]
parent is applied to preceding 'allow' rule, in your case to `allow * * ::/0`, but effective rule in your case is `allow usryourname`. Add parent after both allow rules.

**Comment by doim** [comment]
thank you very much . can help me modify the config below?thank you .
-------------
daemon
maxconn 5000
nscache 65536
log /var/log/3proxy/3proxy.log D
logformat "%e"
rotate 2

nserver 8.8.8.8
nserver 8.8.4.4
nserver [2001:4860:4860:0:0:0:0:8888]
timeouts 1 5 30 60 180 1800 15 60
setgid 65535
setuid 65535

users usryourname:CL:pass065
authcache user 60
auth strong cache
flush
deny * * 127.0.0.1
allow usryourname
allow * * ::/0
parent 1000 extip 2605:6400:48::/48 0
proxy -6 -s0 -n -a -p3128

**Comment by doim** [comment]
# 1. chang config blow ,but still same external ip( ipv6 who is last added to eth0) by every request.
------------------------
auth none
flush
allow * * ::/0
parent 1000 extip 2605:6400:48::/48 0
proxy -6 -s0 -n -a -p3128

# 2. ifconfig eth0
-------------
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 209.141.55.82  netmask 255.255.255.0  broadcast 209.141.55.255
        inet6 2605:6400:48:886f:ff7:b366:fd3f:160a  prefixlen 48  scopeid 0x0<global>
        inet6 2605:6400:48:f897:8d29:a4d4:9496:923b  prefixlen 48  scopeid 0x0<global>
        inet6 2605:6400:20:e5:fa82:ae0b:5e66:d632  prefixlen 48  scopeid 0x0<global>
        inet6 fe80::216:17ff:fe61:1536  prefixlen 64  scopeid 0x20<link>
        ether 00:16:17:61:15:36  txqueuelen 1000  (Ethernet)
        RX packets 6056  bytes 526420 (526.4 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4493  bytes 707453 (707.4 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

# 3. every request ,alway same ipv6 of  last added to eth0
-----------------------
~# curl -x usryourname:pass098765@209.141.55.82:3128 icanhazip.com
## 2605:6400:48:f897:8d29:a4d4:9496:923b
~# curl -x usryourname:pass098765@209.141.55.82:3128 icanhazip.com
## 2605:6400:48:f897:8d29:a4d4:9496:923b
~# curl -x usryourname:pass098765@209.141.55.82:3128 icanhazip.com
## 2605:6400:48:f897:8d29:a4d4:9496:923b

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtoe.asp#LIMITS
`auth none` disables ACLs.

**Comment by doim** [comment]
thank you. help,how can i correct this config ...
------------
users usryourname:CL:pass065
authcache user 60
auth strong cache
allow usryourname                                 <--------------
allow * * ::/0                                             <------------------
parent 1000 extip 2605:6400:48::/48 0
proxy -6 -s0 -n -a -p3128
