### ISSUE TITLE
проблема с открытием некоторых сайтов (play.google.com)

### ISSUE THREAD

**Issue by BAXONnt** [3proxy/3proxy#967]
Ситуация такая: приобрел VPS, поднял на нём 3proxy, OpenVPN. Вроде всё работает, но есть нюанс.
В частности при подключении через OpenVPN сайт play.google.com открывается, но если подключаться в браузере через прокси, то он не открывается, выдает: "Не удается получить доступ к сайту Соединение сброшено".
Конфиг 3proxy делал минимальным, всё равно не работает:
 
nserver 8.8.8.8
nserver 77.88.8.8
nserver [2001:4860:4860::8844] 
timeouts 1 5 30 60 180 1800 15 60
external 5.*.*.83
external 2a00:*:*:*::*:* 
internal 5.*.*.83
proxy -64 -p2324 -n -a
socks -p2325 -n -a

В логах никаких ошибок нет, но сайт не открывается. 
logformat "- +_L%t.%.  %N.%p %E %U %C:%c %R:%r %O %I %h %T"

Тут play.google.com не открылся, а ipsee.ru нормально открылся и показывает адрес прокси. Ни через HTTP, ни через SOCKS5 play.google.com не работает
1691854318.519  SOCK5.51325 00000 - 46.122.22.205:55487 173.194.222.102:443 517 6772 0 CONNECT_play.google.com:443
1691854325.447  SOCK5.51325 00000 - 46.122.22.205:55488 77.222.40.195:443 1521 10167 0 CONNECT_ipsee.ru:443 

1691855150.749  PROXY.51324 00000 - 46.122.22.205:55604 2a00:1450:4010:c0b::8a:443 517 6771 0 CONNECT_play.google.com:443_HTTP/1.1
1691855161.694  PROXY.51324 00000 - 46.122.22.205:55605 77.222.40.195:443 1602 10198 0 CONNECT_ipsee.ru:443_HTTP/1.1
Что добавить в конфиг, чтобы завелось?

**Comment by z3APA3A** [comment]
00000 означает что соединение было завершено штатно по инициативе сервера или клиента, вряд ли тут что-то можно сделать на стороне прокси. Возможно play.google.com не нравится IPv6 сеть через которую ты приходишь, попробуй, например, proxy -46
