### ISSUE TITLE
hi acctstarttime not right format 3proxy send unixtime mysql wait datetime 

### ISSUE THREAD

**Issue by bottookku** [3proxy/3proxy#972]
Tue Sep  5 22:34:56 2023 : ERROR: (56) sql: ERROR: rlm_sql_mysql: ERROR 1292 (Incorrect datetime value: '1693919668' for column 'acctstarttime' at row 1): 22007

**Comment by bottookku** [comment]
кто виноват фрирадиус или 3прокси, просто тип данных на число поменяю в таблице.

**Comment by z3APA3A** [comment]
3proxy в mysql ничего не шлет. Более того, он и время в RADIUS не шлет

**Comment by bottookku** [comment]
почему эта ошибка выходит во время того как нажимаю f5 на браузере который через прокси подключено 3 устолйсьва который подключен к Mylsq

**Comment by bottookku** [comment]
а понял это ошибка самого радиуса.. но я не понял это

` Configures RADIUS servers to be used for logging and authentication (log and auth types
must be set to radius). port and local address to use with given server may be specified.
.br
 Attributes within request: User-Name, Password: (username and password if presented by client),
Service Type: Authenticate-Only,
NAS-Port-Type: NAS-Port-Virtual,
NAS-Port-ID: (proxy service port, e.g. 1080),
NAS-IPv6-Address / NAS-IP-Address: (proxy interface accessed by client),
NAS-Identifier: (text identifing proxy, e.g. PROXY or SOCKSv5),
Framed-IPv6-Address / Framed-IP-Address: (IP address of the client),
Called-Station-ID: (requested Hostname, if presents),
Login-Service: (type of request, e.g. 1001 - SOCKS CONNECT, 1010 - HTTP GET, 1013 - HTTP CONNECT),
Login-TCP-Port: (requested port),
Login-IPv6-Host / Login-IP-Host: (requested IP). 
.br
 Supported reply attributes for authentication:
Framed-IP-Address / Framed-IPv6-Address (IP to assign to user), Reply-Message.
Use authcache to speedup authentication. RADIUS feature is currently experimental.`

радиус в ответе на авторизацию или аутентификации должен слать следующие кастомные атрибуты::???
чтобы например задать определенный IP для каждого пользователя? 
или это просто для записи в журнал RADIUS-а??


NAS-IP-Address - это IP с которого должен зайти пользователь? он не сможет с других кроме этого?
Login-IP-Host - это тот айпи который хочет получить? я не понял..
Framed-IP-Address - это как он назначит пользователю ip создает у себя какието виртуальные IP?

**Comment by bottookku** [comment]
спасибо за то что создал такую замечательную вещ действительно после SQUID на первом месте
