### ISSUE TITLE
have analog -De for radius?

### ISSUE THREAD

**Issue by bottookku** [3proxy/3proxy#975]
есть ли аналог команды -De в радиусе?

**Comment by z3APA3A** [comment]
Нет, сейчас интерфейсы можно указать только на сервис целиком. Но биндинг по интерфейсам в любом случае не рекомендуется делать, правильно делать биндинг по IP адресам, а использование интерфейсов настраивать за счет source routing (т.е. добавить правила что с такого-то IP трафик должен идти в такой-то интерфейс)
