### ISSUE TITLE
Цепочек (каскадный) прокси

### ISSUE THREAD

**Issue by OmetovVlad** [3proxy/3proxy#979]
Добрый день.
У меня вопрос касаемо цепочек прокси - у нас есть список прокси, нам нужно чтобы из под наших прокси работали прокси из списка.

Делаем следующим образом:

allow *
parent 1000 http proxy port login pass
proxy -n -p10000

flush
allow *
parent 1000 http proxy2 port login pass
proxy -n -p10001

Но при подключении к нашей прокси мы видим наш ip, а должны видеть ip прокси которую указали в parent

**Comment by z3APA3A** [comment]
Что стоит в auth?

**Comment by OmetovVlad** [comment]
> Что стоит в auth?

Там и была ошибка ) Все поправили
