### ISSUE TITLE
Whitelist incoming IP address

### ISSUE THREAD

**Issue by SalimF** [3proxy/3proxy#980]
Hi, for compatibility with Chrome app (_mostly headless chrome_ ) I config m 3proxy to not use Authentication, 

later on, I notice some bots start using my proxy port after scanning my IP address...

How to prevent this using the config file, here is mine contents, but it still didn't work 

```
#config /usr/local/3proxy/3proxy.cfg
nserver 1.1.1.1
nserver 1.0.0.1
nscache 65536
# clients
timeouts 1 5 30 60 180 1800 15 60
#users 3APA3A:CL:3apa3a "test:CR:$1$qwer$CHFTUFGqkjue9HyhcMHEe1"
daemon
#log /usr/local/etc/3proxy/logs/3proxy.log D
logformat "- +_L%t.%.  %N.%p %E %U %C:%c %R:%r %O %I %h %T"
archiver gz /bin/gzip %F
rotate 30
auth iponly
# Use default ACLs, don't need to flush
deny * * 127.0.0.1,192.168.1.1
allow * * * 80-88,8080-8088 HTTP
allow * * * 443,8443 HTTPS
allow * * 111.111.111.0/14 # this is not real IP
deny * 
proxy -n -u -p9999 -a -e111.111.111.111 # this is not real IP
#SOCKS
flush
#auth none cache
socks  -n -u -p9998 -a -e111.111.111.111 # this is not real IP
```

**Comment by z3APA3A** [comment]
either limit access by source IP address of enable authentication. To access from chrome you can install local proxy service on the host with Chrome without authentication, configure remote proxy service as a parent and configure local proxy server in Chrome.
