### ISSUE TITLE
Random 407 from proxy

### ISSUE THREAD

**Issue by Kukiezi** [3proxy/3proxy#982]
When launching my 3proxy server and testing it via curl or anything, Im getting like 90-95% success rate, and sometimes 407 back.
I found it weird, because if it's passing authentication, why should it fail sometimes randomly?

Im using `auth iponly strong cache`
and cache is set to `authcache user 10` for testing now low value.

I tried reloading via admin web ui, but didn't help.

Finally I went into `scripts/init.d` and run the stop command. Then started the 3proxy via .cfg again, and the issue was gone.
That being said, it is not the first time it happened to me. For now it seems to be fine, but I am wondering if there is some kind of cache or loadbalancing happening there?

**Comment by ZairKSM** [comment]
Hello, I have the same problem, I have randomly a 407 like you here is my 3proxy.cfg

`#! /usr/local/bin/3proxy

daemon

nserver 8.8.8.8

nscache 65536

timeouts 600 600 600 600 600 600 600

users root:pass

log /var/log/3proxy.log

#rotate 30

setgid 13

setuid 13

auth strong

allow root

proxy -p3128 -Deusb0

flush
`

**Comment by ezbik** [comment]
logs of random 407? I encountered issues when proxy clients (browsers) don't obey with proxy password in their settings and send some requests  without proxy auth.

**Comment by ezbik** [comment]
also "random 407" may be because there are 2 or more running 3proxy  instances **on the same proxy port** with **different login/password**. Then with 50% likelihood your requests will reach **another** 3proxy  instance.

**Comment by z3APA3A** [comment]
Check the log, and "trace" request parameters via your ACL. For 
`auth iponly strong cache`
it's most likely you get 407 due to some request which is not allowed by ACL without authentication.
BTW "cache" is useless here, because you place it after "strong".
