### ISSUE TITLE
HTTPS proxy

### ISSUE THREAD

**Issue by Comandante1977** [3proxy/3proxy#983]
Добрый день.
Правильно я понимаю, что HTTPS прокси не реализована пока?
Имеется ввиду шифрация между клиентом и прокси.

**Comment by sws33** [comment]
Поддерживаю вопрос - шифруется ли трафик между сервером и клиентом при подключении модуля прозрачного прокси - https://3proxy.ru/plugins/SSLPlugin

**Comment by z3APA3A** [comment]
@Comandante1977  если имеется ввиду TLS между клиентом и прокси - пока нет

@swa33 - насколько я понимаю, твои вопросы не имеют отношения к исходному, они по прозрачной подмене сертификата. Один ключ используется для корневого/промежуточного сертификата которым подписываются сгенерированные сертификаты, второй ключ используется для сгенерированного сертификата конечного сервера, в целом это разные сертификаты, но технически лючи можно использоваться одинаковые. Прокси не выполняет полной проверки сертификата сервера назначения при передподписывании, поэтому в зависимости от сценария использования и угроз это может снижать безопасность использующих его клиентов

**Comment by z3APA3A** [comment]
https://github.com/3proxy/3proxy/commit/067fdd7f95001ba23ddb3bae66fd668e0965cae5 - можно пробовать
