### ISSUE TITLE
[Feature request] bind internal and external interface name instead of specified ip.

### ISSUE THREAD

**Issue by phamminhkhac** [3proxy/3proxy#985]
for example:
proxy -a -n -p1080 -i115.72.68.105 -e121.8.231.16
Can change to
proxy -a -n -p1080 iWan1 -epppoe-out2

**Comment by z3APA3A** [comment]
See -Di / -De parameters.

P.S. Under Linux binding to interface and binding to IP are different types of binding, both may be required in some cases.
