### ISSUE TITLE
В докере не пишет логи.

### ISSUE THREAD

**Issue by Comandante1977** [3proxy/3proxy#986]
Установил 3proxy в докер.
Файлы логов создает, но они пустые.
Папку логов замапил на хост.
Может что-то с правами?

docker-compose.yml

version: "2.1"
services:
  3proxy:
     image: 3proxy/3proxy:latest
     container_name: 3proxy
     volumes:
        - /root/3proxy/conf:/usr/local/3proxy/conf
        - /root/3proxy/conf/logs:/usr/local/3proxy/logs
     ports:
        - 32563:3128
        - 32564:1180
     restart: unless-stopped

Кусок из 3proxy.cfg

# Указываем путь к логам, формат лога и ротацию
log /logs/3proxy.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"

**Comment by Comandante1977** [comment]
Проверил без докера. В такой конфигурации они нигде не пишутся. Файлы пустые.
Если использовать параметр -l, то пишутся.

**Comment by z3APA3A** [comment]
Какой порядок команд в конфиге?

**Comment by Comandante1977** [comment]
nserver 8.8.8.8
nserver 8.8.4.4
timeouts 1 5 30 60 180 1800 15 60
nscache 65536
radius <radius secret> <ip>
authcache ip,user,password
auth cache radius
proxy -p3128 -n -a 
socks -p1180
log /usr/local/3proxy/logs/3proxy.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
rotate 30

**Comment by z3APA3A** [comment]
Порядок команд важен, log/logformat будет действовать только на сервисы которые указаны после этой команды
