### ISSUE TITLE
external ip

### ISSUE THREAD

**Issue by jonson2081** [3proxy/3proxy#987]
Hi, please suggest a solution.

I have two interfaces:
eth1 with ip 192.168.0.157/24
enx0c5b8f279a64 with ip 192.168.8.200

routes are configured:

ip route
default via 192.168.0.1 dev enp1s0 proto dhcp src 192.168.0.157 metric 100
default via 192.168.8.1 dev enx0c5b8f279a64 proto static metric 200

command ctrl --interface enx0c5b8f279a64 2ip.ru it is being executed and I get the correct answer

when using external 192.168.8.200 I don't get an answer

log after start
1699895431.181 SOCKS.1080 00000 - 0.0.0.0:0 192.168.8.200:0 0 0 0 Exiting_thread
1699895434.722 SOCKS.1080 00000 - 0.0.0.0:1080 192.168.8.200:0 0 0 0 Accepting_connections_[1481/4231161408]

when executing a request, nothing is written to the log, it hangs until the timeout closes, but I'm not getting an answer
3proxy    1414            root    3u  IPv4  30138      0t0  TCP gw4:1080->85.1.2.1:47481 (ESTABLISHED)
3proxy    1414            root    5u  IPv4  30112      0t0  TCP *:1080 (LISTEN)
3proxy    1414            root    6u  IPv4  31498      0t0  TCP gw4:43721->static.35.201.201.195.clients.your-server.de:80 (SYN_SENT)

**Comment by jonson2081** [comment]
tcpdump -i enx0c5b8f279a64 does not see any new packets when executing the request.

**Comment by z3APA3A** [comment]
Either use -De to specify external interface or configure [source route](https://www.google.com/search?q=linux+source+routing) (preferred) to route traffic from 192.168.8.200 via enx0c5b8f279a64

**Comment by jonson2081** [comment]
It's not about 3proxy.

It is not enough to register a route in netplan.  

Therefore, I had to use the route table as before.
