### ISSUE TITLE
parent error

### ISSUE THREAD

**Issue by tekh0** [3proxy/3proxy#989]
I want to use always new ipv6 from my ipv6 assigned network interfaces, but I have an error with the "parent function".

Error: Command: 'parent' failed with code 5, line 11

My 3proxy.cfg:
nserver 8.8.8.8
nserver 8.8.4.4
nscache 65536
timeouts 1 5 30 60 180 1800 15 60

config /etc/3proxy/3proxy.cfg
monitor /etc/3proxy/3proxy.cfg

auth iponly
allow *
parent 250 extip <MY_SUBNET_IPV6>::/48 0
proxy -6 -n -a -p30000 -i<MY_VPS_IP>

**Comment by z3APA3A** [comment]
which 3proxy version do you use?

also, sum weight of parents must be even of 1000.
