### ISSUE TITLE
Is there a way to setup rotating proxy?

### ISSUE THREAD

**Issue by itseyup** [3proxy/3proxy#992]
Hello, Is there a way to create a rotating proxy without writing external code? By rotating proxy I mean whenever a request comes to the proxy, it will change the IPv6 address on the defined subnet with subnet mask.

**Comment by nvtinh368** [comment]
You just need to edit a little in the source code to achieve that. it is very easy to do

**Comment by z3APA3A** [comment]
See parent extip

```
allow *
parent 1000 extip a:b:c::/64
```

selects external address randomely from subnetwork, but all IPs in subnetwork must be configured as local, that is you must be able to bind to this IP. It usually requires some trick with local routing or ip_nonlocal_bind

**Comment by z3APA3A** [comment]
See second reply [here](https://serverfault.com/questions/590038/adding-a-whole-ipv6-64-block-to-an-network-interface-on-debian/591435#591435).

**Comment by itseyup** [comment]
> See parent extip
> 
> ```
> allow *
> parent 1000 extip a:b:c::/64
> ```
> 
> selects external address randomely from subnetwork, but all IPs in subnetwork must be configured as local, that is you must be able to bind to this IP. It usually requires some trick with local routing or ip_nonlocal_bind

But how do I use it with specific username:password? For example I have a config file like this:
`
nserver 8.8.8.8
nserver 8.8.4.4
nscache6 65536
timeouts 1 5 30 60 180 1800 15 60
users testproxy:CL:test
daemon
log /dev/null
setgid 65535
setuid 65535
stacksize 1024000
authcache user 60
auth strong
allow *
parent 1000 extip a:b:c::/64
proxy -6 -n -a -p10021 -i[MYIPV4]
proxy -6 -n -a -p10022 -i[MYIPV4]
proxy -6 -n -a -p10023 -i[MYIPV4]
flush
`
But I get an error like this:
`Unknown command: 'parent' line 14`

**Comment by z3APA3A** [comment]
which 3proxy version do you use?

**Comment by z3APA3A** [comment]
Use
parent 1000 extip a:b:c::/64 0

**Comment by itseyup** [comment]
Okey It fixed it. Thank you!

**Comment by itseyup** [comment]
@z3APA3A 
One last question, lets say we have a file called "iplist.txt" which has bunch of IPv4 addresses in it. Is there a way to impelement this file with this rotating proxy feature?

**Comment by z3APA3A** [comment]
There is no way to work with this file directly. You can generate the set of rules
```
parent 250 extip IP1 0
parent 250 extip IP2 0
parent 250 extip IP3 0
parent 250 extip IP4 0
```
