### ISSUE TITLE
Multi ip usage

### ISSUE THREAD

**Issue by mustafasevincc** [3proxy/3proxy#993]
Hello, there is more than one external IP address on my server. Can I specify user-based logout ropes? How can I do it?

For example

username1 : 95.10.xx.10
username2: 95.10.xx.11
Username3: Let it use the IP address 95.10.xx.12.

I log in to the proxy with a verification username and password.

**Comment by z3APA3A** [comment]
```
allow username1
parent 1000 extip 95.10.xx.10 0
allow username2
parent 1000 extip 95.10.xx.11 0
allow username3
parent 1000 extip 95.10.xx.12 0
```
