### ISSUE TITLE
Error pages not working

### ISSUE THREAD

**Issue by iwyz0** [3proxy/3proxy#994]
Hello
We could not activate the error page that should appear when entering a banned site. Why could it be?

![image](https://github.com/3proxy/3proxy/assets/49274332/cfd4d357-5624-4c16-809c-ee268a54a77e)

monitor /opt/3proxy/cfg_file/test.cfg
plugin /opt/3proxy/bin/StringsPlugin.ld.so start /opt/3proxy/rus.3ps
daemon
maxconn 100000
nscache 65536
nserver 1.1.1.1
log /var/log/3proxy/test_log
rotate 120
logformat "L%t.%. %N.%p %E %U %e %C:%c %R:%r %O %I %h %T"
timeouts 1 5 30 60 180 1800 15 60
setgid 65535
setuid 65535
flush
bandlimin 15728640 * *
bandlimout 15728640 * *
users 3proxy:CL:3proxy
auth strong iponly
deny test * *google.com* * * *
allow test
auto -n -a1 -p8000 -iipadress -eipadress
flush

**Comment by z3APA3A** [comment]
https://  uses encrypted TLS connection and special "CONNECT" proxy command. You can not send any HTTP response from proxy in the case of https:// (without SSLPlugin and certificated spoofing at least).
