### ISSUE TITLE
Исключение некоторых сайтов из работы 3proxy

### ISSUE THREAD

**Issue by HopeLess27** [3proxy/3proxy#996]
Здравствуйте.

Для доступа к ограниченному набору сайтов нужно не использовать прокси-сервер. Как настроить конфиг 3proxy таким образом, что через прокси трафик будет идти не на все сайты, то есть чтобы некоторые сайты не проксировались?
Операционная система Windows.

Спасибо.

**Comment by z3APA3A** [comment]
Если запрос уже пришел в 3proxy то он уже пришел в прокси и прокси его может либо проксировать либо вернуть ошибку. Запретить доступ к сайтам можно через deny

```
deny * * site1,site2,site3
allow *
proxy
```

если надо чтобы клиенты для этих сайтов не ходили в прокси, то это решается на стороне клиента, или добавлением сайтов в исключения или за счет [WPAD](https://en.wikipedia.org/wiki/Web_Proxy_Auto-Discovery_Protocol)
