### ISSUE TITLE
Можно ли добавить код ошибки при Warning:_too_many_connected_clients

### ISSUE THREAD

**Issue by S-Mister-S** [3proxy/3proxy#997]
Привет!
Возможно ли добавить код ошибки в заголовок http (например, HTTP 409 Conflict, или что нибудь другое более подходящее), когда возникает Warning:_too_many_connected_clients

Иначе обрывается соединение по таймауту. 
Или так как сейчас реализовано на практике лучше?

Хотелось бы получить ответ.
Спасибо!

**Comment by z3APA3A** [comment]
При превышении maxconn соединение не обрабатывается, поэтому что-либо отправить в него нельзя. Таймауты тут непричем, оно закрывается сразу.
