### ISSUE TITLE
Вопросы по настройки IPV6 прокси

### ISSUE THREAD

**Issue by Vision20202** [3proxy/3proxy#998]
Задача - настроить мобильный прокси и поддержкой IPV6. Дано - модем с работающим IPV4 и IPV6. 
Пробела номер один - непонятно какой адрес IPV6 у модема. Дофига адресов, есть конечно локальный fe80::c4e8:f361:6a3:cdc5%18, но как я его не записывал - не работает:
fe80::c4e8:f361:6a3:cdc5%18
fe80::c4e8:f361:6a3:cdc5

Единственный способ, который сработал, это использовать фактически IPV4 адрес модема:
proxy -6 -n -p6565 -i192.168.1.211 -e192.168.30.100

Но это тянет, возможно, проблемы с маршрутизацией, это догадка, но пока не могу проверить. Везде, во всех статьях, по настройке IPV6 используют IPV6 адрес интерфейса. Но как его определить у модема?

**Comment by z3APA3A** [comment]
Такая конфигурацию соответствует отсутствию заданного внешнего адреса. Если адрес не задан или задан нулевой адрес, то система автоматически выбирает адрес. Если такой подход устраивает, то внешний адрес можно не задавать.

**Comment by Vision20202** [comment]
Если выставить нулевой адрес, т.е. 0.0.0.0 работать как раз не будет.

**Comment by z3APA3A** [comment]
В IPv6 нулевой адрес обозначается :: или ::0

**Comment by z3APA3A** [comment]
0.0.0.0 ни на что влияет, так же как и -e192.168.30.100

**Comment by Vision20202** [comment]
Поставил ::0 вместо 192.168.30.100 и теперь у меня IPV6 от модема, а IPV4 от проводного провайдера, очень забавно... Ну я к тому, что 192.168.30.100 вообще, ни разу не равно  ::0, ибо 192.168.30.100 конкретный интерфейс модема, а не с потолка взятый.

**Comment by z3APA3A** [comment]
При -6 не использвется IPv4

**Comment by z3APA3A** [comment]
Потому что прописывать надо IP адрес локального интерфейса, а не шлюза https://3proxy.ru/howtor.asp#INTEXT

**Comment by Vision20202** [comment]
proxy -4 -n -p6565 -i192.168.1.211 -e192.168.30.100
Ну и что здесь не правильно? 192.168.1.211 - интерфейс локальный, т.е. проводной интернет. 192.168.30.100 - интерфейс модема, для создания прокси через модем.
И всё прекрасно работает, пока это IPV4, а с 6-кой нифига не работает, когда адрес интерфейса у модема fe80::c4e8:f361:6a3:cdc5%18

**Comment by z3APA3A** [comment]
fe80::c4e8:f361:6a3:cdc5%18 - это link-local адрес, с него невозможно выходить во внешнюю сеть

**Comment by Vision20202** [comment]
Люди добрые, подайте кто сколько может. :) Как всё таки у модема правильно задать IPV6 адрес? IPV4 адрес хоть и работает, но там другие баги вылезают - у всех интерфейсов становится одинаковый IPV6 адрес.
