### ISSUE TITLE
Опции -Di и -De - как это работает? 

### ISSUE THREAD

**Issue by Vision20202** [3proxy/3proxy#999]
В сети почти ноль информации про опции -Di и -De. Я так понимаю, вместо IP можно указать номер/название интерфейса. Но как бы понять, что этим названием является в Windows и Linux? Т.к. как это должно выглядеть? Ну или как в той же Windows узнать, как конкретно прописать интерфейс по имени, а не IP.

**Comment by z3APA3A** [comment]
Биндинг к интерфейсу не поддерживается в Windows. В Windows биндинг по IP адресу одновременно является биндингом к интерфейсу, поэтому достаточно биндинга по IP адресу. В Linux это не так, поэтому можно прибиндиться к IP адресу, можно к интерфейсу, и одно не заменяет другое

**Comment by Vision20202** [comment]
Если интерфейс называется eth9, то вот так правильно будет: -Deeth9?

**Comment by Vision20202** [comment]
Service not started on line: 37
Command: 'proxy' failed with code 40, line 37

37 строка это:
proxy -64 -n -p17500 -i192.168.1.10 -De(eth9)

**Comment by z3APA3A** [comment]
-Deeth9

для биндинга к интерфейсу необходимо запускать из-под рута или с CAP_NET_RAW
